// AUTO-GENERATED by scripts/build-catalog.mjs — do not edit

import petListeningBook2Test1 from '../data/listening-pet-b1-book2-test1.json'
import petListeningBook2Test2 from '../data/listening-pet-b1-book2-test2.json'
import petListeningBook2Test3 from '../data/listening-pet-b1-book2-test3.json'
import petListeningBook2Test4 from '../data/listening-pet-b1-book2-test4.json'
import petListeningBook3Test1 from '../data/listening-pet-b1-book3-test1.json'
import petListeningBook3Test2 from '../data/listening-pet-b1-book3-test2.json'
import petListeningBook3Test3 from '../data/listening-pet-b1-book3-test3.json'
import petListeningBook3Test4 from '../data/listening-pet-b1-book3-test4.json'
import petListeningBook4Test1 from '../data/listening-pet-b1-book4-test1.json'
import petListeningBook4Test2 from '../data/listening-pet-b1-book4-test2.json'
import petListeningBook4Test3 from '../data/listening-pet-b1-book4-test3.json'
import petListeningBook4Test4 from '../data/listening-pet-b1-book4-test4.json'
import petListeningBook5Test1 from '../data/listening-pet-b1-book5-test1.json'
import petListeningBook5Test2 from '../data/listening-pet-b1-book5-test2.json'
import petListeningBook5Test3 from '../data/listening-pet-b1-book5-test3.json'
import petListeningBook5Test4 from '../data/listening-pet-b1-book5-test4.json'
import petListeningBook6Test1 from '../data/listening-pet-b1-book6-test1.json'
import petListeningBook6Test2 from '../data/listening-pet-b1-book6-test2.json'
import petListeningBook6Test3 from '../data/listening-pet-b1-book6-test3.json'
import petListeningBook6Test4 from '../data/listening-pet-b1-book6-test4.json'
import petListeningBook7Test1 from '../data/listening-pet-b1-book7-test1.json'
import petListeningBook7Test2 from '../data/listening-pet-b1-book7-test2.json'
import petListeningBook7Test3 from '../data/listening-pet-b1-book7-test3.json'
import petListeningBook7Test4 from '../data/listening-pet-b1-book7-test4.json'
import petListeningBook8Test1 from '../data/listening-pet-b1-book8-test1.json'
import petListeningBook8Test2 from '../data/listening-pet-b1-book8-test2.json'
import petListeningBook8Test3 from '../data/listening-pet-b1-book8-test3.json'
import petListeningBook8Test4 from '../data/listening-pet-b1-book8-test4.json'
import petListeningBook9Test1 from '../data/listening-pet-b1-book9-test1.json'
import petListeningBook9Test2 from '../data/listening-pet-b1-book9-test2.json'
import petListeningBook9Test3 from '../data/listening-pet-b1-book9-test3.json'
import petListeningBook9Test4 from '../data/listening-pet-b1-book9-test4.json'

export const GENERATED_PET_LISTENING_EXAMS = [
  petListeningBook2Test1,
  petListeningBook2Test2,
  petListeningBook2Test3,
  petListeningBook2Test4,
  petListeningBook3Test1,
  petListeningBook3Test2,
  petListeningBook3Test3,
  petListeningBook3Test4,
  petListeningBook4Test1,
  petListeningBook4Test2,
  petListeningBook4Test3,
  petListeningBook4Test4,
  petListeningBook5Test1,
  petListeningBook5Test2,
  petListeningBook5Test3,
  petListeningBook5Test4,
  petListeningBook6Test1,
  petListeningBook6Test2,
  petListeningBook6Test3,
  petListeningBook6Test4,
  petListeningBook7Test1,
  petListeningBook7Test2,
  petListeningBook7Test3,
  petListeningBook7Test4,
  petListeningBook8Test1,
  petListeningBook8Test2,
  petListeningBook8Test3,
  petListeningBook8Test4,
  petListeningBook9Test1,
  petListeningBook9Test2,
  petListeningBook9Test3,
  petListeningBook9Test4,
]
