// AUTO-GENERATED by scripts/build-catalog.mjs — do not edit

import fceListeningBook2Test1 from '../data/listening-fce-b2-book2-test1.json'
import fceListeningBook2Test2 from '../data/listening-fce-b2-book2-test2.json'
import fceListeningBook2Test3 from '../data/listening-fce-b2-book2-test3.json'
import fceListeningBook2Test4 from '../data/listening-fce-b2-book2-test4.json'
import fceListeningBook3Test1 from '../data/listening-fce-b2-book3-test1.json'
import fceListeningBook3Test2 from '../data/listening-fce-b2-book3-test2.json'
import fceListeningBook3Test3 from '../data/listening-fce-b2-book3-test3.json'
import fceListeningBook3Test4 from '../data/listening-fce-b2-book3-test4.json'
import fceListeningBook4Test1 from '../data/listening-fce-b2-book4-test1.json'
import fceListeningBook4Test2 from '../data/listening-fce-b2-book4-test2.json'
import fceListeningBook4Test3 from '../data/listening-fce-b2-book4-test3.json'
import fceListeningBook4Test4 from '../data/listening-fce-b2-book4-test4.json'
import fceListeningBook5Test1 from '../data/listening-fce-b2-book5-test1.json'
import fceListeningBook5Test2 from '../data/listening-fce-b2-book5-test2.json'
import fceListeningBook5Test3 from '../data/listening-fce-b2-book5-test3.json'
import fceListeningBook5Test4 from '../data/listening-fce-b2-book5-test4.json'
import fceListeningBook6Test1 from '../data/listening-fce-b2-book6-test1.json'
import fceListeningBook6Test2 from '../data/listening-fce-b2-book6-test2.json'
import fceListeningBook6Test3 from '../data/listening-fce-b2-book6-test3.json'
import fceListeningBook6Test4 from '../data/listening-fce-b2-book6-test4.json'
import fceListeningBook7Test1 from '../data/listening-fce-b2-book7-test1.json'
import fceListeningBook7Test2 from '../data/listening-fce-b2-book7-test2.json'
import fceListeningBook7Test3 from '../data/listening-fce-b2-book7-test3.json'
import fceListeningBook7Test4 from '../data/listening-fce-b2-book7-test4.json'
import fceListeningBook8Test1 from '../data/listening-fce-b2-book8-test1.json'
import fceListeningBook8Test2 from '../data/listening-fce-b2-book8-test2.json'
import fceListeningBook8Test3 from '../data/listening-fce-b2-book8-test3.json'
import fceListeningBook9Test1 from '../data/listening-fce-b2-book9-test1.json'
import fceListeningBook9Test2 from '../data/listening-fce-b2-book9-test2.json'
import fceListeningBook9Test3 from '../data/listening-fce-b2-book9-test3.json'
import fceListeningBook9Test4 from '../data/listening-fce-b2-book9-test4.json'
import fceListeningBook10Test1 from '../data/listening-fce-b2-book10-test1.json'
import fceListeningBook10Test2 from '../data/listening-fce-b2-book10-test2.json'
import fceListeningBook10Test3 from '../data/listening-fce-b2-book10-test3.json'
import fceListeningBook10Test4 from '../data/listening-fce-b2-book10-test4.json'
import fceListeningBook11Test1 from '../data/listening-fce-b2-book11-test1.json'
import fceListeningBook11Test2 from '../data/listening-fce-b2-book11-test2.json'
import fceListeningBook11Test3 from '../data/listening-fce-b2-book11-test3.json'
import fceListeningBook11Test4 from '../data/listening-fce-b2-book11-test4.json'
import fceListeningBook12Test1 from '../data/listening-fce-b2-book12-test1.json'
import fceListeningBook12Test2 from '../data/listening-fce-b2-book12-test2.json'
import fceListeningBook12Test3 from '../data/listening-fce-b2-book12-test3.json'
import fceListeningBook12Test4 from '../data/listening-fce-b2-book12-test4.json'
import fceListeningBook13Test1 from '../data/listening-fce-b2-book13-test1.json'
import fceListeningBook13Test2 from '../data/listening-fce-b2-book13-test2.json'
import fceListeningBook13Test3 from '../data/listening-fce-b2-book13-test3.json'
import fceListeningBook13Test4 from '../data/listening-fce-b2-book13-test4.json'
import fceListeningBook14Test1 from '../data/listening-fce-b2-book14-test1.json'
import fceListeningBook14Test2 from '../data/listening-fce-b2-book14-test2.json'
import fceListeningBook14Test3 from '../data/listening-fce-b2-book14-test3.json'
import fceListeningBook14Test4 from '../data/listening-fce-b2-book14-test4.json'
import fceListeningBook15Test1 from '../data/listening-fce-b2-book15-test1.json'
import fceListeningBook15Test2 from '../data/listening-fce-b2-book15-test2.json'
import fceListeningBook15Test3 from '../data/listening-fce-b2-book15-test3.json'
import fceListeningBook15Test4 from '../data/listening-fce-b2-book15-test4.json'
import fceListeningBook16Test1 from '../data/listening-fce-b2-book16-test1.json'
import fceListeningBook16Test2 from '../data/listening-fce-b2-book16-test2.json'
import fceListeningBook16Test3 from '../data/listening-fce-b2-book16-test3.json'
import fceListeningBook16Test4 from '../data/listening-fce-b2-book16-test4.json'
import fceListeningBook17Test1 from '../data/listening-fce-b2-book17-test1.json'
import fceListeningBook17Test2 from '../data/listening-fce-b2-book17-test2.json'
import fceListeningBook17Test3 from '../data/listening-fce-b2-book17-test3.json'
import fceListeningBook17Test4 from '../data/listening-fce-b2-book17-test4.json'
import fceListeningBook18Test1 from '../data/listening-fce-b2-book18-test1.json'
import fceListeningBook18Test2 from '../data/listening-fce-b2-book18-test2.json'
import fceListeningBook18Test3 from '../data/listening-fce-b2-book18-test3.json'
import fceListeningBook18Test4 from '../data/listening-fce-b2-book18-test4.json'
import fceListeningBook19Test1 from '../data/listening-fce-b2-book19-test1.json'
import fceListeningBook19Test2 from '../data/listening-fce-b2-book19-test2.json'
import fceListeningBook19Test3 from '../data/listening-fce-b2-book19-test3.json'
import fceListeningBook19Test4 from '../data/listening-fce-b2-book19-test4.json'
import fceListeningBook20Test1 from '../data/listening-fce-b2-book20-test1.json'
import fceListeningBook20Test2 from '../data/listening-fce-b2-book20-test2.json'
import fceListeningBook20Test3 from '../data/listening-fce-b2-book20-test3.json'
import fceListeningBook20Test4 from '../data/listening-fce-b2-book20-test4.json'
import fceListeningBook21Test1 from '../data/listening-fce-b2-book21-test1.json'
import fceListeningBook21Test2 from '../data/listening-fce-b2-book21-test2.json'
import fceListeningBook21Test3 from '../data/listening-fce-b2-book21-test3.json'
import fceListeningBook21Test4 from '../data/listening-fce-b2-book21-test4.json'
import fceListeningBook22Test1 from '../data/listening-fce-b2-book22-test1.json'
import fceListeningBook22Test2 from '../data/listening-fce-b2-book22-test2.json'
import fceListeningBook22Test3 from '../data/listening-fce-b2-book22-test3.json'
import fceListeningBook22Test4 from '../data/listening-fce-b2-book22-test4.json'
import fceListeningBook23Test1 from '../data/listening-fce-b2-book23-test1.json'
import fceListeningBook23Test2 from '../data/listening-fce-b2-book23-test2.json'
import fceListeningBook23Test3 from '../data/listening-fce-b2-book23-test3.json'
import fceListeningBook23Test4 from '../data/listening-fce-b2-book23-test4.json'
import fceListeningBook24Test1 from '../data/listening-fce-b2-book24-test1.json'
import fceListeningBook24Test2 from '../data/listening-fce-b2-book24-test2.json'
import fceListeningBook24Test3 from '../data/listening-fce-b2-book24-test3.json'
import fceListeningBook24Test4 from '../data/listening-fce-b2-book24-test4.json'
import fceListeningBook25Test1 from '../data/listening-fce-b2-book25-test1.json'
import fceListeningBook25Test2 from '../data/listening-fce-b2-book25-test2.json'
import fceListeningBook25Test3 from '../data/listening-fce-b2-book25-test3.json'
import fceListeningBook25Test4 from '../data/listening-fce-b2-book25-test4.json'

export const GENERATED_FCE_LISTENING_EXAMS = [
  fceListeningBook2Test1,
  fceListeningBook2Test2,
  fceListeningBook2Test3,
  fceListeningBook2Test4,
  fceListeningBook3Test1,
  fceListeningBook3Test2,
  fceListeningBook3Test3,
  fceListeningBook3Test4,
  fceListeningBook4Test1,
  fceListeningBook4Test2,
  fceListeningBook4Test3,
  fceListeningBook4Test4,
  fceListeningBook5Test1,
  fceListeningBook5Test2,
  fceListeningBook5Test3,
  fceListeningBook5Test4,
  fceListeningBook6Test1,
  fceListeningBook6Test2,
  fceListeningBook6Test3,
  fceListeningBook6Test4,
  fceListeningBook7Test1,
  fceListeningBook7Test2,
  fceListeningBook7Test3,
  fceListeningBook7Test4,
  fceListeningBook8Test1,
  fceListeningBook8Test2,
  fceListeningBook8Test3,
  fceListeningBook9Test1,
  fceListeningBook9Test2,
  fceListeningBook9Test3,
  fceListeningBook9Test4,
  fceListeningBook10Test1,
  fceListeningBook10Test2,
  fceListeningBook10Test3,
  fceListeningBook10Test4,
  fceListeningBook11Test1,
  fceListeningBook11Test2,
  fceListeningBook11Test3,
  fceListeningBook11Test4,
  fceListeningBook12Test1,
  fceListeningBook12Test2,
  fceListeningBook12Test3,
  fceListeningBook12Test4,
  fceListeningBook13Test1,
  fceListeningBook13Test2,
  fceListeningBook13Test3,
  fceListeningBook13Test4,
  fceListeningBook14Test1,
  fceListeningBook14Test2,
  fceListeningBook14Test3,
  fceListeningBook14Test4,
  fceListeningBook15Test1,
  fceListeningBook15Test2,
  fceListeningBook15Test3,
  fceListeningBook15Test4,
  fceListeningBook16Test1,
  fceListeningBook16Test2,
  fceListeningBook16Test3,
  fceListeningBook16Test4,
  fceListeningBook17Test1,
  fceListeningBook17Test2,
  fceListeningBook17Test3,
  fceListeningBook17Test4,
  fceListeningBook18Test1,
  fceListeningBook18Test2,
  fceListeningBook18Test3,
  fceListeningBook18Test4,
  fceListeningBook19Test1,
  fceListeningBook19Test2,
  fceListeningBook19Test3,
  fceListeningBook19Test4,
  fceListeningBook20Test1,
  fceListeningBook20Test2,
  fceListeningBook20Test3,
  fceListeningBook20Test4,
  fceListeningBook21Test1,
  fceListeningBook21Test2,
  fceListeningBook21Test3,
  fceListeningBook21Test4,
  fceListeningBook22Test1,
  fceListeningBook22Test2,
  fceListeningBook22Test3,
  fceListeningBook22Test4,
  fceListeningBook23Test1,
  fceListeningBook23Test2,
  fceListeningBook23Test3,
  fceListeningBook23Test4,
  fceListeningBook24Test1,
  fceListeningBook24Test2,
  fceListeningBook24Test3,
  fceListeningBook24Test4,
  fceListeningBook25Test1,
  fceListeningBook25Test2,
  fceListeningBook25Test3,
  fceListeningBook25Test4,
]
