// AUTO-GENERATED by scripts/build-catalog.mjs — do not edit

import ieltsReadingCam9Test1 from '../data/reading-ielts-cam9-test1.json'
import ieltsReadingCam9Test2 from '../data/reading-ielts-cam9-test2.json'
import ieltsReadingCam9Test3 from '../data/reading-ielts-cam9-test3.json'
import ieltsReadingCam9Test4 from '../data/reading-ielts-cam9-test4.json'
import ieltsReadingCam10Test1 from '../data/reading-ielts-cam10-test1.json'
import ieltsReadingCam10Test2 from '../data/reading-ielts-cam10-test2.json'
import ieltsReadingCam10Test3 from '../data/reading-ielts-cam10-test3.json'
import ieltsReadingCam10Test4 from '../data/reading-ielts-cam10-test4.json'
import ieltsReadingCam11Test1 from '../data/reading-ielts-cam11-test1.json'
import ieltsReadingCam11Test3 from '../data/reading-ielts-cam11-test3.json'

export const GENERATED_IELTS_READING_EXAMS = [
  ieltsReadingCam9Test1,
  ieltsReadingCam9Test2,
  ieltsReadingCam9Test3,
  ieltsReadingCam9Test4,
  ieltsReadingCam10Test1,
  ieltsReadingCam10Test2,
  ieltsReadingCam10Test3,
  ieltsReadingCam10Test4,
  ieltsReadingCam11Test1,
  ieltsReadingCam11Test3,
]
