// AUTO-GENERATED by scripts/build-catalog.mjs — do not edit

import ketReadingBook4Test1 from '../data/reading-ket-a2-book4-test1.json'
import ketReadingBook4Test2 from '../data/reading-ket-a2-book4-test2.json'
import ketReadingBook4Test3 from '../data/reading-ket-a2-book4-test3.json'
import ketReadingBook4Test4 from '../data/reading-ket-a2-book4-test4.json'
import ketReadingBook5Test1 from '../data/reading-ket-a2-book5-test1.json'
import ketReadingBook5Test2 from '../data/reading-ket-a2-book5-test2.json'
import ketReadingBook5Test3 from '../data/reading-ket-a2-book5-test3.json'
import ketReadingBook5Test4 from '../data/reading-ket-a2-book5-test4.json'
import ketReadingBook6Test1 from '../data/reading-ket-a2-book6-test1.json'
import ketReadingBook6Test2 from '../data/reading-ket-a2-book6-test2.json'
import ketReadingBook6Test3 from '../data/reading-ket-a2-book6-test3.json'
import ketReadingBook6Test4 from '../data/reading-ket-a2-book6-test4.json'
import ketReadingBook7Test1 from '../data/reading-ket-a2-book7-test1.json'
import ketReadingBook7Test2 from '../data/reading-ket-a2-book7-test2.json'

export const GENERATED_KET_READING_EXAMS = [
  ketReadingBook4Test1,
  ketReadingBook4Test2,
  ketReadingBook4Test3,
  ketReadingBook4Test4,
  ketReadingBook5Test1,
  ketReadingBook5Test2,
  ketReadingBook5Test3,
  ketReadingBook5Test4,
  ketReadingBook6Test1,
  ketReadingBook6Test2,
  ketReadingBook6Test3,
  ketReadingBook6Test4,
  ketReadingBook7Test1,
  ketReadingBook7Test2,
]
