import type { SentenceStructure } from '@ryan/db'

type CatalogStructure = Omit<SentenceStructure, 'createdAt' | 'updatedAt'>

/**
 * Core curated sentence structures (UTF-8).
 * Gộp với EXTRA → 365 template unique (xem sentenceStructures.ts).
 */
export const CORE_SENTENCE_STRUCTURES: CatalogStructure[] = [
  {
    id: 'catalog:ss:just-because',
    title: "Just because ... doesn't mean ...",
    template: "Just because [A] doesn't mean [B].",
    description: 'Dùng để nói một lý do chưa đủ để kết luận điều gì.',
    category: 'Liên từ / Lý do',
    exampleA: 'you fail once',
    exampleB: 'you should give up',
    exampleNoteVi: 'Chỉ vì bạn thất bại một lần không có nghĩa là bạn nên bỏ cuộc.',
    starred: true,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:not-only',
    title: 'Not only ... but also ...',
    template: 'Not only [A], but also [B].',
    description: 'Nhấn mạnh hai ý song song.',
    category: 'Liên từ / Lý do',
    exampleA: 'is it cheap',
    exampleB: 'it is effective',
    exampleNoteVi: 'Không những rẻ mà còn hiệu quả.',
    starred: true,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:because-of',
    title: 'Because of ..., ...',
    template: 'Because of [A], [B].',
    description: 'Nêu nguyên nhân bằng cụm danh từ — vì… nên…',
    category: 'Liên từ / Lý do',
    exampleA: 'the heavy rain',
    exampleB: 'the match was cancelled',
    exampleNoteVi: 'Vì mưa to, trận đấu đã bị hủy.',
    starred: false,
    cefr: 'A2',
  },
  {
    id: 'catalog:ss:due-to',
    title: 'Due to ..., ...',
    template: 'Due to [A], [B].',
    description: 'Nguyên nhân trang trọng hơn because of.',
    category: 'Liên từ / Lý do',
    exampleA: 'a technical problem',
    exampleB: 'the flight was delayed',
    exampleNoteVi: 'Do sự cố kỹ thuật, chuyến bay bị trễ.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:as-a-result',
    title: 'As a result, ...',
    template: '[A]. As a result, [B].',
    description: 'Nêu kết quả — do đó / kết quả là…',
    category: 'Liên từ / Lý do',
    exampleA: 'He trained every day',
    exampleB: 'he won the competition',
    exampleNoteVi: 'Anh ấy tập mỗi ngày. Kết quả là anh ấy thắng cuộc thi.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:therefore',
    title: 'Therefore, ...',
    template: '[A]. Therefore, [B].',
    description: 'Kết luận logic — vì vậy…',
    category: 'Liên từ / Lý do',
    exampleA: 'The evidence is clear',
    exampleB: 'we should change the policy',
    exampleNoteVi: 'Bằng chứng rõ ràng. Vì vậy chúng ta nên thay đổi chính sách.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:thanks-to',
    title: 'Thanks to ..., ...',
    template: 'Thanks to [A], [B].',
    description: 'Nguyên nhân tích cực — nhờ có…',
    category: 'Liên từ / Lý do',
    exampleA: 'her support',
    exampleB: 'I finished the project on time',
    exampleNoteVi: 'Nhờ sự hỗ trợ của cô ấy, tôi hoàn thành dự án đúng hạn.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:owing-to',
    title: 'Owing to ..., ...',
    template: 'Owing to [A], [B].',
    description: 'Nguyên nhân trang trọng (IELTS Writing).',
    category: 'Liên từ / Lý do',
    exampleA: 'rising living costs',
    exampleB: 'many families have cut their spending',
    exampleNoteVi: 'Do chi phí sinh hoạt tăng, nhiều gia đình đã cắt giảm chi tiêu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:the-reason-why',
    title: 'The reason why ... is that ...',
    template: 'The reason why [A] is that [B].',
    description: 'Giải thích lý do rõ ràng, học thuật.',
    category: 'Liên từ / Lý do',
    exampleA: 'many students fail',
    exampleB: 'they do not revise regularly',
    exampleNoteVi: 'Lý do nhiều học sinh trượt là vì họ không ôn đều đặn.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:in-order-to-reason',
    title: 'This is because ...',
    template: '[A]. This is because [B].',
    description: 'Giải thích nguyên nhân sau một nhận định.',
    category: 'Liên từ / Lý do',
    exampleA: 'Public transport should be improved',
    exampleB: 'it reduces traffic congestion',
    exampleNoteVi: 'Giao thông công cộng cần được cải thiện. Điều này là vì nó giảm ùn tắc.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:the-more',
    title: 'The more ..., the more ...',
    template: 'The more [A], the more [B].',
    description: 'Hai vế tỷ lệ thuận — càng… càng…',
    category: 'So sánh',
    exampleA: 'you practise',
    exampleB: 'you improve',
    exampleNoteVi: 'Bạn càng luyện tập nhiều, bạn càng tiến bộ.',
    starred: true,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:the-less',
    title: 'The less ..., the better ...',
    template: 'The less [A], the better [B].',
    description: 'Tỷ lệ nghịch — càng ít… càng tốt…',
    category: 'So sánh',
    exampleA: 'sugar you eat',
    exampleB: 'it is for your health',
    exampleNoteVi: 'Bạn càng ít ăn đường, càng tốt cho sức khỏe.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:as-as',
    title: 'as ... as ...',
    template: '[A] is as [B] as mine.',
    description: 'So sánh bằng — ngang bằng…',
    category: 'So sánh',
    exampleA: 'Your idea',
    exampleB: 'good',
    exampleNoteVi: 'Ý tưởng của bạn tốt ngang với của tôi.',
    starred: false,
    cefr: 'A2',
  },
  {
    id: 'catalog:ss:not-as-as',
    title: 'not as ... as ...',
    template: '[A] is not as [B] as it used to be.',
    description: 'So sánh không bằng — không… bằng…',
    category: 'So sánh',
    exampleA: 'The city',
    exampleB: 'quiet',
    exampleNoteVi: 'Thành phố không còn yên tĩnh như trước.',
    starred: false,
    cefr: 'A2',
  },
  {
    id: 'catalog:ss:more-than',
    title: 'more ... than ...',
    template: '[A] is more [B] than before.',
    description: 'So sánh hơn với tính từ dài.',
    category: 'So sánh',
    exampleA: 'Online learning',
    exampleB: 'popular',
    exampleNoteVi: 'Học trực tuyến phổ biến hơn trước đây.',
    starred: false,
    cefr: 'A2',
  },
  {
    id: 'catalog:ss:less-than',
    title: 'less ... than ...',
    template: '[A] is less [B] than expected.',
    description: 'So sánh kém hơn.',
    category: 'So sánh',
    exampleA: 'The problem',
    exampleB: 'serious',
    exampleNoteVi: 'Vấn đề ít nghiêm trọng hơn dự kiến.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:one-of-the-most',
    title: 'one of the most ...',
    template: '[A] is one of the most [B] in the world.',
    description: 'So sánh nhất — một trong những… nhất.',
    category: 'So sánh',
    exampleA: 'Climate change',
    exampleB: 'urgent issues',
    exampleNoteVi: 'Biến đổi khí hậu là một trong những vấn đề cấp bách nhất thế giới.',
    starred: true,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:far-more',
    title: 'far more ... than ...',
    template: '[A] is far more [B] than people think.',
    description: 'Nhấn mạnh mức độ so sánh — hơn nhiều.',
    category: 'So sánh',
    exampleA: 'The solution',
    exampleB: 'complex',
    exampleNoteVi: 'Giải pháp phức tạp hơn nhiều so với mọi người nghĩ.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:compared-with',
    title: 'Compared with ..., ...',
    template: 'Compared with [A], [B].',
    description: 'So sánh trang trọng trong Writing.',
    category: 'So sánh',
    exampleA: 'previous years',
    exampleB: 'sales have increased significantly',
    exampleNoteVi: 'So với các năm trước, doanh số đã tăng đáng kể.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:in-contrast-to',
    title: 'In contrast to ..., ...',
    template: 'In contrast to [A], [B].',
    description: 'Đối chiếu hai đối tượng.',
    category: 'So sánh',
    exampleA: 'rural areas',
    exampleB: 'cities offer more job opportunities',
    exampleNoteVi: 'Trái với nông thôn, thành phố mang lại nhiều cơ hội việc làm hơn.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:so-that',
    title: 'S + V ... so that S + can + V',
    template: '[A] so that I can [B].',
    description: 'Nêu mục đích của hành động — để có thể làm gì.',
    category: 'Mục đích',
    exampleA: 'I wake up early',
    exampleB: 'finish my homework',
    exampleNoteVi: 'Tôi dậy sớm để có thể hoàn thành bài tập.',
    starred: true,
    cefr: 'A2',
  },
  {
    id: 'catalog:ss:in-order-to',
    title: 'in order to ...',
    template: '[A] in order to [B].',
    description: 'Mục đích trang trọng — nhằm / để…',
    category: 'Mục đích',
    exampleA: 'Governments invest in education',
    exampleB: 'improve social mobility',
    exampleNoteVi: 'Chính phủ đầu tư vào giáo dục nhằm cải thiện sự lưu động xã hội.',
    starred: true,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:so-as-to',
    title: 'so as to ...',
    template: '[A] so as to [B].',
    description: 'Mục đích formal, tương tự in order to.',
    category: 'Mục đích',
    exampleA: 'She spoke slowly',
    exampleB: 'make herself understood',
    exampleNoteVi: 'Cô ấy nói chậm để người khác hiểu mình.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:for-the-purpose-of',
    title: 'for the purpose of ...',
    template: '[A] for the purpose of [B].',
    description: 'Mục đích học thuật — với mục đích…',
    category: 'Mục đích',
    exampleA: 'The study was conducted',
    exampleB: 'identifying key risk factors',
    exampleNoteVi: 'Nghiên cứu được thực hiện nhằm xác định các yếu tố rủi ro chính.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:to-infinitive-purpose',
    title: 'to + V (purpose)',
    template: '[A] to [B].',
    description: 'Mục đích ngắn gọn với to-infinitive.',
    category: 'Mục đích',
    exampleA: 'I went to the library',
    exampleB: 'borrow some books',
    exampleNoteVi: 'Tôi đến thư viện để mượn vài cuốn sách.',
    starred: false,
    cefr: 'A2',
  },
  {
    id: 'catalog:ss:with-a-view-to',
    title: 'with a view to ...',
    template: '[A] with a view to [B].',
    description: 'Mục đích rất formal — nhằm mục tiêu…',
    category: 'Mục đích',
    exampleA: 'The company expanded overseas',
    exampleB: 'increasing its market share',
    exampleNoteVi: 'Công ty mở rộng ra nước ngoài nhằm tăng thị phần.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:if-will',
    title: 'If ..., ... will ...',
    template: 'If [A], [B].',
    description: 'Câu điều kiện loại 1 — nếu… thì sẽ…',
    category: 'Điều kiện',
    exampleA: 'you study hard',
    exampleB: 'you will succeed',
    exampleNoteVi: 'Nếu bạn học chăm, bạn sẽ đạt kết quả tốt.',
    starred: true,
    cefr: 'A2',
  },
  {
    id: 'catalog:ss:if-would',
    title: 'If ..., ... would ...',
    template: 'If [A], [B].',
    description: 'Điều kiện loại 2 — giả định hiện tại.',
    category: 'Điều kiện',
    exampleA: 'I had more time',
    exampleB: 'I would learn another language',
    exampleNoteVi: 'Nếu tôi có nhiều thời gian hơn, tôi sẽ học thêm một ngoại ngữ.',
    starred: true,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:if-had-would-have',
    title: 'If ... had ..., ... would have ...',
    template: 'If [A], [B].',
    description: 'Điều kiện loại 3 — giả định quá khứ.',
    category: 'Điều kiện',
    exampleA: 'she had left earlier',
    exampleB: 'she would have caught the train',
    exampleNoteVi: 'Nếu cô ấy đi sớm hơn, cô ấy đã bắt kịp tàu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:unless',
    title: 'Unless ..., ...',
    template: 'Unless [A], [B].',
    description: 'Trừ khi… — if not.',
    category: 'Điều kiện',
    exampleA: 'we act now',
    exampleB: 'the problem will get worse',
    exampleNoteVi: 'Trừ khi chúng ta hành động ngay, vấn đề sẽ trở nên tồi tệ hơn.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:provided-that',
    title: 'Provided that ..., ...',
    template: 'Provided that [A], [B].',
    description: 'Với điều kiện là… (formal).',
    category: 'Điều kiện',
    exampleA: 'the weather is fine',
    exampleB: 'the event will take place outdoors',
    exampleNoteVi: 'Với điều kiện thời tiết đẹp, sự kiện sẽ diễn ra ngoài trời.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:as-long-as',
    title: 'As long as ..., ...',
    template: 'As long as [A], [B].',
    description: 'Miễn là… / chỉ cần…',
    category: 'Điều kiện',
    exampleA: 'you keep practising',
    exampleB: 'you will improve',
    exampleNoteVi: 'Miễn là bạn tiếp tục luyện tập, bạn sẽ tiến bộ.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:even-if',
    title: 'Even if ..., ...',
    template: 'Even if [A], [B].',
    description: 'Ngay cả khi… — điều kiện nhượng bộ.',
    category: 'Điều kiện',
    exampleA: 'it rains',
    exampleB: 'we will still go hiking',
    exampleNoteVi: 'Ngay cả khi trời mưa, chúng tôi vẫn đi bộ đường dài.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:whether-or-not',
    title: 'Whether or not ..., ...',
    template: 'Whether or not [A], [B].',
    description: 'Dù có… hay không…',
    category: 'Điều kiện',
    exampleA: 'you agree',
    exampleB: 'the decision has already been made',
    exampleNoteVi: 'Dù bạn có đồng ý hay không, quyết định đã được đưa ra.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:in-case',
    title: 'in case ...',
    template: '[A] in case [B].',
    description: 'Phòng khi… — chuẩn bị trước tình huống.',
    category: 'Điều kiện',
    exampleA: 'Take an umbrella',
    exampleB: 'it rains',
    exampleNoteVi: 'Mang theo ô phòng khi trời mưa.',
    starred: false,
    cefr: 'A2',
  },
  {
    id: 'catalog:ss:only-if',
    title: 'only if ...',
    template: '[A] only if [B].',
    description: 'Chỉ khi… — điều kiện bắt buộc.',
    category: 'Điều kiện',
    exampleA: 'You can join the course',
    exampleB: 'you pass the entry test',
    exampleNoteVi: 'Bạn chỉ có thể tham gia khóa học nếu đậu bài kiểm tra đầu vào.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:although',
    title: 'Although ..., ...',
    template: 'Although [A], [B].',
    description: 'Mệnh đề tương phản — mặc dù… nhưng…',
    category: 'Tương phản',
    exampleA: 'it was raining',
    exampleB: 'we still went out',
    exampleNoteVi: 'Mặc dù trời mưa, chúng tôi vẫn đi ra ngoài.',
    starred: true,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:even-though',
    title: 'Even though ..., ...',
    template: 'Even though [A], [B].',
    description: 'Tương phản mạnh hơn although.',
    category: 'Tương phản',
    exampleA: 'he was exhausted',
    exampleB: 'he finished the report',
    exampleNoteVi: 'Dù kiệt sức, anh ấy vẫn hoàn thành báo cáo.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:despite',
    title: 'Despite ..., ...',
    template: 'Despite [A], [B].',
    description: 'Tương phản với danh từ / V-ing.',
    category: 'Tương phản',
    exampleA: 'the difficulties',
    exampleB: 'the team completed the project',
    exampleNoteVi: 'Bất chấp khó khăn, nhóm đã hoàn thành dự án.',
    starred: true,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:in-spite-of',
    title: 'In spite of ..., ...',
    template: 'In spite of [A], [B].',
    description: 'Tương đương despite — formal hơn một chút.',
    category: 'Tương phản',
    exampleA: 'limited resources',
    exampleB: 'they achieved remarkable results',
    exampleNoteVi: 'Mặc dù nguồn lực hạn chế, họ đạt kết quả ấn tượng.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:however',
    title: 'However, ...',
    template: '[A]. However, [B].',
    description: 'Chuyển ý đối lập giữa hai câu.',
    category: 'Tương phản',
    exampleA: 'The plan sounds attractive',
    exampleB: 'it may be too expensive',
    exampleNoteVi: 'Kế hoạch nghe hấp dẫn. Tuy nhiên, nó có thể quá đắt.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:on-the-other-hand',
    title: 'On the other hand, ...',
    template: 'On the one hand, [A]. On the other hand, [B].',
    description: 'Cân nhắc hai mặt của vấn đề (Writing).',
    category: 'Tương phản',
    exampleA: 'technology creates jobs',
    exampleB: 'it can also replace workers',
    exampleNoteVi: 'Một mặt, công nghệ tạo việc làm. Mặt khác, nó cũng có thể thay thế lao động.',
    starred: true,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:whereas',
    title: 'Whereas ..., ...',
    template: 'Whereas [A], [B].',
    description: 'Đối chiếu hai sự thật — trong khi…',
    category: 'Tương phản',
    exampleA: 'some people prefer city life',
    exampleB: 'others enjoy the countryside',
    exampleNoteVi: 'Trong khi một số người thích sống ở thành phố, những người khác thích nông thôn.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:while-contrast',
    title: 'While ..., ...',
    template: 'While [A], [B].',
    description: 'Tương phản hoặc đồng thời — trong khi…',
    category: 'Tương phản',
    exampleA: 'public transport is cheap',
    exampleB: 'it is often overcrowded',
    exampleNoteVi: 'Trong khi giao thông công cộng rẻ, nó thường quá đông.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:nevertheless',
    title: 'Nevertheless, ...',
    template: '[A]. Nevertheless, [B].',
    description: 'Nhượng bộ formal — dù vậy…',
    category: 'Tương phản',
    exampleA: 'The task was difficult',
    exampleB: 'they completed it successfully',
    exampleNoteVi: 'Nhiệm vụ khó. Dù vậy, họ vẫn hoàn thành thành công.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:by-contrast',
    title: 'By contrast, ...',
    template: '[A]. By contrast, [B].',
    description: 'Đối chiếu rõ nét giữa hai ý.',
    category: 'Tương phản',
    exampleA: 'Urban areas are densely populated',
    exampleB: 'rural regions remain sparsely inhabited',
    exampleNoteVi: 'Khu đô thị đông đúc. Ngược lại, vùng nông thôn vẫn thưa dân.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:it-is-argued-that',
    title: 'It is often argued that ...',
    template: 'It is often argued that [A] because [B].',
    description: 'Mở bài Writing — người ta thường lập luận rằng…',
    category: 'Khác',
    exampleA: 'education should be free',
    exampleB: 'it is a basic right',
    exampleNoteVi: 'Người ta thường lập luận rằng giáo dục nên miễn phí vì đó là quyền cơ bản.',
    starred: true,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:in-my-opinion',
    title: 'In my opinion, ...',
    template: 'In my opinion, [A] should [B].',
    description: 'Nêu quan điểm cá nhân rõ ràng.',
    category: 'Khác',
    exampleA: 'governments',
    exampleB: 'invest more in public transport',
    exampleNoteVi: 'Theo tôi, chính phủ nên đầu tư nhiều hơn vào giao thông công cộng.',
    starred: false,
    cefr: 'A2',
  },
  {
    id: 'catalog:ss:it-is-widely-believed',
    title: 'It is widely believed that ...',
    template: 'It is widely believed that [A], especially when [B].',
    description: 'Nêu quan điểm phổ biến — mang tính khách quan.',
    category: 'Khác',
    exampleA: 'technology improves our quality of life',
    exampleB: 'it is used responsibly',
    exampleNoteVi: 'Nhiều người tin rằng công nghệ cải thiện chất lượng cuộc sống, đặc biệt khi được dùng có trách nhiệm.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:there-is-no-doubt',
    title: 'There is no doubt that ...',
    template: 'There is no doubt that [A], so [B].',
    description: 'Nhấn mạnh sự chắc chắn và hệ quả.',
    category: 'Khác',
    exampleA: 'climate change requires urgent action',
    exampleB: 'governments must invest in green energy',
    exampleNoteVi: 'Không còn nghi ngờ gì rằng biến đổi khí hậu cần hành động khẩn cấp, vì vậy chính phủ phải đầu tư năng lượng xanh.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:what-matters-is',
    title: 'What matters is ...',
    template: 'What matters is [A], not [B].',
    description: 'Nhấn mạnh điều quan trọng thật sự.',
    category: 'Khác',
    exampleA: 'consistent effort',
    exampleB: 'natural talent alone',
    exampleNoteVi: 'Điều quan trọng là nỗ lực đều đặn, không chỉ tài năng bẩm sinh.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:it-is-essential-that',
    title: 'It is essential that ...',
    template: 'It is essential that [A] so that [B].',
    description: 'Nhấn mạnh sự cần thiết và mục đích.',
    category: 'Khác',
    exampleA: 'students develop critical thinking skills',
    exampleB: 'they can solve complex problems',
    exampleNoteVi: 'Điều thiết yếu là học sinh phát triển tư duy phản biện để có thể giải quyết vấn đề phức tạp.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:having-said-that',
    title: 'Having said that, ...',
    template: '[A]. Having said that, [B].',
    description: 'Nhượng bộ tinh tế sau khi nêu ý trước.',
    category: 'Khác',
    exampleA: 'Online learning is convenient',
    exampleB: 'it cannot fully replace classroom interaction',
    exampleNoteVi: 'Học online tiện lợi. Dù vậy, nó không thể thay thế hoàn toàn tương tác lớp học.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:to-what-extent',
    title: 'To what extent ...',
    template: 'To what extent [A] depends on [B].',
    description: 'Câu trả lời dạng “mức độ nào” (IELTS).',
    category: 'Khác',
    exampleA: 'technology benefits society',
    exampleB: 'how it is regulated',
    exampleNoteVi: 'Công nghệ mang lại lợi ích cho xã hội đến mức nào phụ thuộc vào cách nó được quản lý.',
    starred: true,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:rather-than',
    title: 'rather than ...',
    template: '[A] rather than [B].',
    description: 'Lựa chọn ưu tiên — thay vì…',
    category: 'Khác',
    exampleA: 'We should prevent disease',
    exampleB: 'only treat it later',
    exampleNoteVi: 'Chúng ta nên phòng bệnh thay vì chỉ chữa khi đã mắc.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:instead-of',
    title: 'instead of ...',
    template: '[A] instead of [B].',
    description: 'Thay vì… — thay thế hành động/danh từ.',
    category: 'Khác',
    exampleA: 'Take the train',
    exampleB: 'driving in heavy traffic',
    exampleNoteVi: 'Hãy đi tàu thay vì lái xe trong tắc đường.',
    starred: false,
    cefr: 'A2',
  },
  {
    id: 'catalog:ss:it-is-high-time',
    title: 'It is high time ...',
    template: 'It is high time [A] before [B].',
    description: 'Đã đến lúc phải… (past subjunctive).',
    category: 'Khác',
    exampleA: 'governments took climate change seriously',
    exampleB: 'it is too late',
    exampleNoteVi: 'Đã đến lúc chính phủ phải nghiêm túc với biến đổi khí hậu trước khi quá muộn.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:no-sooner',
    title: 'No sooner ... than ...',
    template: 'No sooner had [A] than [B].',
    description: 'Vừa… thì… (đảo ngữ nâng cao).',
    category: 'Khác',
    exampleA: 'I arrived',
    exampleB: 'it started to rain',
    exampleNoteVi: 'Tôi vừa đến thì trời bắt đầu mưa.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:hardly-when',
    title: 'Hardly ... when ...',
    template: 'Hardly had [A] when [B].',
    description: 'Vừa mới… thì… (đảo ngữ).',
    category: 'Khác',
    exampleA: 'the meeting begun',
    exampleB: 'the fire alarm went off',
    exampleNoteVi: 'Cuộc họp vừa bắt đầu thì chuông báo cháy reo.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:the-fact-that',
    title: 'The fact that ...',
    template: 'The fact that [A] suggests that [B].',
    description: 'Dùng mệnh đề danh ngữ học thuật.',
    category: 'Khác',
    exampleA: 'more people work from home',
    exampleB: 'office culture is changing',
    exampleNoteVi: 'Việc nhiều người làm việc tại nhà cho thấy văn hóa văn phòng đang thay đổi.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:it-seems-that',
    title: 'It seems that ...',
    template: 'It seems that [A], especially among [B].',
    description: 'Đưa nhận định dè dặt — có vẻ như…',
    category: 'Khác',
    exampleA: 'remote work will remain common',
    exampleB: 'young professionals',
    exampleNoteVi: 'Có vẻ như làm việc từ xa sẽ vẫn phổ biến, đặc biệt trong giới chuyên gia trẻ.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:a-growing-number',
    title: 'A growing number of ...',
    template: 'A growing number of [A] are [B].',
    description: 'Mô tả xu hướng tăng — ngày càng nhiều…',
    category: 'Khác',
    exampleA: 'people',
    exampleB: 'choosing flexible working hours',
    exampleNoteVi: 'Ngày càng nhiều người chọn giờ làm linh hoạt.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:play-a-role',
    title: 'play a vital role in ...',
    template: '[A] play a vital role in [B].',
    description: 'Collocation Writing — đóng vai trò then chốt.',
    category: 'Khác',
    exampleA: 'Teachers',
    exampleB: 'shaping students�" futures',
    exampleNoteVi: 'Giáo viên đóng vai trò then chốt trong việc định hình tương lai học sinh.',
    starred: true,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:lead-to',
    title: 'lead to ...',
    template: '[A] can lead to [B].',
    description: 'Nêu hệ quả — dẫn đến…',
    category: 'Khác',
    exampleA: 'Lack of sleep',
    exampleB: 'poor concentration',
    exampleNoteVi: 'Thiếu ngủ có thể dẫn đến giảm tập trung.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:result-in',
    title: 'result in ...',
    template: '[A] may result in [B].',
    description: 'Hệ quả formal — dẫn tới kết quả…',
    category: 'Khác',
    exampleA: 'Poor planning',
    exampleB: 'project delays',
    exampleNoteVi: 'Lập kế hoạch kém có thể dẫn đến chậm tiến độ dự án.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:be-likely-to',
    title: 'be likely to ...',
    template: '[A] are likely to [B].',
    description: 'Dự đoán khả năng — có khả năng…',
    category: 'Khác',
    exampleA: 'Young people',
    exampleB: 'change careers more often',
    exampleNoteVi: 'Người trẻ có khả năng thay đổi nghề nghiệp thường xuyên hơn.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:tend-to',
    title: 'tend to ...',
    template: '[A] tend to [B].',
    description: 'Xu hướng chung — thường…',
    category: 'Khác',
    exampleA: 'City residents',
    exampleB: 'rely more on public transport',
    exampleNoteVi: 'Cư dân thành phố thường phụ thuộc nhiều hơn vào giao thông công cộng.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:it-is-worth',
    title: 'It is worth + V-ing',
    template: 'It is worth [A] if [B].',
    description: 'Đáng để làm gì — worth + V-ing.',
    category: 'Khác',
    exampleA: 'learning a second language',
    exampleB: 'you want better career options',
    exampleNoteVi: 'Đáng để học ngoại ngữ thứ hai nếu bạn muốn nhiều lựa chọn nghề nghiệp hơn.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:far-from',
    title: 'far from ...',
    template: '[A] is far from [B].',
    description: 'Nhấn mạnh khoảng cách với kỳ vọng — còn xa mới…',
    category: 'Khác',
    exampleA: 'The solution',
    exampleB: 'perfect',
    exampleNoteVi: 'Giải pháp còn xa mới hoàn hảo.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:in-terms-of',
    title: 'in terms of ...',
    template: 'In terms of [A], [B].',
    description: 'Xét về phương diện… (Writing).',
    category: 'Khác',
    exampleA: 'cost',
    exampleB: 'public transport is more efficient',
    exampleNoteVi: 'Xét về chi phí, giao thông công cộng hiệu quả hơn.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:when-it-comes-to',
    title: 'When it comes to ...',
    template: 'When it comes to [A], [B].',
    description: 'Khi nói đến… — chuyển chủ đề tự nhiên.',
    category: 'Khác',
    exampleA: 'mental health',
    exampleB: 'prevention is better than cure',
    exampleNoteVi: 'Khi nói đến sức khỏe tinh thần, phòng bệnh hơn chữa bệnh.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:given-that',
    title: 'Given that ..., ...',
    template: 'Given that [A], [B].',
    description: 'Nối ý nguyên nhân – kết quả trong câu/đoạn văn.',
    category: 'Liên từ / Lý do',
    exampleA: 'resources are limited',
    exampleB: 'priorities must be set carefully',
    exampleNoteVi: 'Dùng cấu trúc này để giải thích lý do hoặc hệ quả một cách mạch lạc.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:in-view-of',
    title: 'In view of ..., ...',
    template: 'In view of [A], [B].',
    description: 'Nối ý nguyên nhân – kết quả trong câu/đoạn văn.',
    category: 'Liên từ / Lý do',
    exampleA: 'recent evidence',
    exampleB: 'the policy should be revised',
    exampleNoteVi: 'Dùng cấu trúc này để giải thích lý do hoặc hệ quả một cách mạch lạc.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:on-account-of',
    title: 'On account of ..., ...',
    template: 'On account of [A], [B].',
    description: 'Nối ý nguyên nhân – kết quả trong câu/đoạn văn.',
    category: 'Liên từ / Lý do',
    exampleA: 'severe weather',
    exampleB: 'several flights were cancelled',
    exampleNoteVi: 'Dùng cấu trúc này để giải thích lý do hoặc hệ quả một cách mạch lạc.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:for-this-reason',
    title: 'For this reason, ...',
    template: '[A]. For this reason, [B].',
    description: 'Nối ý nguyên nhân – kết quả trong câu/đoạn văn.',
    category: 'Liên từ / Lý do',
    exampleA: 'Air pollution harms public health',
    exampleB: 'stricter emission rules are needed',
    exampleNoteVi: 'Dùng cấu trúc này để giải thích lý do hoặc hệ quả một cách mạch lạc.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:hence',
    title: 'Hence, ...',
    template: '[A]. Hence, [B].',
    description: 'Nối ý nguyên nhân – kết quả trong câu/đoạn văn.',
    category: 'Liên từ / Lý do',
    exampleA: 'Demand has risen sharply',
    exampleB: 'prices are likely to increase',
    exampleNoteVi: 'Dùng cấu trúc này để giải thích lý do hoặc hệ quả một cách mạch lạc.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:that-is-why',
    title: 'That is why ...',
    template: '[A]. That is why [B].',
    description: 'Nối ý nguyên nhân – kết quả trong câu/đoạn văn.',
    category: 'Liên từ / Lý do',
    exampleA: 'She practised every day',
    exampleB: 'she improved so quickly',
    exampleNoteVi: 'Dùng cấu trúc này để giải thích lý do hoặc hệ quả một cách mạch lạc.',
    starred: false,
    cefr: 'A2',
  },
  {
    id: 'catalog:ss:seeing-that',
    title: 'Seeing that ..., ...',
    template: 'Seeing that [A], [B].',
    description: 'Nối ý nguyên nhân – kết quả trong câu/đoạn văn.',
    category: 'Liên từ / Lý do',
    exampleA: 'the deadline is tomorrow',
    exampleB: 'we should finish tonight',
    exampleNoteVi: 'Dùng cấu trúc này để giải thích lý do hoặc hệ quả một cách mạch lạc.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:now-that',
    title: 'Now that ..., ...',
    template: 'Now that [A], [B].',
    description: 'Nối ý nguyên nhân – kết quả trong câu/đoạn văn.',
    category: 'Liên từ / Lý do',
    exampleA: 'the exam is over',
    exampleB: 'I can finally relax',
    exampleNoteVi: 'Dùng cấu trúc này để giải thích lý do hoặc hệ quả một cách mạch lạc.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:in-light-of',
    title: 'In light of ..., ...',
    template: 'In light of [A], [B].',
    description: 'Nối ý nguyên nhân – kết quả trong câu/đoạn văn.',
    category: 'Liên từ / Lý do',
    exampleA: 'new research findings',
    exampleB: 'the guidelines were updated',
    exampleNoteVi: 'Dùng cấu trúc này để giải thích lý do hoặc hệ quả một cách mạch lạc.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:by-virtue-of',
    title: 'By virtue of ..., ...',
    template: 'By virtue of [A], [B].',
    description: 'Nối ý nguyên nhân – kết quả trong câu/đoạn văn.',
    category: 'Liên từ / Lý do',
    exampleA: 'her experience',
    exampleB: 'she was promoted quickly',
    exampleNoteVi: 'Dùng cấu trúc này để giải thích lý do hoặc hệ quả một cách mạch lạc.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:twice-as',
    title: 'twice as ... as ...',
    template: '[A] is twice as expensive as [B].',
    description: 'So sánh mức độ, số lượng hoặc đặc điểm giữa hai ý.',
    category: 'So sánh',
    exampleA: 'This phone',
    exampleB: 'the older model',
    exampleNoteVi: 'Điền A và B sao cho câu so sánh tự nhiên, đúng ngữ pháp.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:three-times-as',
    title: 'three times as ... as ...',
    template: '[A] is three times as large as [B].',
    description: 'So sánh mức độ, số lượng hoặc đặc điểm giữa hai ý.',
    category: 'So sánh',
    exampleA: 'Online sales',
    exampleB: 'last year',
    exampleNoteVi: 'Điền A và B sao cho câu so sánh tự nhiên, đúng ngữ pháp.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:no-more-than',
    title: 'no more than ...',
    template: '[A] is no more than [B].',
    description: 'So sánh mức độ, số lượng hoặc đặc điểm giữa hai ý.',
    category: 'So sánh',
    exampleA: 'This is',
    exampleB: 'a temporary solution',
    exampleNoteVi: 'Điền A và B sao cho câu so sánh tự nhiên, đúng ngữ pháp.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:no-less-than',
    title: 'no less than ...',
    template: 'No less than [A] is needed to [B].',
    description: 'So sánh mức độ, số lượng hoặc đặc điểm giữa hai ý.',
    category: 'So sánh',
    exampleA: 'a decade of research',
    exampleB: 'solve the problem',
    exampleNoteVi: 'Điền A và B sao cho câu so sánh tự nhiên, đúng ngữ pháp.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:similarly',
    title: 'Similarly, ...',
    template: '[A]. Similarly, [B].',
    description: 'So sánh mức độ, số lượng hoặc đặc điểm giữa hai ý.',
    category: 'So sánh',
    exampleA: 'City life can be stressful',
    exampleB: 'rural isolation can affect mental health',
    exampleNoteVi: 'Điền A và B sao cho câu so sánh tự nhiên, đúng ngữ pháp.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:likewise',
    title: 'Likewise, ...',
    template: '[A]. Likewise, [B].',
    description: 'So sánh mức độ, số lượng hoặc đặc điểm giữa hai ý.',
    category: 'So sánh',
    exampleA: 'Exercise improves physical health',
    exampleB: 'sleep improves cognitive performance',
    exampleNoteVi: 'Điền A và B sao cho câu so sánh tự nhiên, đúng ngữ pháp.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:just-as',
    title: 'Just as ..., so ...',
    template: 'Just as [A], so [B].',
    description: 'So sánh mức độ, số lượng hoặc đặc điểm giữa hai ý.',
    category: 'So sánh',
    exampleA: 'plants need sunlight',
    exampleB: 'children need encouragement',
    exampleNoteVi: 'Điền A và B sao cho câu so sánh tự nhiên, đúng ngữ pháp.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:prefer-to',
    title: 'prefer ... to ...',
    template: 'Many people prefer [A] to [B].',
    description: 'So sánh mức độ, số lượng hoặc đặc điểm giữa hai ý.',
    category: 'So sánh',
    exampleA: 'working from home',
    exampleB: 'commuting every day',
    exampleNoteVi: 'Điền A và B sao cho câu so sánh tự nhiên, đúng ngữ pháp.',
    starred: false,
    cefr: 'A2',
  },
  {
    id: 'catalog:ss:would-rather',
    title: 'would rather ... than ...',
    template: 'I would rather [A] than [B].',
    description: 'So sánh mức độ, số lượng hoặc đặc điểm giữa hai ý.',
    category: 'So sánh',
    exampleA: 'walk',
    exampleB: 'wait in traffic',
    exampleNoteVi: 'Điền A và B sao cho câu so sánh tự nhiên, đúng ngữ pháp.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:superior-to',
    title: 'be superior to ...',
    template: '[A] is superior to [B] in many ways.',
    description: 'So sánh mức độ, số lượng hoặc đặc điểm giữa hai ý.',
    category: 'So sánh',
    exampleA: 'Prevention',
    exampleB: 'treatment',
    exampleNoteVi: 'Điền A và B sao cho câu so sánh tự nhiên, đúng ngữ pháp.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:with-the-aim-of',
    title: 'with the aim of ...',
    template: '[A] with the aim of [B].',
    description: 'Nêu mục đích của hành động.',
    category: 'Mục đích',
    exampleA: 'The campaign was launched',
    exampleB: 'raising public awareness',
    exampleNoteVi: 'A là hành động chính; B là mục đích cần đạt.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:with-the-intention-of',
    title: 'with the intention of ...',
    template: '[A] with the intention of [B].',
    description: 'Nêu mục đích của hành động.',
    category: 'Mục đích',
    exampleA: 'She moved abroad',
    exampleB: 'studying architecture',
    exampleNoteVi: 'A là hành động chính; B là mục đích cần đạt.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:so-that-not',
    title: 'so that ... not / so as not to',
    template: '[A] so as not to [B].',
    description: 'Nêu mục đích của hành động.',
    category: 'Mục đích',
    exampleA: 'He left quietly',
    exampleB: 'wake the baby',
    exampleNoteVi: 'A là hành động chính; B là mục đích cần đạt.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:for-fear-of',
    title: 'for fear of ...',
    template: '[A] for fear of [B].',
    description: 'Nêu mục đích của hành động.',
    category: 'Mục đích',
    exampleA: 'She avoided the topic',
    exampleB: 'causing an argument',
    exampleNoteVi: 'A là hành động chính; B là mục đích cần đạt.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:in-an-attempt-to',
    title: 'in an attempt to ...',
    template: '[A] in an attempt to [B].',
    description: 'Nêu mục đích của hành động.',
    category: 'Mục đích',
    exampleA: 'The company cut prices',
    exampleB: 'attract more customers',
    exampleNoteVi: 'A là hành động chính; B là mục đích cần đạt.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:to-the-end-that',
    title: 'to the end that ...',
    template: '[A] to the end that [B].',
    description: 'Nêu mục đích của hành động.',
    category: 'Mục đích',
    exampleA: 'Laws were tightened',
    exampleB: 'public safety is protected',
    exampleNoteVi: 'A là hành động chính; B là mục đích cần đạt.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:suppose-that',
    title: 'Suppose that ..., ...',
    template: 'Suppose that [A], [B].',
    description: 'Nêu điều kiện và kết quả có thể xảy ra.',
    category: 'Điều kiện',
    exampleA: 'fuel prices double',
    exampleB: 'many people will use public transport',
    exampleNoteVi: 'A là điều kiện; B là kết quả.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:supposing',
    title: 'Supposing ..., ...',
    template: 'Supposing [A], what would [B]?',
    description: 'Nêu điều kiện và kết quả có thể xảy ra.',
    category: 'Điều kiện',
    exampleA: 'you lost your job',
    exampleB: 'you do next',
    exampleNoteVi: 'A là điều kiện; B là kết quả.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:on-condition-that',
    title: 'on condition that ...',
    template: '[A] on condition that [B].',
    description: 'Nêu điều kiện và kết quả có thể xảy ra.',
    category: 'Điều kiện',
    exampleA: 'You may borrow the car',
    exampleB: 'you drive carefully',
    exampleNoteVi: 'A là điều kiện; B là kết quả.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:in-the-event-that',
    title: 'In the event that ..., ...',
    template: 'In the event that [A], [B].',
    description: 'Nêu điều kiện và kết quả có thể xảy ra.',
    category: 'Điều kiện',
    exampleA: 'the system fails',
    exampleB: 'a backup plan will be activated',
    exampleNoteVi: 'A là điều kiện; B là kết quả.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:otherwise',
    title: '..., otherwise ...',
    template: '[A]; otherwise, [B].',
    description: 'Nêu điều kiện và kết quả có thể xảy ra.',
    category: 'Điều kiện',
    exampleA: 'Hurry up',
    exampleB: 'we will miss the train',
    exampleNoteVi: 'A là điều kiện; B là kết quả.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:or-else',
    title: '..., or else ...',
    template: '[A], or else [B].',
    description: 'Nêu điều kiện và kết quả có thể xảy ra.',
    category: 'Điều kiện',
    exampleA: 'Follow the instructions',
    exampleB: 'the experiment will fail',
    exampleNoteVi: 'A là điều kiện; B là kết quả.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:should-you',
    title: 'Should you ..., ...',
    template: 'Should you [A], [B].',
    description: 'Nêu điều kiện và kết quả có thể xảy ra.',
    category: 'Điều kiện',
    exampleA: 'need further information',
    exampleB: 'please contact our office',
    exampleNoteVi: 'A là điều kiện; B là kết quả.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:were-i-to',
    title: 'Were I to ..., ...',
    template: 'Were I to [A], [B].',
    description: 'Nêu điều kiện và kết quả có thể xảy ra.',
    category: 'Điều kiện',
    exampleA: 'refuse this offer',
    exampleB: 'I would regret it later',
    exampleNoteVi: 'A là điều kiện; B là kết quả.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:had-it-not-been',
    title: 'Had it not been for ..., ...',
    template: 'Had it not been for [A], [B].',
    description: 'Nêu điều kiện và kết quả có thể xảy ra.',
    category: 'Điều kiện',
    exampleA: 'your help',
    exampleB: 'I would have failed',
    exampleNoteVi: 'A là điều kiện; B là kết quả.',
    starred: true,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:but-for',
    title: 'But for ..., ...',
    template: 'But for [A], [B].',
    description: 'Nêu điều kiện và kết quả có thể xảy ra.',
    category: 'Điều kiện',
    exampleA: 'the rain',
    exampleB: 'we would have finished earlier',
    exampleNoteVi: 'A là điều kiện; B là kết quả.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:albeit',
    title: 'albeit ...',
    template: '[A], albeit [B].',
    description: 'Nối hai ý đối lập hoặc nhượng bộ.',
    category: 'Tương phản',
    exampleA: 'The plan was accepted',
    exampleB: 'with some reservations',
    exampleNoteVi: 'A và B tạo sự tương phản rõ ràng, tự nhiên.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:notwithstanding',
    title: 'Notwithstanding ..., ...',
    template: 'Notwithstanding [A], [B].',
    description: 'Nối hai ý đối lập hoặc nhượng bộ.',
    category: 'Tương phản',
    exampleA: 'the risks',
    exampleB: 'investors remained confident',
    exampleNoteVi: 'A và B tạo sự tương phản rõ ràng, tự nhiên.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:conversely',
    title: 'Conversely, ...',
    template: '[A]. Conversely, [B].',
    description: 'Nối hai ý đối lập hoặc nhượng bộ.',
    category: 'Tương phản',
    exampleA: 'Some jobs are disappearing',
    exampleB: 'new roles are being created',
    exampleNoteVi: 'A và B tạo sự tương phản rõ ràng, tự nhiên.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:admittedly',
    title: 'Admittedly, ... However, ...',
    template: 'Admittedly, [A]. However, [B].',
    description: 'Nối hai ý đối lập hoặc nhượng bộ.',
    category: 'Tương phản',
    exampleA: 'the policy is expensive',
    exampleB: 'the long-term benefits outweigh the costs',
    exampleNoteVi: 'A và B tạo sự tương phản rõ ràng, tự nhiên.',
    starred: true,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:that-said',
    title: 'That said, ...',
    template: '[A]. That said, [B].',
    description: 'Nối hai ý đối lập hoặc nhượng bộ.',
    category: 'Tương phản',
    exampleA: 'Remote work is convenient',
    exampleB: 'team culture still needs face-to-face time',
    exampleNoteVi: 'A và B tạo sự tương phản rõ ràng, tự nhiên.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:all-the-same',
    title: 'All the same, ...',
    template: '[A]. All the same, [B].',
    description: 'Nối hai ý đối lập hoặc nhượng bộ.',
    category: 'Tương phản',
    exampleA: 'The evidence is incomplete',
    exampleB: 'we should take precautions',
    exampleNoteVi: 'A và B tạo sự tương phản rõ ràng, tự nhiên.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:yet',
    title: '..., yet ...',
    template: '[A], yet [B].',
    description: 'Nối hai ý đối lập hoặc nhượng bộ.',
    category: 'Tương phản',
    exampleA: 'The task was simple',
    exampleB: 'few people completed it correctly',
    exampleNoteVi: 'A và B tạo sự tương phản rõ ràng, tự nhiên.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:unlike',
    title: 'Unlike ..., ...',
    template: 'Unlike [A], [B].',
    description: 'Nối hai ý đối lập hoặc nhượng bộ.',
    category: 'Tương phản',
    exampleA: 'previous generations',
    exampleB: 'young people change careers more often',
    exampleNoteVi: 'A và B tạo sự tương phản rõ ràng, tự nhiên.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:in-comparison-with',
    title: 'In comparison with ..., ...',
    template: 'In comparison with [A], [B].',
    description: 'Nối hai ý đối lập hoặc nhượng bộ.',
    category: 'Tương phản',
    exampleA: 'traditional classrooms',
    exampleB: 'online courses offer greater flexibility',
    exampleNoteVi: 'A và B tạo sự tương phản rõ ràng, tự nhiên.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:be-that-as-it-may',
    title: 'Be that as it may, ...',
    template: '[A]. Be that as it may, [B].',
    description: 'Nối hai ý đối lập hoặc nhượng bộ.',
    category: 'Tương phản',
    exampleA: 'The criticism is understandable',
    exampleB: 'the reform is still necessary',
    exampleNoteVi: 'A và B tạo sự tương phản rõ ràng, tự nhiên.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:it-goes-without-saying',
    title: 'It goes without saying that ...',
    template: 'It goes without saying that [A] if [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'practice is essential',
    exampleB: 'you want to improve',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:needless-to-say',
    title: 'Needless to say, ...',
    template: 'Needless to say, [A] when [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'safety comes first',
    exampleB: 'lives are at risk',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:as-far-as-concerned',
    title: 'As far as ... is concerned',
    template: 'As far as [A] is concerned, [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'cost',
    exampleB: 'this option is the most efficient',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:with-regard-to',
    title: 'With regard to ..., ...',
    template: 'With regard to [A], [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'employment',
    exampleB: 'technology is a double-edged sword',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:in-relation-to',
    title: 'In relation to ..., ...',
    template: 'In relation to [A], [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'public health',
    exampleB: 'clean air is essential',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:as-regards',
    title: 'As regards ..., ...',
    template: 'As regards [A], [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'your proposal',
    exampleB: 'we need further details',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:it-is-worth-noting',
    title: 'It is worth noting that ...',
    template: 'It is worth noting that [A] when [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'results vary widely',
    exampleB: 'sample sizes are small',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:it-should-be-noted',
    title: 'It should be noted that ...',
    template: 'It should be noted that [A], particularly [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'the data is incomplete',
    exampleB: 'for rural areas',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:a-case-in-point',
    title: 'A case in point is ...',
    template: 'A case in point is [A], which [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'Singapore',
    exampleB: 'has invested heavily in public transport',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:take-for-example',
    title: 'Take ..., for example',
    template: 'Take [A], for example: [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'Finland',
    exampleB: 'its education system prioritises equity',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:this-means-that',
    title: 'This means that ...',
    template: '[A]. This means that [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'More people work remotely',
    exampleB: 'cities must rethink office demand',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:in-other-words',
    title: 'In other words, ...',
    template: '[A]. In other words, [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'Prevention is cheaper than treatment',
    exampleB: 'investing early saves money later',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:to-put-it-simply',
    title: 'To put it simply, ...',
    template: 'To put it simply, [A] because [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'we need cleaner energy',
    exampleB: 'fossil fuels harm the planet',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:broadly-speaking',
    title: 'Broadly speaking, ...',
    template: 'Broadly speaking, [A] tends to [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'urbanisation',
    exampleB: 'increase living costs',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:by-and-large',
    title: 'By and large, ...',
    template: 'By and large, [A] is [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'the reform',
    exampleB: 'a success',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:to-a-large-extent',
    title: 'To a large extent, ...',
    template: 'To a large extent, [A] depends on [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'academic success',
    exampleB: 'consistent study habits',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: true,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:to-some-extent',
    title: 'To some extent, ...',
    template: 'To some extent, [A], but [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'technology replaces workers',
    exampleB: 'it also creates new roles',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:be-bound-to',
    title: 'be bound to ...',
    template: '[A] is bound to [B] if nothing changes.',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'The problem',
    exampleB: 'get worse',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:be-prone-to',
    title: 'be prone to ...',
    template: '[A] are prone to [B] under stress.',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'People',
    exampleB: 'make poor decisions',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:be-subject-to',
    title: 'be subject to ...',
    template: '[A] is subject to [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'The agreement',
    exampleB: 'final approval',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:have-yet-to',
    title: 'have yet to ...',
    template: '[A] have yet to [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'Many countries',
    exampleB: 'meet their climate targets',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:it-remains-to-be-seen',
    title: 'It remains to be seen whether ...',
    template: 'It remains to be seen whether [A] will [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'the reform',
    exampleB: 'deliver lasting benefits',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:at-the-expense-of',
    title: 'at the expense of ...',
    template: '[A] grew at the expense of [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'Economic growth',
    exampleB: 'the environment',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: true,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:in-the-long-run',
    title: 'in the long run',
    template: 'In the long run, [A] is better than [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'prevention',
    exampleB: 'treatment',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:in-the-short-term',
    title: 'in the short term',
    template: 'In the short term, [A], but in the long term [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'the policy may be costly',
    exampleB: 'it will save money',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:by-no-means',
    title: 'by no means',
    template: '[A] is by no means [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'The problem',
    exampleB: 'easy to solve',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:on-no-account',
    title: 'On no account ...',
    template: 'On no account should [A] [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'children',
    exampleB: 'be left unsupervised online',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:under-no-circumstances',
    title: 'Under no circumstances ...',
    template: 'Under no circumstances should [A] [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'sensitive data',
    exampleB: 'be shared without consent',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:little-did',
    title: 'Little did ... know',
    template: 'Little did [A] know that [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'they',
    exampleB: 'the decision would change everything',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'C1',
  },
  {
    id: 'catalog:ss:so-adj-that',
    title: 'so ... that ...',
    template: '[A] was so [B] that we postponed the trip.',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'The weather',
    exampleB: 'bad',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'A2',
  },
  {
    id: 'catalog:ss:such-that',
    title: 'such ... that ...',
    template: 'It was such [A] that [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'a difficult exam',
    exampleB: 'many students failed',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:too-to',
    title: 'too ... to ...',
    template: '[A] is too [B] to ignore.',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'The issue',
    exampleB: 'important',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'A2',
  },
  {
    id: 'catalog:ss:enough-to',
    title: 'enough ... to ...',
    template: '[A] is not experienced enough to [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'He',
    exampleB: 'lead the project alone',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'A2',
  },
  {
    id: 'catalog:ss:used-to',
    title: 'used to ...',
    template: '[A] used to [B], but not anymore.',
    description: 'Đã từng… (thói quen quá khứ).',
    category: 'Khác',
    exampleA: 'I',
    exampleB: 'live in the countryside',
    exampleNoteVi: 'Tôi đã từng sống ở nông thôn, nhưng không còn nữa.',
    starred: false,
    cefr: 'A2',
  },
  {
    id: 'catalog:ss:be-used-to',
    title: 'be used to + V-ing',
    template: '[A] is used to [B].',
    description: 'Quen với…',
    category: 'Khác',
    exampleA: 'She',
    exampleB: 'working under pressure',
    exampleNoteVi: 'Cô ấy quen làm việc dưới áp lực.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:get-used-to',
    title: 'get used to + V-ing',
    template: 'It takes time to get used to [A] after [B].',
    description: 'Dần quen với…',
    category: 'Khác',
    exampleA: 'a new routine',
    exampleB: 'moving abroad',
    exampleNoteVi: 'Cần thời gian để quen thói quen mới sau khi chuyển ra nước ngoài.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:look-forward-to',
    title: 'look forward to + V-ing',
    template: 'I look forward to [A] when [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'meeting you',
    exampleB: 'you visit our office',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'A2',
  },
  {
    id: 'catalog:ss:be-committed-to',
    title: 'be committed to ...',
    template: '[A] is committed to [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'The company',
    exampleB: 'reducing emissions',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:make-sense-to',
    title: 'it makes sense to ...',
    template: 'It makes sense to [A] rather than [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'invest early',
    exampleB: 'pay higher costs later',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:from-my-perspective',
    title: 'From my perspective, ...',
    template: 'From my perspective, [A] is more important than [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'equity',
    exampleB: 'short-term profit',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:all-things-considered',
    title: 'All things considered, ...',
    template: 'All things considered, [A] seems [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'the proposal',
    exampleB: 'reasonable',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:taking-into-account',
    title: 'Taking ... into account',
    template: 'Taking [A] into account, [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'inflation',
    exampleB: 'real wages have fallen',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:as-opposed-to',
    title: 'as opposed to ...',
    template: '[A], as opposed to [B], is more sustainable.',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'Renewable energy',
    exampleB: 'fossil fuels',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:in-favour-of',
    title: 'in favour of ...',
    template: 'I am in favour of [A] because [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'free school meals',
    exampleB: 'they improve learning outcomes',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:be-opposed-to',
    title: 'be opposed to ...',
    template: 'Many people are opposed to [A] unless [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'higher taxes',
    exampleB: 'services clearly improve',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:on-balance',
    title: 'On balance, ...',
    template: 'On balance, [A] outweighs [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'the benefits of the reform',
    exampleB: 'its drawbacks',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: true,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:last-but-not-least',
    title: 'Last but not least, ...',
    template: 'Last but not least, [A] can [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'community involvement',
    exampleB: 'make policies more effective',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:all-in-all',
    title: 'All in all, ...',
    template: 'All in all, [A] is [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'the project',
    exampleB: 'a worthwhile investment',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:to-conclude',
    title: 'To conclude, ...',
    template: 'To conclude, [A] should [B].',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'governments',
    exampleB: 'act sooner rather than later',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:in-conclusion-essay',
    title: 'In conclusion, ...',
    template: 'In conclusion, [A] and [B] are both necessary.',
    description: 'Cấu trúc Writing / collocation / nhấn mạnh thường gặp.',
    category: 'Khác',
    exampleA: 'individual effort',
    exampleB: 'government support',
    exampleNoteVi: 'Điền A và B để hoàn thành câu theo mẫu.',
    starred: true,
    cefr: 'B1',
  },
]
