import type { SentenceStructure } from '@ryan/db'

type CatalogStructure = Omit<SentenceStructure, 'createdAt' | 'updatedAt'>

export const CATALOG_SENTENCE_STRUCTURES: CatalogStructure[] = [
  {
    id: 'catalog:ss:just-because',
    title: "Just because ... doesn't mean ...",
    template: "Just because [A] doesn't mean [B].",
    description: 'Dùng để nói một lý do chưa đủ để kết luận điều gì.',
    category: 'Liên từ / Lý do',
    exampleA: 'you fail once',
    exampleB: 'you should give up',
    exampleNoteVi: 'Chỉ vì bạn thất bại một lần không có nghĩa là bạn nên bỏ cuộc.',
    starred: true,
    cefr: 'B2',
  },
  {
    id: 'catalog:ss:the-more',
    title: 'The more ..., the more ...',
    template: 'The more [A], the more [B].',
    description: 'Hai vế tỷ lệ thuận — càng… càng…',
    category: 'So sánh',
    exampleA: 'you practise',
    exampleB: 'you improve',
    exampleNoteVi: 'Bạn càng luyện tập nhiều, bạn càng tiến bộ.',
    starred: true,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:so-that',
    title: 'S + V ... so that S + can + V',
    template: '[A] so that I can [B].',
    description: 'Nêu mục đích của hành động — để có thể làm gì.',
    category: 'Mục đích',
    exampleA: 'I wake up early',
    exampleB: 'finish my homework',
    exampleNoteVi: 'Tôi dậy sớm để có thể hoàn thành bài tập.',
    starred: false,
    cefr: 'A2',
  },
  {
    id: 'catalog:ss:although',
    title: 'Although ..., ...',
    template: 'Although [A], [B].',
    description: 'Mệnh đề tương phản — mặc dù… nhưng…',
    category: 'Tương phản',
    exampleA: 'it was raining',
    exampleB: 'we still went out',
    exampleNoteVi: 'Mặc dù trời mưa, chúng tôi vẫn đi ra ngoài.',
    starred: false,
    cefr: 'B1',
  },
  {
    id: 'catalog:ss:if-will',
    title: 'If ..., ... will ...',
    template: 'If [A], [B].',
    description: 'Câu điều kiện loại 1 — nếu… thì sẽ…',
    category: 'Điều kiện',
    exampleA: 'you study hard',
    exampleB: 'you will succeed',
    exampleNoteVi: 'Nếu bạn học chăm, bạn sẽ đạt kết quả tốt.',
    starred: false,
    cefr: 'A2',
  },
  {
    id: 'catalog:ss:not-only',
    title: 'Not only ... but also ...',
    template: 'Not only [A], but also [B].',
    description: 'Nhấn mạnh hai ý song song.',
    category: 'Liên từ / Lý do',
    exampleA: 'is it cheap',
    exampleB: 'it is effective',
    exampleNoteVi: 'Không những rẻ mà còn hiệu quả.',
    starred: false,
    cefr: 'B2',
  },
]