// Generated by scripts/writing/build-cambridge-writing-index.mjs. Do not edit manually.
import type { CambridgeWritingTest } from './schema.ts'

export const CAMBRIDGE_WRITING_GENERATED_TESTS = {
  b1: [] as CambridgeWritingTest[],
  b2: [] as CambridgeWritingTest[],
  c1: [] as CambridgeWritingTest[],
  c2: [] as CambridgeWritingTest[],
} as const
