// Generated by scripts/writing/build-cambridge-writing-index.mjs. Do not edit manually.
import generatedTest0 from '../../../data/cambridge-writing/b1/b1-test-02.json'
import generatedTest1 from '../../../data/cambridge-writing/b1/b1-test-03.json'
import generatedTest2 from '../../../data/cambridge-writing/b1/b1-test-04.json'
import generatedTest3 from '../../../data/cambridge-writing/b1/b1-test-05.json'
import generatedTest4 from '../../../data/cambridge-writing/b1/b1-test-06.json'
import generatedTest5 from '../../../data/cambridge-writing/b2/b2-test-02.json'
import generatedTest6 from '../../../data/cambridge-writing/b2/b2-test-03.json'
import generatedTest7 from '../../../data/cambridge-writing/b2/b2-test-04.json'
import generatedTest8 from '../../../data/cambridge-writing/b2/b2-test-05.json'
import generatedTest9 from '../../../data/cambridge-writing/b2/b2-test-06.json'
import generatedTest10 from '../../../data/cambridge-writing/c1/c1-test-02.json'
import generatedTest11 from '../../../data/cambridge-writing/c1/c1-test-03.json'
import generatedTest12 from '../../../data/cambridge-writing/c1/c1-test-04.json'
import generatedTest13 from '../../../data/cambridge-writing/c1/c1-test-05.json'
import generatedTest14 from '../../../data/cambridge-writing/c1/c1-test-06.json'
import generatedTest15 from '../../../data/cambridge-writing/c2/c2-test-02.json'
import generatedTest16 from '../../../data/cambridge-writing/c2/c2-test-03.json'
import generatedTest17 from '../../../data/cambridge-writing/c2/c2-test-04.json'
import generatedTest18 from '../../../data/cambridge-writing/c2/c2-test-05.json'
import generatedTest19 from '../../../data/cambridge-writing/c2/c2-test-06.json'
import type { CambridgeWritingTest } from './schema.ts'

export const CAMBRIDGE_WRITING_GENERATED_TESTS = {
  b1: [generatedTest0, generatedTest1, generatedTest2, generatedTest3, generatedTest4] as CambridgeWritingTest[],
  b2: [generatedTest5, generatedTest6, generatedTest7, generatedTest8, generatedTest9] as CambridgeWritingTest[],
  c1: [generatedTest10, generatedTest11, generatedTest12, generatedTest13, generatedTest14] as CambridgeWritingTest[],
  c2: [generatedTest15, generatedTest16, generatedTest17, generatedTest18, generatedTest19] as CambridgeWritingTest[],
} as const
