import {
  CambridgeWritingCollectionSchema,
  CambridgeWritingManifestSchema,
  type CambridgeWritingCollection,
  type CambridgeWritingLevel,
  type CambridgeWritingManifest,
} from './schema.ts'
import ketReadingBook4Test2 from '../../../data/reading-ket-a2-book4-test2.json'

const ketA2Book4Test2 = ketReadingBook4Test2 as {
  id: string
  parts: Array<{
    id: string
    partNumber: number
    passage: Array<{ text?: string; imageUrl?: string }>
    questionGroups?: Array<{
      instruction?: string
      questions?: Array<{ prompt: string; minWords?: number }>
    }>
  }>
}

const a2Part6 = ketA2Book4Test2.parts.find((part) => part.partNumber === 6)!
const a2Part7 = ketA2Book4Test2.parts.find((part) => part.partNumber === 7)!

const collections = [
  {
    level: 'a2',
    examName: 'KET',
    title: 'KET · A2 Writing Seed Collection',
    testCount: 1,
    tests: [
      {
        id: 'ket-a2-book4-test2',
        level: 'a2',
        testNumber: 1,
        title: 'KET A2 Writing · Book 4 · Test 2',
        sourceFile: 'packages/catalog/data/reading-ket-a2-book4-test2.json',
        status: 'published',
        version: 1,
        tasks: [
          {
            id: 'ket-a2-book4-test2-task-31',
            partNumber: 6,
            taskNumber: 31,
            title: 'Question 31',
            genre: 'email',
            instruction: a2Part6.questionGroups?.[0]?.instruction ?? 'Write 25 words or more.',
            promptText: a2Part6.passage.map((block) => block.text ?? '').filter(Boolean).join('\n\n'),
            wordLimit: {
              min: a2Part6.questionGroups?.[0]?.questions?.[0]?.minWords ?? 25,
              displayText: a2Part6.questionGroups?.[0]?.instruction ?? '25 words or more',
            },
            metadata: {
              compulsory: true,
              sourceQuestionNumber: '31',
              ketSourcePartId: a2Part6.id,
              ketQuestionPrompt: a2Part6.questionGroups?.[0]?.questions?.[0]?.prompt ?? '',
            },
          },
          {
            id: 'ket-a2-book4-test2-task-32',
            partNumber: 7,
            taskNumber: 32,
            title: 'Question 32',
            genre: 'story',
            instruction: a2Part7.questionGroups?.[0]?.instruction ?? 'Write 35 words or more.',
            promptText: a2Part7.questionGroups?.[0]?.questions?.[0]?.prompt ?? '',
            wordLimit: {
              min: a2Part7.questionGroups?.[0]?.questions?.[0]?.minWords ?? 35,
              displayText: a2Part7.questionGroups?.[0]?.instruction ?? '35 words or more',
            },
            metadata: {
              compulsory: true,
              sourceQuestionNumber: '32',
              ketSourcePartId: a2Part7.id,
              ketQuestionPrompt: a2Part7.questionGroups?.[0]?.questions?.[0]?.prompt ?? '',
              ketImageUrls: a2Part7.passage.map((block) => block.imageUrl ?? '').filter(Boolean),
            },
          },
        ],
      },
    ],
  },
  {
    level: 'b1',
    examName: 'PET',
    title: 'PET · B1 Writing Seed Collection',
    testCount: 1,
    tests: [
      {
        id: 'b1-test-01',
        level: 'b1',
        testNumber: 1,
        title: 'PET B1 Digital Sample Test 1',
        sourceUrl: 'https://ceq.inspera.com/player/?assessmentRunId=146726796&context=exam#/section/4128591741313/question/143865262',
        sourceFile: 'docs/research/ceq.inspera.com/writing/b1.questions.json',
        status: 'published',
        version: 1,
        tasks: [
          {
            id: 'b1-test-01-task-01',
            partNumber: 1,
            taskNumber: 1,
            title: 'Question 1',
            genre: 'email',
            instruction: 'You must answer this question. Write your answer in about 100 words.',
            promptText: [
              'Read this email from your English-speaking friend Sandy and the notes you have made.',
              'Write your email to Sandy using all the notes.',
            ].join('\n\n'),
            wordLimit: { min: 100, max: 100, displayText: 'about 100 words' },
            metadata: { compulsory: true, sourceQuestionNumber: '1' },
          },
          {
            id: 'b1-test-01-task-02',
            partNumber: 2,
            taskNumber: 2,
            title: 'Question 2',
            genre: 'article',
            instruction: 'Answer one of these questions. Write your answer in about 100 words.',
            promptText: [
              'You see this notice on an English-language website.',
              'Articles wanted',
              'FILMS',
              'What kind of films do you enjoy?',
              'Do you prefer watching them at the cinema or at home? Why?',
              'Write an article answering these questions and we will put it on our website!',
              'Write your article.',
            ].join('\n'),
            wordLimit: { min: 100, max: 100, displayText: 'about 100 words' },
            metadata: { compulsory: false, sourceQuestionNumber: '2' },
          },
          {
            id: 'b1-test-01-task-03',
            partNumber: 2,
            taskNumber: 3,
            title: 'Question 3',
            genre: 'story',
            instruction: 'Answer one of these questions. Write your answer in about 100 words.',
            promptText: [
              'Your English teacher has asked you to write a story.',
              'Your story must begin with this sentence.',
              'As the plane flew lower, Lou saw the golden beaches of the island below.',
              'Write your story.',
            ].join('\n'),
            wordLimit: { min: 100, max: 100, displayText: 'about 100 words' },
            metadata: { compulsory: false, sourceQuestionNumber: '3' },
          },
        ],
      },
    ],
  },
  {
    level: 'b2',
    examName: 'FCE',
    title: 'FCE · B2 Writing Seed Collection',
    testCount: 1,
    tests: [
      {
        id: 'b2-test-01',
        level: 'b2',
        testNumber: 1,
        title: 'FCE B2 Digital Sample Test 1',
        sourceUrl: 'https://ceq.inspera.com/player/?assessmentRunId=146732614&context=exam#/section/4060115584647/question/143372237',
        sourceFile: 'docs/research/ceq.inspera.com/writing/b2.questions.json',
        status: 'published',
        version: 1,
        tasks: [
          {
            id: 'b2-test-01-task-01',
            partNumber: 1,
            taskNumber: 1,
            title: 'Question 1',
            genre: 'essay',
            instruction: 'You must answer this question. Write 140–190 words in an appropriate style.',
            promptText: [
              'In your English class you have been talking about the environment. Now, your English teacher has asked you to write an essay.',
              'Write an essay using all the notes and giving reasons for your point of view.',
              'Every country in the world has problems with pollution and damage to the environment. Do you think these problems can be solved?',
              'Notes',
              'Write about:',
              '1. transport',
              '2. rivers and seas',
              '3. your own idea',
            ].join('\n\n'),
            wordLimit: { min: 140, max: 190, displayText: '140–190 words' },
            metadata: { compulsory: true, sourceQuestionNumber: '1' },
          },
          {
            id: 'b2-test-01-task-02',
            partNumber: 2,
            taskNumber: 2,
            title: 'Question 2',
            genre: 'review',
            instruction: 'Answer one of these questions. Write 140–190 words in an appropriate style.',
            promptText: [
              'You see this announcement in your college English-language magazine.',
              'Book reviews wanted',
              'Have you read a book in which the main character behaved in a surprising way?',
              'Write us a review of the book, explaining what the main character did and why it was surprising.',
              'Tell us whether or not you would recommend this book to other people.',
              'The best reviews will be published in the magazine.',
              'Write your review.',
            ].join('\n'),
            wordLimit: { min: 140, max: 190, displayText: '140–190 words' },
            metadata: { compulsory: false, sourceQuestionNumber: '2' },
          },
          {
            id: 'b2-test-01-task-03',
            partNumber: 2,
            taskNumber: 3,
            title: 'Question 3',
            genre: 'article',
            instruction: 'Answer one of these questions. Write 140–190 words in an appropriate style.',
            promptText: [
              'You see this announcement on an English-language website.',
              'Articles wanted',
              'The most useful thing I have ever learned',
              'What is the most useful thing you have learned?',
              'Who did you learn it from? Why is it useful?',
              'Write us an article answering these questions.',
              'We will publish the best articles on our website.',
              'Write your article.',
            ].join('\n'),
            wordLimit: { min: 140, max: 190, displayText: '140–190 words' },
            metadata: { compulsory: false, sourceQuestionNumber: '3' },
          },
          {
            id: 'b2-test-01-task-04',
            partNumber: 2,
            taskNumber: 4,
            title: 'Question 4',
            genre: 'email',
            instruction: 'Answer one of these questions. Write 140–190 words in an appropriate style.',
            promptText: [
              'You have received this email from your English-speaking friend David.',
              'From: David',
              'Subject: touring holiday',
              'Some college friends of mine are visiting your area soon for a week’s touring holiday.',
              'They would like to travel around and learn about your local area and its history.',
              'Can you tell me about some of the places they could visit? What’s the best way to travel around – car, bike or coach?',
              'Thanks,',
              'David',
              'Write your email.',
            ].join('\n'),
            wordLimit: { min: 140, max: 190, displayText: '140–190 words' },
            metadata: { compulsory: false, sourceQuestionNumber: '4' },
          },
        ],
      },
    ],
  },
  {
    level: 'c1',
    examName: 'CAE',
    title: 'CAE · C1 Writing Seed Collection',
    testCount: 1,
    tests: [
      {
        id: 'c1-test-01',
        level: 'c1',
        testNumber: 1,
        title: 'CAE C1 Digital Sample Test 2',
        sourceUrl: 'https://ceq.inspera.com/player/?assessmentRunId=415313797&context=exam#/section/7937623297746/question/406033127/scorableItem/1',
        sourceFile: 'docs/research/ceq.inspera.com/writing/c1.questions.json',
        status: 'published',
        version: 1,
        tasks: [
          {
            id: 'c1-test-01-task-01',
            partNumber: 1,
            taskNumber: 1,
            title: 'Question 1',
            genre: 'essay',
            instruction: 'You must answer this question. Write 220–260 words in an appropriate style.',
            promptText: [
              'Your class has listened to a radio discussion programme about facilities which should receive money from local authorities.',
              'You have made the notes below:',
              'Which facilities should receive money from local authorities?',
              '- museums',
              '- sports centres',
              '- public gardens',
              'Some opinions expressed in the discussion:',
              '“Museums are not popular with everybody!”',
              '“Sports centres mean healthier people.”',
              '“A town needs green spaces – parks are great for everybody.”',
              'Write an essay for your tutor discussing two of the facilities in your notes.',
              'You should explain which facility it is more important for your local authorities to give money to, giving reasons in support of your answer.',
            ].join('\n'),
            wordLimit: { min: 220, max: 260, displayText: '220–260 words' },
            metadata: { compulsory: true, sourceQuestionNumber: '1' },
          },
          {
            id: 'c1-test-01-task-02',
            partNumber: 2,
            taskNumber: 2,
            title: 'Question 2',
            genre: 'proposal',
            instruction: 'Answer one of these questions. Write 220–260 words in an appropriate style.',
            promptText: [
              'The international college where you study would like to organise a series of events to encourage student interaction with the local community.',
              'It has invited students to suggest ideas for this.',
              'You decide to send in a proposal in which you outline the kind of events that you think would be most effective,',
              'how to get the widest number of students involved, and what you think the main benefits of these events will be,',
              'to both the students and the local community.',
              'Write your proposal.',
            ].join('\n'),
            wordLimit: { min: 220, max: 260, displayText: '220–260 words' },
            metadata: { compulsory: false, sourceQuestionNumber: '2' },
          },
          {
            id: 'c1-test-01-task-03',
            partNumber: 2,
            taskNumber: 3,
            title: 'Question 3',
            genre: 'email',
            instruction: 'Answer one of these questions. Write 220–260 words in an appropriate style.',
            promptText: [
              'You recently attended a course which did not provide everything that was promised in its publicity.',
              'Write an email to the organizer of the course.',
              'In your email you should evaluate the course overall, and complain about the inaccuracy of the publicity material, justifying your opinions.',
              'You should also recommend the action that you believe the course organizer should take.',
              'Write your email.',
            ].join('\n'),
            wordLimit: { min: 220, max: 260, displayText: '220–260 words' },
            metadata: { compulsory: false, sourceQuestionNumber: '3' },
          },
          {
            id: 'c1-test-01-task-04',
            partNumber: 2,
            taskNumber: 4,
            title: 'Question 4',
            genre: 'review',
            instruction: 'Answer one of these questions. Write 220–260 words in an appropriate style.',
            promptText: [
              'You see this announcement on an English-language lifestyle website:',
              'Digital detox',
              'Have you ever done a digital detox where you intentionally did not use devices like your smartphone or laptop for a period of time?',
              'If so, we would love to receive a review about your experience.',
              'In your review, briefly say why you decided to do this, evaluate how worthwhile it was for you and explain whether you would recommend this to others.',
              'Write your review.',
            ].join('\n'),
            wordLimit: { min: 220, max: 260, displayText: '220–260 words' },
            metadata: { compulsory: false, sourceQuestionNumber: '4' },
          },
        ],
      },
    ],
  },
  {
    level: 'c2',
    examName: 'CPE',
    title: 'CPE · C2 Writing Seed Collection',
    testCount: 1,
    tests: [
      {
        id: 'c2-test-01',
        level: 'c2',
        testNumber: 1,
        title: 'CPE C2 Digital Sample Test 1',
        sourceUrl: 'https://ceq.inspera.com/player/?assessmentRunId=146745736&context=exam#/section/7185437720868/question/143372866/scorableItem/1',
        sourceFile: 'docs/research/ceq.inspera.com/writing/c2.questions.json',
        status: 'published',
        version: 1,
        tasks: [
          {
            id: 'c2-test-01-task-01',
            partNumber: 1,
            taskNumber: 1,
            title: 'Question 1',
            genre: 'essay',
            instruction: 'You must answer this question. Write an essay summarising and evaluating the key points from both texts in 240–280 words.',
            promptText: [
              'Use your own words throughout as far as possible, and include your own ideas in your answers.',
              'Text 1: Shifting sands: behavioural change',
              'Nowadays, in some cultures there may often be confusion between generations about what is acceptable behaviour in certain situations.',
              'Older people sometimes complain, for example, about the real or imagined rudeness of others, such as in the use of electronic devices in public places.',
              'Text 2: Follow my leader?',
              'Should we always aim to do what society expects of us? No, what society needs is individuality.',
              'Worrying about what other people think inhibits enthusiasm and creativity.',
            ].join('\n'),
            wordLimit: { min: 240, max: 280, displayText: '240–280 words' },
            metadata: { compulsory: true, sourceQuestionNumber: '1' },
          },
          {
            id: 'c2-test-01-task-02',
            partNumber: 2,
            taskNumber: 2,
            title: 'Question 2',
            genre: 'review',
            instruction: 'Answer one of these questions. Write 280–320 words in an appropriate style.',
            promptText: [
              'A literary magazine is running a series of reviews of books that people enjoyed reading as a child and would recommend for children today.',
              'You decide to send in a review in which you describe a book you enjoyed and the attractions it had for you as a child.',
              'You should also explain why you feel it remains relevant for children today.',
              'Write your review.',
            ].join('\n'),
            wordLimit: { min: 280, max: 320, displayText: '280–320 words' },
            metadata: { compulsory: false, sourceQuestionNumber: '2' },
          },
          {
            id: 'c2-test-01-task-03',
            partNumber: 2,
            taskNumber: 3,
            title: 'Question 3',
            genre: 'report',
            instruction: 'Answer one of these questions. Write 280–320 words in an appropriate style.',
            promptText: [
              'A jobs fair was recently held in your town for international organisations and companies to promote careers available for young people.',
              'You have been asked to write a report of the jobs fair for your college website.',
              'You should briefly describe the event and identify two or three promotions of particular interest and relevance.',
              'You should also evaluate the extent to which such events can open young people’s minds to new challenges and career opportunities.',
              'Write your report.',
            ].join('\n'),
            wordLimit: { min: 280, max: 320, displayText: '280–320 words' },
            metadata: { compulsory: false, sourceQuestionNumber: '3' },
          },
          {
            id: 'c2-test-01-task-04',
            partNumber: 2,
            taskNumber: 4,
            title: 'Question 4',
            genre: 'article',
            instruction: 'Answer one of these questions. Write 280–320 words in an appropriate style.',
            promptText: [
              'An international travel magazine is running a series of articles on alternatives to travelling by plane.',
              'The magazine has invited readers to send in articles briefly describing a memorable long-distance train or bus journey they have made.',
              'The article should explain the advantages of travelling a long distance by train or bus and consider whether in general travelling to your destination more slowly may result in a more satisfying travel experience.',
              'Write your article.',
            ].join('\n'),
            wordLimit: { min: 280, max: 320, displayText: '280–320 words' },
            metadata: { compulsory: false, sourceQuestionNumber: '4' },
          },
        ],
      },
    ],
  },
] satisfies CambridgeWritingCollection[]

export const CAMBRIDGE_WRITING_COLLECTIONS = collections.map((collection) =>
  CambridgeWritingCollectionSchema.parse(collection),
)

export const CAMBRIDGE_WRITING_COLLECTION_MAP = Object.fromEntries(
  CAMBRIDGE_WRITING_COLLECTIONS.map((collection) => [collection.level, collection]),
) as Record<CambridgeWritingLevel, CambridgeWritingCollection>

export const CAMBRIDGE_WRITING_MANIFEST = CambridgeWritingManifestSchema.parse({
  a2: {
    examName: 'KET',
    displayName: 'KET · A2',
    testCount: 1,
    taskCount: 2,
    genres: ['email', 'story'],
  },
  b1: {
    examName: 'PET',
    displayName: 'PET · B1',
    testCount: 1,
    taskCount: 3,
    genres: ['email', 'article', 'story'],
  },
  b2: {
    examName: 'FCE',
    displayName: 'FCE · B2',
    testCount: 1,
    taskCount: 4,
    genres: ['essay', 'review', 'article', 'email'],
  },
  c1: {
    examName: 'CAE',
    displayName: 'CAE · C1',
    testCount: 1,
    taskCount: 4,
    genres: ['essay', 'proposal', 'email', 'review'],
  },
  c2: {
    examName: 'CPE',
    displayName: 'CPE · C2',
    testCount: 1,
    taskCount: 4,
    genres: ['essay', 'review', 'report', 'article'],
  },
}) satisfies CambridgeWritingManifest
