#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Ryan English Local Kokoro TTS Server
- Endpoint: http://127.0.0.1:<port>/tts?text=hello&lang=b&voice=bf_emma&speed=1
- Returns WAV audio generated by Kokoro when dependencies are installed.
- Health/status endpoints never require heavy imports, so Electron can always show a helpful status.
"""
from __future__ import annotations

import argparse
import io
import json
import os
import sys
import time
import traceback
import threading
import urllib.parse
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any, Dict, Optional, Tuple

HOST = "127.0.0.1"
PORT = 8788
SAMPLE_RATE = 24000
MAX_TEXT_CHARS = 500

_pipeline_cache: Dict[str, Any] = {}
_audio_cache: Dict[Tuple[str, str, str, float], Tuple[bytes, str]] = {}
_last_error: Optional[str] = None
_deps_cache: Optional[Dict[str, Any]] = None
_deps_cache_ts: float = 0.0
_pipeline_lock = threading.RLock()
_tts_lock = threading.RLock()
_deps_lock = threading.RLock()


def _json_bytes(data: Dict[str, Any]) -> bytes:
    return json.dumps(data, ensure_ascii=False, indent=2).encode("utf-8")


def _clean_text(value: str) -> str:
    text = (value or "").replace("\x00", " ").strip()
    return " ".join(text.split())[:MAX_TEXT_CHARS]


def _normalize_lang(value: str) -> str:
    v = (value or "").lower().strip()
    if v in {"b", "en-gb", "uk", "british"}:
        return "b"
    if v in {"a", "en-us", "us", "american"}:
        return "a"
    return "b"


def _default_voice(lang_code: str) -> str:
    # Kokoro naming convention: a* = American English, b* = British English.
    return "bf_emma" if lang_code == "b" else "af_heart"


def _dependency_status(force: bool = False) -> Dict[str, Any]:
    """Check heavy Kokoro dependencies. Cached so /deps and UI do not freeze server startup."""
    global _deps_cache, _deps_cache_ts
    with _deps_lock:
        now = time.time()
        if (not force) and _deps_cache and (now - _deps_cache_ts) < 30:
            cached = dict(_deps_cache)
            cached["cached"] = True
            cached["last_error"] = _last_error
            return cached

        status: Dict[str, Any] = {
            "python": sys.version.split()[0],
            "executable": sys.executable,
            "kokoro": False,
            "soundfile": False,
            "numpy": False,
            "ready": False,
            "last_error": _last_error,
            "cached": False,
        }
        try:
            import kokoro  # noqa: F401
            status["kokoro"] = True
        except Exception as exc:
            status["kokoro_error"] = str(exc)
        try:
            import soundfile  # noqa: F401
            status["soundfile"] = True
        except Exception as exc:
            status["soundfile_error"] = str(exc)
        try:
            import numpy  # noqa: F401
            status["numpy"] = True
        except Exception as exc:
            status["numpy_error"] = str(exc)
        status["ready"] = bool(status["kokoro"] and status["soundfile"] and status["numpy"])
        if not status["ready"]:
            status["install_hint"] = "pip install -r server/python/requirements.txt"
        _deps_cache = dict(status)
        _deps_cache_ts = now
        return status


def _quick_health() -> Dict[str, Any]:
    """Fast health endpoint: never imports Kokoro, so Electron can detect the server immediately."""
    data: Dict[str, Any] = {
        "ok": True,
        "service": "Ryan English Kokoro TTS",
        "host": HOST,
        "port": PORT,
        "python": sys.version.split()[0],
        "executable": sys.executable,
        "ready": None,
        "deps_checked": bool(_deps_cache),
        "last_error": _last_error,
    }
    if _deps_cache:
        # Keep health lightweight but still surface the latest known result.
        data.update({
            "ready": bool(_deps_cache.get("ready")),
            "kokoro": bool(_deps_cache.get("kokoro")),
            "soundfile": bool(_deps_cache.get("soundfile")),
            "numpy": bool(_deps_cache.get("numpy")),
            "install_hint": _deps_cache.get("install_hint"),
        })
    return data

def _get_pipeline(lang_code: str):
    global _last_error
    with _pipeline_lock:
        if lang_code in _pipeline_cache:
            return _pipeline_cache[lang_code]
        try:
            from kokoro import KPipeline
            try:
                pipeline = KPipeline(lang_code=lang_code, repo_id="hexgrad/Kokoro-82M")
            except TypeError:
                pipeline = KPipeline(lang_code=lang_code)
            _pipeline_cache[lang_code] = pipeline
            _last_error = None
            return pipeline
        except Exception as exc:
            _last_error = str(exc)
            raise


def _concat_audio(chunks: list):
    import numpy as np
    if not chunks:
        return np.zeros(int(SAMPLE_RATE * 0.2), dtype="float32")
    normalized = []
    for item in chunks:
        try:
            normalized.append(np.asarray(item, dtype="float32"))
        except Exception:
            pass
    if not normalized:
        return np.zeros(int(SAMPLE_RATE * 0.2), dtype="float32")
    return np.concatenate(normalized)


def _synth_chunks(text: str, lang_code: str, voice: str, speed: float) -> list:
    pipeline = _get_pipeline(lang_code)
    chunks = []
    generator = pipeline(text, voice=voice, speed=speed, split_pattern=r"\n+")
    for _gs, _ps, audio in generator:
        chunks.append(audio)
    return chunks


def _generate_wav(text: str, lang_code: str, voice: str, speed: float) -> Tuple[bytes, str]:
    """Generate WAV bytes. Serialised because Kokoro/spaCy lazy setup is not safe under concurrent first requests."""
    cache_key = (text, lang_code, voice, round(float(speed or 1.0), 2))
    if cache_key in _audio_cache:
        return _audio_cache[cache_key]

    with _tts_lock:
        if cache_key in _audio_cache:
            return _audio_cache[cache_key]

        import soundfile as sf

        used_voice = voice or _default_voice(lang_code)
        attempts = [(lang_code, used_voice)]
        same_lang_default = _default_voice(lang_code)
        if used_voice != same_lang_default:
            attempts.append((lang_code, same_lang_default))
        if lang_code != "a":
            attempts.append(("a", "af_heart"))

        errors = []
        chunks = []
        for try_lang, try_voice in attempts:
            try:
                chunks = _synth_chunks(text, try_lang, try_voice, speed)
                used_voice = try_voice
                break
            except Exception as exc:
                errors.append(f"{try_voice}: {exc}")
                chunks = []
        if not chunks:
            raise RuntimeError("Kokoro không tạo được audio: " + " | ".join(errors[-3:]))

        audio = _concat_audio(chunks)
        bio = io.BytesIO()
        sf.write(bio, audio, SAMPLE_RATE, format="WAV", subtype="PCM_16")
        result = (bio.getvalue(), used_voice)
        if len(_audio_cache) > 250:
            try:
                _audio_cache.pop(next(iter(_audio_cache)))
            except Exception:
                pass
        _audio_cache[cache_key] = result
        return result


class RyanKokoroHandler(BaseHTTPRequestHandler):
    server_version = "RyanEnglishKokoro/1.0"

    def log_message(self, fmt: str, *args: Any) -> None:
        if os.environ.get("RYAN_KOKORO_DEBUG") == "1":
            super().log_message(fmt, *args)

    def _send_headers(self, status: int, content_type: str, extra: Optional[Dict[str, str]] = None) -> None:
        self.send_response(status)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.send_header("Cache-Control", "no-store")
        self.send_header("Content-Type", content_type)
        for key, value in (extra or {}).items():
            self.send_header(key, value)
        self.end_headers()

    def do_OPTIONS(self) -> None:  # noqa: N802
        self._send_headers(204, "text/plain; charset=utf-8")

    def do_GET(self) -> None:  # noqa: N802
        global _last_error
        parsed = urllib.parse.urlparse(self.path)
        query = urllib.parse.parse_qs(parsed.query)
        path = parsed.path.rstrip("/") or "/"

        if path in {"/", "/health"}:
            data = _quick_health()
            body = _json_bytes(data)
            self._send_headers(200, "application/json; charset=utf-8", {"Content-Length": str(len(body))})
            self.wfile.write(body)
            return

        if path in {"/status", "/deps"}:
            data = _dependency_status(force=(query.get("force", [""])[0] == "1"))
            data.update({"ok": True, "service": "Ryan English Kokoro TTS", "host": HOST, "port": PORT})
            body = _json_bytes(data)
            self._send_headers(200, "application/json; charset=utf-8", {"Content-Length": str(len(body))})
            self.wfile.write(body)
            return

        if path != "/tts":
            body = _json_bytes({"ok": False, "error": "Not found", "path": path})
            self._send_headers(404, "application/json; charset=utf-8", {"Content-Length": str(len(body))})
            self.wfile.write(body)
            return

        text = _clean_text(query.get("text", [""])[0])
        if not text:
            body = _json_bytes({"ok": False, "error": "Missing text"})
            self._send_headers(400, "application/json; charset=utf-8", {"Content-Length": str(len(body))})
            self.wfile.write(body)
            return

        lang_code = _normalize_lang(query.get("lang", ["b"])[0])
        voice = (query.get("voice", [""])[0] or _default_voice(lang_code)).strip()
        try:
            speed = float(query.get("speed", ["1"])[0])
            speed = max(0.55, min(1.45, speed))
        except Exception:
            speed = 1.0

        started = time.time()
        try:
            audio, used_voice = _generate_wav(text, lang_code, voice, speed)
            _last_error = None
            self._send_headers(200, "audio/wav; codecs=1", {
                "Content-Length": str(len(audio)),
                "X-Ryan-TTS-Voice": used_voice,
                "X-Ryan-TTS-Seconds": f"{time.time() - started:.3f}",
            })
            self.wfile.write(audio)
        except Exception as exc:
            _last_error = str(exc)
            body = _json_bytes({
                "ok": False,
                "error": str(exc),
                "trace": traceback.format_exc(limit=3),
                "status": _dependency_status(),
            })
            self._send_headers(500, "application/json; charset=utf-8", {"Content-Length": str(len(body))})
            self.wfile.write(body)


def _warmup_pipeline(lang_code: str) -> None:
    try:
        _dependency_status(force=True)
        _get_pipeline(lang_code)
        try:
            _generate_wav("hello", lang_code, _default_voice(lang_code), 1.0)
        except Exception:
            pass
        print(f"Ryan English Kokoro warmup OK: {lang_code}", flush=True)
    except Exception as exc:
        print(f"Ryan English Kokoro warmup skipped for {lang_code}: {exc}", flush=True)


class RyanThreadingHTTPServer(ThreadingHTTPServer):
    allow_reuse_address = True


def main() -> int:
    global HOST, PORT
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", default=HOST)
    parser.add_argument("--port", type=int, default=PORT)
    args = parser.parse_args()
    HOST = args.host
    PORT = int(args.port)
    try:
        httpd = RyanThreadingHTTPServer((HOST, PORT), RyanKokoroHandler)
    except PermissionError as exc:
        print(f"Ryan English Kokoro bind error at http://{HOST}:{PORT}: {exc}", file=sys.stderr, flush=True)
        return 98
    except OSError as exc:
        print(f"Ryan English Kokoro bind error at http://{HOST}:{PORT}: {exc}", file=sys.stderr, flush=True)
        return 98
    print(f"Ryan English Kokoro TTS server running at http://{HOST}:{PORT}", flush=True)
    threading.Thread(target=_warmup_pipeline, args=("b",), daemon=True).start()
    try:
        httpd.serve_forever(poll_interval=0.3)
    except KeyboardInterrupt:
        pass
    finally:
        httpd.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
