export type Part1QuestionBankEntry = {
  topic: string
  aliases: string[]
  questions: string[]
  hints: string[]
  sampleAnswerStructure: string
}

const PART1_QUESTION_BANK: Part1QuestionBankEntry[] = [
  {
    topic: 'Hometown',
    aliases: ['Where you live now', 'HOMETOWN'],
    questions: [
      'Where is your hometown?',
      'What do you like most about your hometown?',
      'Is there anything you dislike about your hometown?',
      'Has your hometown changed much since you were a child?',
      'Would you recommend your hometown to tourists? Why?',
    ],
    hints: ['scenery', 'friendly locals', 'pace of life', 'urban development', 'tourist attraction', 'close-knit community'],
    sampleAnswerStructure: 'State location → mention 1-2 positive aspects → acknowledge a drawback → conclude with recommendation',
  },
  {
    topic: 'Work or Study',
    aliases: ['Work / Study', 'WORK'],
    questions: [
      'Do you work or are you a student?',
      'What do you like most about your work/studies?',
      'Is there anything you dislike about your work/studies?',
      'What are your future plans for work or study?',
      'How do you usually spend your day at work/school?',
    ],
    hints: ['fulfilling', 'challenging', 'career path', 'qualification', 'work-life balance', 'long-term goal'],
    sampleAnswerStructure: 'Identify status → share what you enjoy → mention a challenge → outline future plans',
  },
  {
    topic: 'Family',
    aliases: ['FAMILY'],
    questions: [
      'Do you have a large or small family?',
      'How often do you spend time with your family?',
      'What do you enjoy doing together with your family?',
      'Are you more similar to your mother or your father?',
      'Who are you closest to in your family?',
    ],
    hints: ['close-knit', 'supportive', 'gathering', 'bond', 'take after', 'role model'],
    sampleAnswerStructure: 'Describe family size → mention activities → explain who you are closest to and why',
  },
  {
    topic: 'Friends',
    aliases: [],
    questions: [
      'How often do you see your friends?',
      'What do you usually do with your friends?',
      'Do you prefer spending time with friends or family?',
      'How did you meet your best friend?',
      'Is it easy to make new friends where you live?',
    ],
    hints: ['hang out', 'common interest', 'trustworthy', 'sense of humour', 'lifelong', 'keep in touch'],
    sampleAnswerStructure: 'State frequency → describe activities → compare with family → share how you met a close friend',
  },
  {
    topic: 'Neighbours',
    aliases: [],
    questions: [
      'Do you know your neighbours well?',
      'What makes a good neighbour?',
      'Have you ever had a problem with a neighbour?',
      'How can neighbours help each other?',
      'Do you think it is important to have good neighbours?',
    ],
    hints: ['considerate', 'keep to themselves', 'friendly', 'community spirit', 'helpful', 'respect privacy'],
    sampleAnswerStructure: 'Describe current neighbours → define a good neighbour → share an experience → explain importance',
  },
  {
    topic: 'Childhood',
    aliases: [],
    questions: [
      'What is your happiest childhood memory?',
      'Did you enjoy your childhood?',
      'What did you like to do as a child?',
      'Where did you grow up?',
      'Do you think childhood is the best time of life?',
    ],
    hints: ['carefree', 'nostalgic', 'fond memory', 'grow up', 'innocent', 'play outdoors'],
    sampleAnswerStructure: 'Share a specific memory → describe activities → reflect on whether childhood is the best time',
  },
  {
    topic: 'Pets',
    aliases: ['Pets and animals', 'ANIMALS'],
    questions: [
      'Do you have any pets?',
      'What is your favourite animal? Why?',
      'Do you think it is good for children to have pets?',
      'Are there any animals you are afraid of?',
      'What animals are common in your country?',
    ],
    hints: ['companion', 'loyal', 'look after', 'rescue', 'wildlife', 'domestic'],
    sampleAnswerStructure: 'State if you have pets → explain favourite animal → discuss benefits for children → mention fears',
  },
  {
    topic: 'Education',
    aliases: [],
    questions: [
      'What was your favourite subject at school?',
      'Did you enjoy your time at school?',
      'Do you think education is important? Why?',
      'What would you like to study in the future?',
      'How is education in your country different from other countries?',
    ],
    hints: ['curriculum', 'qualified', 'memorable', 'practical', 'academic', 'valuable'],
    sampleAnswerStructure: 'Name favourite subject → explain why → discuss importance → share future study plans',
  },
  {
    topic: 'Languages',
    aliases: ['LANGUAGES'],
    questions: [
      'How many languages can you speak?',
      'What language would you like to learn in the future?',
      'Do you think it is important to learn a foreign language?',
      'What is the most difficult part of learning a new language?',
      'How do you usually practise a language?',
    ],
    hints: ['fluent', 'mother tongue', 'pick up', 'grammar', 'pronunciation', 'immerse'],
    sampleAnswerStructure: 'State languages spoken → explain a challenge → discuss importance → share practice methods',
  },
  {
    topic: 'Reading',
    aliases: ['Reading carefully'],
    questions: [
      'Do you like reading?',
      'What kind of books do you usually read?',
      'Do you prefer reading books or watching films?',
      'Do you read newspapers or magazines?',
      'Where do you usually read?',
    ],
    hints: ['fiction', 'non-fiction', 'novel', 'bestseller', 'browse', 'page-turner'],
    sampleAnswerStructure: 'State reading habits → mention genres → compare with films → describe reading environment',
  },
  {
    topic: 'Newspapers',
    aliases: ['NEWS'],
    questions: [
      'Do you often read newspapers?',
      'How do you usually get your news?',
      'Do you prefer reading news online or in print?',
      'What type of news are you most interested in?',
      'Do you think it is important to follow the news?',
    ],
    hints: ['headline', 'current affairs', 'reliable source', 'subscribe', 'keep up with', 'breaking news'],
    sampleAnswerStructure: 'State frequency → mention preferred format → explain interests → discuss importance',
  },
  {
    topic: 'Hobbies',
    aliases: ['Free time activities'],
    questions: [
      'What do you do in your free time?',
      'How long have you had this hobby?',
      'Is it an expensive hobby?',
      'Do you prefer indoor or outdoor hobbies?',
      'Would you like to try a new hobby in the future?',
    ],
    hints: ['pastime', 'take up', 'leisure', 'passionate about', 'relaxing', 'rewarding'],
    sampleAnswerStructure: 'Describe hobby → explain when you started → discuss cost → mention future hobby plans',
  },
  {
    topic: 'Music',
    aliases: [],
    questions: [
      'What kind of music do you like?',
      'Do you play any musical instruments?',
      'How often do you listen to music?',
      'Has your taste in music changed over the years?',
      'Do you prefer listening to music alone or with others?',
    ],
    hints: ['genre', 'melody', 'rhythm', 'lyrics', 'live performance', 'upbeat'],
    sampleAnswerStructure: 'Name favourite genre → mention instruments → discuss how taste has changed → explain listening habits',
  },
  {
    topic: 'Sport',
    aliases: ['Team sport', 'SPORT'],
    questions: [
      'Do you like sports?',
      'What sport do you usually play?',
      'How often do you exercise?',
      'Do you prefer watching or playing sports?',
      'What is the most popular sport in your country?',
    ],
    hints: ['keep fit', 'competitive', 'teamwork', 'spectator', 'athletic', 'stamina'],
    sampleAnswerStructure: 'State favourite sport → describe frequency → compare watching vs playing → mention popular sport',
  },
  {
    topic: 'Films',
    aliases: [],
    questions: [
      'Do you like watching films?',
      'What kind of films do you enjoy?',
      'Do you prefer watching films at home or at the cinema?',
      'What was the last film you watched?',
      'Do you have a favourite actor or actress?',
    ],
    hints: ['blockbuster', 'plot', 'special effects', 'soundtrack', 'cast', 'genre'],
    sampleAnswerStructure: 'State preference → name favourite genre → compare home vs cinema → mention a recent film',
  },
  {
    topic: 'Television',
    aliases: [],
    questions: [
      'How often do you watch TV?',
      'What kind of programmes do you like to watch?',
      'Do you prefer watching TV alone or with others?',
      'Do you think watching too much TV is bad?',
      'What did you watch on TV when you were a child?',
    ],
    hints: ['documentary', 'series', 'episode', 'channel', 'binge-watch', 'entertaining'],
    sampleAnswerStructure: 'State frequency → name programme types → discuss childhood viewing → mention whether too much TV is harmful',
  },
  {
    topic: 'Art',
    aliases: ['ART', 'Drawing'],
    questions: [
      'Do you like art?',
      'Have you ever been to an art gallery?',
      'Do you think art is important for children?',
      'Can you draw or paint?',
      'What kind of art do you like?',
    ],
    hints: ['creative', 'masterpiece', 'exhibition', 'inspiring', 'imagination', 'appreciate'],
    sampleAnswerStructure: 'State interest in art → mention gallery visits → discuss importance for children → describe preferred art style',
  },
  {
    topic: 'Photography',
    aliases: [],
    questions: [
      'Do you like taking photographs?',
      'What do you usually take photos of?',
      'Do you prefer taking photos or being in photos?',
      'How do you store your photos?',
      'Do you think photographs are important?',
    ],
    hints: ['capture', 'scenery', 'portrait', 'album', 'memorable', 'freeze a moment'],
    sampleAnswerStructure: 'State photography habits → describe subjects → discuss storage → explain importance',
  },
  {
    topic: 'Technology',
    aliases: [],
    questions: [
      'Do you use technology a lot?',
      'What device do you use most often?',
      'Has technology changed your life? How?',
      'Do you think people rely too much on technology?',
      'What technology would you like to have in the future?',
    ],
    hints: ['gadget', 'convenient', 'essential', 'device', 'rely on', 'innovative'],
    sampleAnswerStructure: 'Describe technology use → name main device → discuss impact → mention future technology',
  },
  {
    topic: 'Social Media',
    aliases: ['SOCIAL MEDIA'],
    questions: [
      'Do you use social media?',
      'Which social media platform do you use most?',
      'How much time do you spend on social media?',
      'Do you think social media has more positive or negative effects?',
      'Have you ever met someone through social media?',
    ],
    hints: ['connect', 'scroll', 'follow', 'update', 'distracting', 'stay in touch'],
    sampleAnswerStructure: 'State platforms used → mention time spent → discuss pros and cons → share an experience',
  },
  {
    topic: 'Robots',
    aliases: [],
    questions: [
      'Are you interested in robots?',
      'Would you like to have a robot at home?',
      'Do you think robots will replace human workers?',
      'What jobs do you think robots will do in the future?',
      'Are there any dangers with robots?',
    ],
    hints: ['automation', 'artificial intelligence', 'efficient', 'replace', 'programmable', 'robotics'],
    sampleAnswerStructure: 'State interest → discuss home robots → mention job replacement → discuss dangers',
  },
  {
    topic: 'Emails',
    aliases: [],
    questions: [
      'How often do you check your emails?',
      'Do you prefer emails or text messages?',
      'Do you think emails are important for work?',
      'How do you feel when you receive too many emails?',
      'Do you reply to emails immediately?',
    ],
    hints: ['inbox', 'correspondence', 'formal', 'spam', 'prompt reply', 'efficient'],
    sampleAnswerStructure: 'State frequency → compare with text messages → discuss work importance → mention email overload',
  },
  {
    topic: 'Food',
    aliases: [],
    questions: [
      'What is your favourite food?',
      'Do you like cooking?',
      'How often do you eat out?',
      'Is there any food you dislike?',
      'What is a traditional dish in your country?',
    ],
    hints: ['delicious', 'cuisine', 'ingredient', 'home-cooked', 'appetite', 'flavour'],
    sampleAnswerStructure: 'Name favourite food → discuss cooking habits → mention eating out → describe a traditional dish',
  },
  {
    topic: 'Health',
    aliases: [],
    questions: [
      'How do you keep healthy?',
      'Do you think you have a healthy diet?',
      'What do you do when you feel unwell?',
      'Do you think people are healthier now than in the past?',
      'Is it important to have a healthy lifestyle?',
    ],
    hints: ['balanced diet', 'well-being', 'immune system', ' nutritious', 'keep fit', 'vital'],
    sampleAnswerStructure: 'Describe health habits → discuss diet → mention what you do when ill → compare past and present',
  },
  {
    topic: 'Morning routine',
    aliases: ['Morning Routine', 'MORNINGS', 'ROUTINE'],
    questions: [
      'What is the first thing you do in the morning?',
      'Do you have the same morning routine every day?',
      'Are you a morning person?',
      'How do you feel in the morning?',
      'Would you like to change your morning routine?',
    ],
    hints: ['early riser', 'alarm clock', 'freshen up', 'energised', 'consistent', 'rush'],
    sampleAnswerStructure: 'Describe first activity → state consistency → discuss being a morning person → mention changes',
  },
  {
    topic: 'Exercise',
    aliases: [],
    questions: [
      'How often do you exercise?',
      'What kind of exercise do you do?',
      'Do you prefer exercising alone or with others?',
      'Where do you usually exercise?',
      'Do you think it is important to exercise every day?',
    ],
    hints: ['work out', 'stamina', 'gym', 'jogging', 'flexibility', 'cardio'],
    sampleAnswerStructure: 'State frequency → describe type → mention location → discuss importance of daily exercise',
  },
  {
    topic: 'Sleep',
    aliases: [],
    questions: [
      'How many hours do you usually sleep?',
      'Do you think you get enough sleep?',
      'Do you have a routine before bed?',
      'Do you ever take naps during the day?',
      'What do you do if you cannot sleep?',
    ],
    hints: ['restful', 'insomnia', 'winding down', 'power nap', 'sleep schedule', 'exhausted'],
    sampleAnswerStructure: 'State hours → discuss if it is enough → describe bedtime routine → mention what you do when sleepless',
  },
  {
    topic: 'Weather',
    aliases: ['WEATHER'],
    questions: [
      'What is your favourite type of weather?',
      'Does the weather affect your mood?',
      'What do you do on rainy days?',
      'Has the weather in your country changed in recent years?',
      'Do you prefer hot or cold weather?',
    ],
    hints: ['mild', 'overcast', 'unpredictable', 'scorching', 'freezing', 'downpour'],
    sampleAnswerStructure: 'State preference → discuss mood impact → mention rainy day activities → compare hot and cold',
  },
  {
    topic: 'Coffee & Tea',
    aliases: ['COFFEE & TEA'],
    questions: [
      'Do you prefer coffee or tea?',
      'How often do you drink coffee or tea?',
      'Do you usually drink coffee or tea at home or in a cafe?',
      'Have you ever tried any special types of coffee or tea?',
      'Do you think drinking too much coffee is bad?',
    ],
    hints: ['caffeine', 'brew', 'aroma', 'refreshing', 'habit', 'espresso'],
    sampleAnswerStructure: 'State preference → mention frequency → discuss where → mention any special varieties',
  },
  {
    topic: 'Phones',
    aliases: ['PHONES'],
    questions: [
      'How often do you use your phone?',
      'What do you usually use your phone for?',
      'Do you think you use your phone too much?',
      'What was the first mobile phone you had?',
      'How would you feel if you lost your phone?',
    ],
    hints: ['apps', 'addicted', 'essential', 'contact', 'upgrade', 'screen time'],
    sampleAnswerStructure: 'State frequency → list uses → discuss overuse → share first phone experience',
  },
  {
    topic: 'Clothes',
    aliases: ['CLOTHES'],
    questions: [
      'What kind of clothes do you usually wear?',
      'Do you prefer casual or formal clothes?',
      'Has your style of clothing changed over the years?',
      'Do you think clothes are important?',
      'How often do you buy new clothes?',
    ],
    hints: ['fashion', 'comfortable', 'trendy', 'wardrobe', 'fit', 'fabric'],
    sampleAnswerStructure: 'Describe usual style → discuss casual vs formal → mention how style changed → discuss importance',
  },
  {
    topic: 'Names',
    aliases: ['NAMES'],
    questions: [
      'Does your name have a special meaning?',
      'Do you like your name?',
      'Is there a tradition for naming children in your country?',
      'Have you ever wanted to change your name?',
      'Do people in your country usually have nicknames?',
    ],
    hints: ['given name', 'meaningful', 'tradition', 'nickname', 'unique', 'named after'],
    sampleAnswerStructure: 'Explain name meaning → state if you like it → describe naming traditions → mention nicknames',
  },
  {
    topic: 'Noise',
    aliases: ['NOISE'],
    questions: [
      'Do you mind noisy places?',
      'Are there any noisy places near where you live?',
      'What kinds of noise do you dislike most?',
      'Do you prefer a quiet or noisy environment when studying?',
      'Have you ever been disturbed by noise?',
    ],
    hints: ['distracting', 'peaceful', 'construction', 'annoying', 'tranquil', 'bustling'],
    sampleAnswerStructure: 'State tolerance → mention nearby noise → describe disliked noise → discuss study environment',
  },
  {
    topic: 'Gifts',
    aliases: [],
    questions: [
      'Do you like receiving gifts?',
      'What was the best gift you have ever received?',
      'Do you prefer giving or receiving gifts?',
      'How do you choose a gift for someone?',
      'Do you think gifts should be expensive?',
    ],
    hints: ['thoughtful', 'unforgettable', 'unwrap', 'gesture', 'personal', 'meaningful'],
    sampleAnswerStructure: 'State preference → share best gift → discuss choosing gifts → mention whether price matters',
  },
  {
    topic: 'Shopping',
    aliases: [],
    questions: [
      'Do you enjoy shopping?',
      'How often do you go shopping?',
      'Do you prefer shopping online or in stores?',
      'What do you usually buy when you go shopping?',
      'Do you think shopping is a good way to relax?',
    ],
    hints: ['browse', 'bargain', 'convenient', 'window shopping', 'impulse buy', 'retail'],
    sampleAnswerStructure: 'State enjoyment → mention frequency → compare online vs stores → discuss relaxation aspect',
  },
  {
    topic: 'Travelling',
    aliases: [],
    questions: [
      'Do you like travelling?',
      'Where would you like to travel in the future?',
      'Do you prefer travelling alone or with others?',
      'What is the most interesting place you have visited?',
      'How do you usually plan your trips?',
    ],
    hints: ['destination', 'itinerary', 'explore', 'memorable', 'tourist', 'adventure'],
    sampleAnswerStructure: 'State enjoyment → mention dream destination → discuss solo vs group → share a memorable trip',
  },
  {
    topic: 'Parks and Gardens',
    aliases: [],
    questions: [
      'Do you often go to parks or gardens?',
      'What do you usually do there?',
      'Are there many parks near your home?',
      'Do you think parks are important for cities?',
      'Did you go to parks often as a child?',
    ],
    hints: ['green space', 'relaxing', 'stroll', 'fresh air', 'nature', 'peaceful'],
    sampleAnswerStructure: 'State frequency → describe activities → mention nearby parks → discuss importance for cities',
  },
  {
    topic: 'Science',
    aliases: [],
    questions: [
      'Are you interested in science?',
      'What is your favourite area of science?',
      'Did you enjoy science subjects at school?',
      'How has science changed our lives?',
      'Do you think science is important for the future?',
    ],
    hints: ['fascinating', 'discovery', 'experiment', 'technology', 'breakthrough', 'research'],
    sampleAnswerStructure: 'State interest → name favourite area → discuss school experience → mention impact on life',
  },
  {
    topic: 'Teachers',
    aliases: [],
    questions: [
      'Do you have a favourite teacher?',
      'What made that teacher special?',
      'Do you think teachers are important?',
      'Would you like to be a teacher in the future?',
      'How should a good teacher behave?',
    ],
    hints: ['inspiring', 'patient', 'knowledgeable', 'mentor', 'encouraging', 'dedicated'],
    sampleAnswerStructure: 'Name favourite teacher → explain what made them special → discuss importance → describe a good teacher',
  },
  {
    topic: 'Cars',
    aliases: [],
    questions: [
      'Do you have a car?',
      'Do you prefer travelling by car or by public transport?',
      'How often do you travel by car?',
      'Do you think cars are bad for the environment?',
      'What kind of car would you like to have in the future?',
    ],
    hints: ['commute', 'convenient', 'traffic jam', 'emissions', 'electric vehicle', 'fuel'],
    sampleAnswerStructure: 'State if you have a car → compare with public transport → discuss environmental impact → mention dream car',
  },
  {
    topic: 'Space Travel',
    aliases: [],
    questions: [
      'Are you interested in space travel?',
      'Do you think space travel will be common in the future?',
      'Would you like to travel to space?',
      'What do you think about space exploration?',
      'Is space travel important for humanity?',
    ],
    hints: ['astronaut', 'universe', 'galaxy', 'exploration', 'orbit', 'frontier'],
    sampleAnswerStructure: 'State interest → discuss future possibilities → mention willingness to go → discuss importance',
  },
  {
    topic: 'Feeling bored',
    aliases: [],
    questions: [
      'Do you often feel bored?',
      'What do you do when you feel bored?',
      'Do you think being bored is sometimes good?',
      'What activities do you find most boring?',
      'Do children get bored more easily than adults?',
    ],
    hints: ['monotonous', 'kill time', 'restless', 'tedious', 'unoccupied', 'entertain'],
    sampleAnswerStructure: 'State frequency → describe what you do → discuss if boredom is good → compare children and adults',
  },
  {
    topic: 'Dream and ambition',
    aliases: ['Dream and ambition'],
    questions: [
      'What is your biggest dream?',
      'Do you think you will achieve your dream?',
      'What did you want to be when you were a child?',
      'Do you think it is important to have ambitions?',
      'Who has inspired you to follow your dreams?',
    ],
    hints: ['aspiration', 'determined', 'role model', 'goal', 'achieve', 'passionate'],
    sampleAnswerStructure: 'Describe your dream → discuss achievability → mention childhood aspirations → discuss importance',
  },
  {
    topic: 'Talking to elderly people',
    aliases: [],
    questions: [
      'Do you enjoy talking to elderly people?',
      'What can we learn from older people?',
      'Do you think older people are respected in your country?',
      'How often do you spend time with elderly relatives?',
      'Do you think the elderly should live with their families?',
    ],
    hints: ['wisdom', 'generation gap', 'respect', 'life experience', 'valuable', 'care for'],
    sampleAnswerStructure: 'State enjoyment → mention what we can learn → discuss respect → share time spent with relatives',
  },
  {
    topic: 'Mirrors',
    aliases: [],
    questions: [
      'Do you often look in the mirror?',
      'Have you ever bought a mirror?',
      'Do you think mirrors are necessary in the home?',
      'Would you decorate your home with mirrors?',
      'Do you check yourself before going out?',
    ],
    hints: ['reflection', 'decorate', 'appearance', ' vanity', 'essential', 'glance'],
    sampleAnswerStructure: 'State frequency → discuss if you have bought one → mention necessity → discuss decoration',
  },
  {
    topic: 'Typing',
    aliases: [],
    questions: [
      'Do you type a lot every day?',
      'Do you prefer typing or writing by hand?',
      'How fast can you type?',
      'Do you think typing is an important skill?',
      'Have you ever had typing lessons?',
    ],
    hints: ['keyboard', 'efficient', 'speed', 'handwriting', 'digital', 'touch type'],
    sampleAnswerStructure: 'State frequency → compare with handwriting → mention speed → discuss importance',
  },
  {
    topic: 'Stage of life',
    aliases: [],
    questions: [
      'What stage of life are you in right now?',
      'Which stage of life do you think is the best?',
      'Do you look forward to the next stage of your life?',
      'What did you enjoy most about being a teenager?',
      'Do you think being an adult is harder than being a child?',
    ],
    hints: ['milestone', 'transition', 'responsibility', 'adulthood', 'adolescence', 'carefree'],
    sampleAnswerStructure: 'Describe current stage → discuss best stage → mention what you look forward to → compare adulthood and childhood',
  },
  {
    topic: 'Long walk',
    aliases: [],
    questions: [
      'Do you enjoy taking long walks?',
      'Where do you usually go for a walk?',
      'How often do you go for a long walk?',
      'Do you prefer walking alone or with someone?',
      'What do you think about while walking?',
    ],
    hints: ['stroll', 'refreshing', 'scenic route', 'clear my mind', 'companion', 'invigorating'],
    sampleAnswerStructure: 'State enjoyment → mention locations → discuss frequency → describe thoughts while walking',
  },
  {
    topic: 'Building',
    aliases: [],
    questions: [
      'What kind of building do you live in?',
      'Do you like the building where you live?',
      'Would you prefer to live in a house or an apartment?',
      'Are there any famous buildings in your city?',
      'What makes a building beautiful?',
    ],
    hints: ['architecture', 'high-rise', 'spacious', 'landmark', 'design', 'construction'],
    sampleAnswerStructure: 'Describe building type → state preference → mention famous buildings → discuss what makes a building beautiful',
  },
  {
    topic: 'Memory',
    aliases: [],
    questions: [
      'Do you have a good memory?',
      'Do you think it is important to have a good memory?',
      'What is your earliest memory?',
      'How do you remember important things?',
      'Is there something you will never forget?',
    ],
    hints: ['recall', 'forgetful', 'vivid', 'unforgettable', 'nostalgic', 'memorise'],
    sampleAnswerStructure: 'State if you have a good memory → share earliest memory → mention how you remember things → describe an unforgettable event',
  },
  {
    topic: 'Singing',
    aliases: [],
    questions: [
      'Do you like singing?',
      'How often do you sing?',
      'Do you sing in front of other people?',
      'What kind of songs do you like to sing?',
      'Did you sing in a choir or group when you were younger?',
    ],
    hints: ['melody', 'tune', 'choir', 'karaoke', 'in tune', 'perform'],
    sampleAnswerStructure: 'State enjoyment → mention frequency → discuss singing in public → describe favourite songs',
  },
  {
    topic: 'Watch',
    aliases: [],
    questions: [
      'Do you usually wear a watch?',
      'Do you think watches are still useful?',
      'Have you ever received a watch as a gift?',
      'Do you prefer digital or analogue watches?',
      'How often do you check the time?',
    ],
    hints: ['timepiece', 'wristwatch', 'punctual', 'smartwatch', 'accessory', 'keep track of time'],
    sampleAnswerStructure: 'State if you wear one → discuss usefulness → mention gifts → compare digital and analogue',
  },
  {
    topic: 'Tidiness',
    aliases: [],
    questions: [
      'Are you a tidy person?',
      'How often do you tidy your room?',
      'Do you think it is important to be tidy?',
      'Does your room get messy quickly?',
      'How do you feel when your room is messy?',
    ],
    hints: ['organised', 'neat', 'clutter', 'messy', 'keep things in order', 'spotless'],
    sampleAnswerStructure: 'State tidiness level → mention frequency → discuss importance → describe feelings about mess',
  },
  {
    topic: 'Headphones',
    aliases: [],
    questions: [
      'Do you often use headphones?',
      'What do you use headphones for?',
      'Do you prefer earphones or over-ear headphones?',
      'When would you not use headphones?',
      'Have you ever lost your headphones?',
    ],
    hints: ['wireless', 'noise-cancelling', 'volume', 'audio', 'convenient', 'distract'],
    sampleAnswerStructure: 'State frequency → mention uses → compare types → discuss situations where you would not use them',
  },
  {
    topic: 'Websites',
    aliases: [],
    questions: [
      'What websites do you visit most often?',
      'Do you think the internet is useful?',
      'How much time do you spend online every day?',
      'Do you prefer reading on websites or in books?',
      'Have you ever bought anything online?',
    ],
    hints: ['browse', 'bookmark', 'online shopping', 'reliable', 'search engine', 'information'],
    sampleAnswerStructure: 'Name favourite websites → discuss internet usefulness → mention time spent → compare with books',
  },
  {
    topic: 'Telling Jokes',
    aliases: [],
    questions: [
      'Do you like telling jokes?',
      'Do you know any good jokes?',
      'Do your friends often tell jokes?',
      'Do you think humour is important?',
      'Can you laugh at yourself?',
    ],
    hints: ['sense of humour', 'hilarious', 'witty', 'laugh', 'punchline', 'amusing'],
    sampleAnswerStructure: 'State enjoyment → share if you know jokes → discuss friends → discuss importance of humour',
  },
]

const aliasIndex = new Map<string, Part1QuestionBankEntry>()
for (const entry of PART1_QUESTION_BANK) {
  aliasIndex.set(entry.topic.toLowerCase(), entry)
  for (const alias of entry.aliases) aliasIndex.set(alias.toLowerCase(), entry)
}

export function lookupPart1Questions(topic: string): Part1QuestionBankEntry | undefined {
  const normalized = topic.toLowerCase().trim()
  return aliasIndex.get(normalized)
}

export function getAllPart1BankTopics(): string[] {
  return PART1_QUESTION_BANK.map(entry => entry.topic)
}
