import { useMemo, useRef, useState } from 'react'
import { ArrowLeft, CheckCircle2, ChevronDown, Mic, RotateCcw, Square, Volume2 } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { speak } from '../listening/tts'
import { sendSpeakingTurn, type TutorTurn } from '../speaking-ai/speakingAiApi'
import { useSpeakingRecorder } from '../speaking-ai/useSpeakingRecorder'
import type { ForecastItem } from './speakingIeltsData'

type Attempt={item:ForecastItem;part:1|2|3;transcript:string;duration:number;feedback:TutorTurn}
export default function SpeakingMockInterviewPage({items,sessionId}:{items:ForecastItem[];sessionId:string}){
 const nav=useNavigate(),recorder=useSpeakingRecorder();const[index,setIndex]=useState(0);const[attempts,setAttempts]=useState<Attempt[]>([]);const[status,setStatus]=useState<'ready'|'processing'|'feedback'|'summary'>('ready');const[feedback,setFeedback]=useState<TutorTurn>();const[error,setError]=useState('');const submitting=useRef(false);const item=items[index]??items[0];const part=(items.length>1?index+1:item?.part) as 1|2|3;const question=item?.cueCard??item?.title??'Tell me about yourself.';const transcript=useMemo(()=>recorder.transcript.trim(),[recorder.transcript]);
 async function submit(){if(!transcript||submitting.current)return;submitting.current=true;setStatus('processing');setError('');try{const result=await sendSpeakingTurn({transcript,durationSec:recorder.seconds||1,level:'B1',topic:item.title,mode:`IELTS_PART_${part}`,conversationId:sessionId==='demo'?undefined:sessionId});setFeedback(result);setAttempts(a=>a.some(attempt=>attempt.item.id===item.id)?a:[...a,{item,part,transcript,duration:recorder.seconds||1,feedback:result}]);setStatus('feedback')}catch(e){setError(e instanceof Error?e.message:'Không thể gửi bài.');setStatus('ready')}finally{submitting.current=false}}
 function next(){recorder.reset();setFeedback(undefined);if(index>=items.length-1)setStatus('summary');else{setIndex(i=>i+1);setStatus('ready')}}
 if(status==='summary'){const duration=attempts.reduce((n,x)=>n+x.duration,0);return <main className="si-interview"><header className="si-interview-top"><b>IELTS MOCK INTERVIEW</b><span><i/> AI ONLINE</span></header><section className="si-summary"><CheckCircle2/><small>SESSION COMPLETE</small><h1>Hoàn thành bài Mock Interview!</h1><div className="si-summary-stats"><b>{items.length}<small>Tổng câu</small></b><b>{attempts.length}<small>Đã trả lời</small></b><b>{duration}s<small>Thời lượng</small></b><b>—<small>Overall Band</small></b></div>{attempts.map((a,i)=><details key={`${a.item.id}-${i}`}><summary>Part {a.part} · {a.item.title}</summary><p><b>Transcript:</b> {a.transcript}</p><p><b>Feedback:</b> {a.feedback.reply}</p></details>)}<div><button className="si-primary" onClick={()=>{setIndex(0);setAttempts([]);setStatus('ready')}}><RotateCcw/> Luyện lại</button><Link to="/app/speaking/ielts">Về IELTS Speaking</Link></div></section></main>}
 return <main className="si-interview"><header className="si-interview-top"><button aria-label="Quay lại" onClick={()=>nav(-1)}><ArrowLeft/></button><div className="si-interview-brand"><span className="si-interview-mic"><Mic/></span><b>IELTS MOCK INTERVIEW</b></div><span><i/> AI ONLINE</span></header><div className="si-geo"/><section className="si-interview-body"><div className="si-progress"><b>PART {part}</b><span>Câu {index+1} / {items.length}</span></div><article className="si-question"><small>TOPIC · {item.title}</small><h1>{question}</h1>{part===2&&<div className="si-timers"><b>01:00<small> Chuẩn bị</small></b><b>02:00<small> Trả lời</small></b></div>}<button className="si-listen" onClick={()=>void speak(question,{speed:1,lang:'a'})}><Volume2/> Nghe lại</button>{item.bulletPoints.length>0&&<details><summary><ChevronDown/> Gợi ý tham khảo</summary><ul>{item.bulletPoints.map(x=><li key={x}>{x}</li>)}</ul></details>}{item.questions&&item.questions.length>0&&<details><summary><ChevronDown/> Câu hỏi gợi ý ({item.questions.length})</summary><ul>{item.questions.map((q,i)=><li key={i}>{q}</li>)}</ul></details>}{item.hints&&item.hints.length>0&&<details><summary><ChevronDown/> Từ vựng gợi ý</summary><p>{item.hints.join(', ')}</p></details>}{item.sampleAnswerStructure&&<details><summary><ChevronDown/> Dàn ý gợi ý</summary><p>{item.sampleAnswerStructure}</p></details>}</article><section className="si-recorder">{recorder.audio&&<audio controls src={recorder.audio.url}/>}<button aria-label={recorder.state==='recording'?'Dừng ghi âm':'Bấm để nói'} className={`si-mic ${recorder.state==='recording'?'recording':''}`} disabled={status!=='ready'} onClick={recorder.state==='recording'?recorder.stop:recorder.start}>{recorder.state==='recording'?<Square/>:<Mic/>}</button><b>{recorder.state==='recording'?`Đang ghi âm · ${recorder.seconds}s`:'Bấm để nói'}</b>{transcript&&<p className="si-live">“{transcript}”</p>}{recorder.error&&<p role="alert">{recorder.error}</p>}{error&&<p role="alert">{error} <button onClick={()=>void submit()}>Thử lại</button></p>}<button className="si-primary" disabled={!transcript||status!=='ready'} onClick={()=>void submit()}>{status==='processing'?'AI đang phân tích…':'Gửi để nhận feedback'}</button></section>{feedback&&<section className="si-feedback" aria-live="polite"><small>FEEDBACK TỪ AI</small><h2>Nhận xét câu trả lời</h2><p>{feedback.reply}</p>{feedback.correction?.corrected&&<p><b>Gợi ý sửa:</b> {feedback.correction.corrected}</p>}<button className="si-primary" onClick={next}>{index===items.length-1?'Xem tổng kết':'Câu tiếp theo'}</button></section>}</section></main>}
