import fullRaw from './data/articles-full.json'
import type {
  BilingualArticle,
  BilingualSource,
  BilingualSourceId,
} from './types'

const ALL = fullRaw as BilingualArticle[]

const R2 = 'https://pub-c71988294a9b45099e83dad66bb73426.r2.dev/images'

/**
 * Flagship (top grid, no badge) = first entries without `recommended`.
 * `recommended: true` = only under “✦ Recommended by Ryan” (no duplicate of top).
 * Covers: unique hero images from article art (not recycled brand tiles).
 */
export const BILINGUAL_SOURCES: BilingualSource[] = [
  {
    id: 'the-atlantic',
    name: 'The Atlantic',
    coverUrl: `${R2}/migrated/ielts-website/blog/htcfq20u8xaaupo6anst.webp`,
  },
  {
    id: 'the-new-york-times',
    name: 'The New York Times',
    coverUrl: `${R2}/migrated/ielts-website/blog/hdfvqht0suztjso0houz.webp`,
  },
  {
    id: 'reuters',
    name: 'Reuters',
    coverUrl: `${R2}/migrated/ielts-website/blog/hbixcbkajuyrbqgfcymd.webp`,
  },
  {
    id: 'substack',
    name: 'Substack',
    coverUrl: `${R2}/migrated/ielts-website/blog/tpcisi2srcegh2mskx1q.webp`,
    recommended: true,
  },
  {
    id: 'the-conversation',
    name: 'The Conversation',
    coverUrl: `${R2}/blog/6786b8ef-364c-4ee6-b0e0-e1e43ab690d2.webp`,
    recommended: true,
  },
  {
    id: 'the-guardian',
    name: 'The Guardian',
    coverUrl: `${R2}/migrated/ielts-website/blog/kurzmbj2rulebfh4xcfv.webp`,
    recommended: true,
  },
  {
    id: 'topic-psychology',
    name: 'Psychology',
    coverUrl: `${R2}/migrated/ielts-website/blog/qov8zv1gjqdn6rnswyr9.webp`,
    recommended: true,
    topicKeywords: [
      'psychology',
      'mental',
      'mindfulness',
      'neuroscience',
      'emotion',
    ],
  },
  {
    id: 'topic-technology',
    name: 'Technology & AI',
    coverUrl: `${R2}/migrated/ielts-website/blog/nqaiftiiwp7iqtgjlmb7.webp`,
    recommended: true,
    topicKeywords: [
      'technology',
      'artificial intelligence',
      'ai',
      'internet',
      'privacy',
    ],
  },
  {
    id: 'topic-health',
    name: 'Health & Wellness',
    coverUrl: `${R2}/migrated/ielts-website/blog/bietvf3ut1eg1pkxtcdq.webp`,
    recommended: true,
    topicKeywords: [
      'health',
      'wellness',
      'fitness',
      'medical',
      'body',
    ],
  },
  {
    id: 'topic-politics',
    name: 'Politics & Society',
    coverUrl: `${R2}/migrated/ielts-website/blog/gl1kkt5owtn16hi6mcag.webp`,
    recommended: true,
    topicKeywords: [
      'politics',
      'policy',
      'government',
      'immigration',
      'society',
      'rights',
    ],
  },
  {
    id: 'topic-lifestyle',
    name: 'Lifestyle & Relationships',
    coverUrl: `${R2}/migrated/ielts-website/blog/gm4jykbrtbmfkltghsjg.webp`,
    recommended: true,
    topicKeywords: [
      'lifestyle',
      'relationships',
      'parenting',
      'friendship',
      'dating',
      'family',
    ],
  },
  {
    id: 'topic-environment',
    name: 'Environment & Energy',
    coverUrl: `${R2}/migrated/ielts-website/blog/tbziy30s2lizspn0hzv5.webp`,
    recommended: true,
    topicKeywords: [
      'environment',
      'energy',
      'climate',
      'shipping',
      'urban',
    ],
  },
  {
    id: 'topic-economics',
    name: 'Economics & Business',
    coverUrl: `${R2}/migrated/ielts-website/blog/xnvqgcs2fmgmgoapyudb.webp`,
    recommended: true,
    topicKeywords: [
      'economics',
      'economy',
      'business',
      'finance',
      'labor',
      'tax',
      'market',
      'inequality',
    ],
  },
  {
    id: 'topic-education',
    name: 'Education',
    coverUrl: `${R2}/migrated/ielts-website/blog/cnclpbgeru6dvddve3qr.webp`,
    recommended: true,
    topicKeywords: [
      'education',
      'school',
      'university',
      'student',
      'learning',
      'demographics',
    ],
  },
  {
    id: 'topic-science',
    name: 'Science & Philosophy',
    coverUrl: `${R2}/migrated/ielts-website/blog/rc17jtbg0uf7pfbjnsf9.webp`,
    recommended: true,
    topicKeywords: [
      'science',
      'philosophy',
      'consciousness',
      'religion',
      'physics',
      'neuroscience',
    ],
  },
  {
    id: 'topic-culture',
    name: 'Culture & Media',
    coverUrl: `${R2}/migrated/ielts-website/blog/ugrzi6sqosfusegolypf.webp`,
    recommended: true,
    topicKeywords: [
      'culture',
      'media',
      'social media',
      'sports',
      'art',
      'internet culture',
    ],
  },
  {
    id: 'topic-work',
    name: 'Work & Leadership',
    coverUrl: `${R2}/migrated/ielts-website/blog/omycah7b0tekisdbeasr.webp`,
    recommended: true,
    topicKeywords: [
      'work',
      'productivity',
      'career',
      'leadership',
      'job',
      'corporate',
    ],
  },
  {
    id: 'topic-self-growth',
    name: 'Self-Growth',
    coverUrl: `${R2}/migrated/ielts-website/blog/totdpp4ji6liofxhc3y8.webp`,
    recommended: true,
    topicKeywords: [
      'self-improvement',
      'personal growth',
      'personal development',
      'habits',
      'uncertainty',
      'mindfulness',
      'self-discovery',
    ],
  },
  {
    id: 'topic-history',
    name: 'History & Memory',
    coverUrl: `${R2}/migrated/ielts-website/blog/z0i77zwz3ew4ltbcqzav.webp`,
    recommended: true,
    topicKeywords: [
      'history',
      'memory',
      'nostalgia',
      'past',
      'heritage',
    ],
  },
  {
    id: 'topic-immigration',
    name: 'Immigration & Borders',
    coverUrl: `${R2}/migrated/ielts-website/blog/tqceb3gvwa7ovnbz60tr.webp`,
    recommended: true,
    topicKeywords: [
      'immigration',
      'refugee',
      'border',
      'migrant',
      'ice',
      'asylum',
    ],
  },
  {
    id: 'topic-climate',
    name: 'Climate Crisis',
    coverUrl: `${R2}/migrated/ielts-website/blog/ew7cyjsihu9vvzorwlaj.webp`,
    recommended: true,
    topicKeywords: [
      'climate',
      'warming',
      'carbon',
      'pollution',
      'emissions',
      'environment',
    ],
  },
  {
    id: 'topic-cities',
    name: 'Cities & Housing',
    coverUrl: `${R2}/migrated/ielts-website/blog/cywnw50ybsyiezofm5ns.webp`,
    recommended: true,
    topicKeywords: [
      'travel',
      'city',
      'urban',
      'housing',
      'cities',
      'planning',
    ],
  },
  {
    id: 'topic-security',
    name: 'War & Security',
    coverUrl: `${R2}/migrated/ielts-website/blog/b449xbkndlx55y2ajmtp.webp`,
    recommended: true,
    topicKeywords: [
      'war',
      'conflict',
      'security',
      'crime',
      'military',
      'violence',
    ],
  },
  {
    id: 'topic-habits',
    name: 'Habits & Routines',
    coverUrl: `${R2}/migrated/ielts-website/blog/t4lzksur73zpue1av8gw.webp`,
    recommended: true,
    topicKeywords: [
      'sleep',
      'habit',
      'routine',
      'morning',
      'discipline',
      'daily',
    ],
  },
  {
    id: 'topic-love',
    name: 'Love & Dating',
    coverUrl: `${R2}/migrated/ielts-website/blog/iafctpogntmzdic7tvco.webp`,
    recommended: true,
    topicKeywords: [
      'dating',
      'kissing',
      'love',
      'romance',
      'relationship',
      'partner',
    ],
  },
  {
    id: 'topic-parenting',
    name: 'Parenting & Family',
    coverUrl: `${R2}/migrated/ielts-website/blog/nr08yvqs3a5nttrwjqyp.webp`,
    recommended: true,
    topicKeywords: [
      'parenting',
      'parenthood',
      'child',
      'children',
      'kids',
      'family',
    ],
  },
  {
    id: 'topic-policy',
    name: 'Public Policy',
    coverUrl: `${R2}/migrated/ielts-website/blog/pkbsbgjjmltpcpsfy67n.webp`,
    recommended: true,
    topicKeywords: [
      'public policy',
      'policy',
      'government',
      'tax',
      'regulation',
    ],
  },
  {
    id: 'topic-privacy',
    name: 'Privacy & Data',
    coverUrl: `${R2}/migrated/ielts-website/blog/ndjpvioqdyjezjdtdvdc.webp`,
    recommended: true,
    topicKeywords: [
      'privacy',
      'surveillance',
      'data',
      'algorithm',
      'tracking',
    ],
  },
  {
    id: 'topic-friendship',
    name: 'Friendship & Solitude',
    coverUrl: `${R2}/migrated/ielts-website/blog/lqxgfebaajgeyxsthiug.webp`,
    recommended: true,
    topicKeywords: [
      'friendship',
      'friend',
      'lonely',
      'loneliness',
      'company',
      'solitude',
    ],
  },
  {
    id: 'topic-demographics',
    name: 'Generations',
    coverUrl: `${R2}/migrated/ielts-website/blog/ezdnykju8gclmxxlak0q.webp`,
    recommended: true,
    topicKeywords: [
      'demographics',
      'generation',
      'young people',
      'aging',
      'youth',
      'gen z',
    ],
  },
  {
    id: 'topic-us-affairs',
    name: 'US Affairs',
    coverUrl: `${R2}/migrated/ielts-website/blog/y84gpsrsf60edcgd4rbl.webp`,
    recommended: true,
    topicKeywords: [
      'trump',
      'united states',
      'america',
      'washington',
      'us politics',
      'white house',
    ],
  },
  {
    id: 'topic-sports',
    name: 'Sports & Play',
    coverUrl: `${R2}/migrated/ielts-website/blog/rej9ikx7vz3p4dkwcwsi.webp`,
    recommended: true,
    topicKeywords: [
      'sport',
      'world cup',
      'football',
      'athlete',
      'game',
      'fans',
    ],
  },
  {
    id: 'topic-money',
    name: 'Money & Wealth',
    coverUrl: `${R2}/migrated/ielts-website/blog/lno2820xhfiyl3k8ujwl.webp`,
    recommended: true,
    topicKeywords: [
      'money',
      'lender',
      'debt',
      'wealth',
      'invest',
      'bank',
      'ipo',
    ],
  },
  {
    id: 'topic-neuroscience',
    name: 'Brain & Neuroscience',
    coverUrl: `${R2}/migrated/ielts-website/blog/p7gz3q47dp9mqh04zon0.webp`,
    recommended: true,
    topicKeywords: [
      'neuroscience',
      'brain',
      'cognitive',
      'neural',
      'inner child',
    ],
  },
  {
    id: 'topic-thinking',
    name: 'Ideas & Thinking',
    coverUrl: `${R2}/migrated/ielts-website/blog/rz8jnmxlrvi0qymux2tz.webp`,
    recommended: true,
    topicKeywords: [
      'thought',
      'thinking',
      'original',
      'idea',
      'creativity',
      'mind',
    ],
  },
  {
    id: 'topic-kindness',
    name: 'Kindness & People',
    coverUrl: `${R2}/migrated/ielts-website/blog/poh9um9sfsclpjpcik5h.webp`,
    recommended: true,
    topicKeywords: [
      'kindness',
      'stranger',
      'people',
      'human',
      'compassion',
      'empathy',
    ],
  },
  {
    id: 'topic-nature',
    name: 'Nature & Risk',
    coverUrl: `${R2}/migrated/ielts-website/blog/zkdqnjp4j2xtihicd7ek.webp`,
    recommended: true,
    topicKeywords: [
      'nature',
      'risk',
      'wildlife',
      'biodiversity',
      'ecosystem',
    ],
  },
  {
    id: 'topic-rebuild',
    name: 'Life Change',
    coverUrl: `${R2}/migrated/ielts-website/blog/wzwar1jmvnjsqq5il2v3.webp`,
    recommended: true,
    topicKeywords: [
      'rebuild',
      'life',
      'navigate',
      'change',
      'restart',
      'transform',
    ],
  },
  {
    id: 'topic-media',
    name: 'Media & Reading',
    coverUrl: `${R2}/migrated/ielts-website/blog/bpbganmeou85yccqkdfd.webp`,
    recommended: true,
    topicKeywords: [
      'news',
      'journalism',
      'media',
      'press',
      'reading',
      'book',
    ],
  },
  {
    id: 'topic-global',
    name: 'Global Affairs',
    coverUrl: `${R2}/migrated/ielts-website/blog/wxnikh0fp6ahe37qhnhg.webp`,
    recommended: true,
    topicKeywords: [
      'global',
      'international',
      'world',
      'foreign',
      'diplomacy',
    ],
  },
  {
    id: 'topic-identity',
    name: 'Identity & Self',
    coverUrl: `${R2}/migrated/ielts-website/blog/gpkoa63b1hh8irsx5u8m.webp`,
    recommended: true,
    topicKeywords: [
      'identity',
      'who you are',
      'self',
      'authenticity',
      'introspect',
    ],
  },
  {
    id: 'topic-jobs',
    name: 'Jobs & Graduates',
    coverUrl: `${R2}/migrated/ielts-website/blog/mruqegpxyhxiaiukvwh6.webp`,
    recommended: true,
    topicKeywords: [
      'job',
      'graduate',
      'career',
      'employment',
      'hiring',
      'labor market',
    ],
  },
  {
    id: 'topic-pets',
    name: 'Pets & Animals',
    coverUrl: `${R2}/blog/6e029f76-d0bf-4047-881e-c8b0f4291ea1.webp`,
    recommended: true,
    topicKeywords: [
      'pet',
      'pets',
      'dog',
      'cat',
      'animal',
      'wildlife',
    ],
  },
  {
    id: 'topic-rights',
    name: 'Human Rights',
    coverUrl: `${R2}/migrated/ielts-website/blog/gyu7dg7yltdl5pokgecg.webp`,
    recommended: true,
    topicKeywords: [
      'human rights',
      'rights',
      'freedom',
      'civil',
      'liberty',
    ],
  },
  {
    id: 'topic-ethics',
    name: 'Ethics & Values',
    coverUrl: `${R2}/migrated/ielts-website/blog/hk7zw3mdf3hdlvge79z3.webp`,
    recommended: true,
    topicKeywords: [
      'ethics',
      'moral',
      'values',
      'share',
      'sharing',
    ],
  },
  {
    id: 'topic-space',
    name: 'Space & Future',
    coverUrl: `${R2}/migrated/ielts-website/blog/yecvklt4rarjostrunnk.webp`,
    recommended: true,
    topicKeywords: [
      'space',
      'spacex',
      'future',
      'musk',
      'rocket',
      'mars',
    ],
  },
  {
    id: 'topic-finance',
    name: 'Personal Finance',
    coverUrl: `${R2}/migrated/ielts-website/blog/lbgzdhsgxgkssf9jhvhb.webp`,
    recommended: true,
    topicKeywords: [
      'finance',
      'inflation',
      'prices',
      'personal finance',
      'savings',
      'house prices',
    ],
  },
  {
    id: 'topic-fitness',
    name: 'Fitness & Body',
    coverUrl: `${R2}/migrated/ielts-website/blog/dpfr4vok0zgs2hapzklo.webp`,
    recommended: true,
    topicKeywords: [
      'fitness',
      'exercise',
      'body',
      'neuroplasticity',
      'biological',
      'training',
    ],
  },
  {
    id: 'topic-opinion',
    name: 'Opinion',
    coverUrl: `${R2}/migrated/ielts-website/blog/yqkdibkrndkoefnqq1zh.webp`,
    recommended: true,
    topicKeywords: [
      'opinion',
      'column',
      'essay',
      'commentary',
    ],
  },
  {
    id: 'topic-disease',
    name: 'Disease & Outbreak',
    coverUrl: `${R2}/blog/1e6d2eb0-fd90-4c43-b5f6-8c4886fcdad9.webp`,
    recommended: true,
    topicKeywords: [
      'disease',
      'outbreak',
      'pandemic',
      'virus',
      'public health',
      'trauma',
    ],
  },
  {
    id: 'topic-critical',
    name: 'Critical Thinking',
    coverUrl: `${R2}/blog/c82c2fe3-e0b2-4afa-8fc6-04986036b5ca.webp`,
    recommended: true,
    topicKeywords: [
      'critical thinking',
      'open-minded',
      'bias',
      'reason',
      'argument',
    ],
  },
  {
    id: 'topic-housing',
    name: 'Housing & Homes',
    coverUrl: `${R2}/migrated/ielts-website/blog/ufan4akgyppep7s95oi7.webp`,
    recommended: true,
    topicKeywords: [
      'housing',
      'home',
      'house',
      'rent',
      'single-family',
      'landlord',
    ],
  },
  {
    id: 'topic-trauma',
    name: 'Trauma & Healing',
    coverUrl: `${R2}/blog/a0f9bfaa-f329-44ca-97c3-4fb104924ba4.webp`,
    recommended: true,
    topicKeywords: [
      'trauma',
      'stigma',
      'healing',
      'lgbtq',
      'childhood',
    ],
  },
  {
    id: 'topic-food-history',
    name: 'Food & Tradition',
    coverUrl: `${R2}/migrated/ielts-website/blog/bbjsajs9euna4bqgb9ll.webp`,
    recommended: true,
    topicKeywords: [
      'food',
      'eat',
      'diet',
      'great-grand',
      'tradition',
      'nutrition',
    ],
  },
  {
    id: 'topic-energy',
    name: 'Energy & Trade',
    coverUrl: `${R2}/migrated/ielts-website/blog/pltcm8clmiynbqqk1bcn.webp`,
    recommended: true,
    topicKeywords: [
      'energy',
      'ethanol',
      'corn',
      'cargo',
      'shipping',
      'oil',
    ],
  },
  {
    id: 'topic-ai-mind',
    name: 'AI & Psychology',
    coverUrl: `${R2}/migrated/ielts-website/blog/u40tefxvzq25pjc3ebea.webp`,
    recommended: true,
    topicKeywords: [
      'ai crisis',
      'psychological',
      'artificial intelligence',
      'machine learning',
      'chatgpt',
    ],
  },
  {
    id: 'topic-college',
    name: 'College Life',
    coverUrl: `${R2}/migrated/ielts-website/blog/tyxga9keg6cn0pzq1jnw.webp`,
    recommended: true,
    topicKeywords: [
      'college',
      'university',
      'campus',
      'student life',
      'fun',
    ],
  },
  {
    id: 'topic-abortion',
    name: 'Rights & Choice',
    coverUrl: `${R2}/migrated/ielts-website/blog/d8jlpnpjf7fupcwo1wpl.webp`,
    recommended: true,
    topicKeywords: [
      'abortion',
      'regret',
      'decide',
      'reproductive',
      'choice',
    ],
  },
  {
    id: 'topic-humor',
    name: 'Humor & Satire',
    coverUrl: `${R2}/migrated/ielts-website/blog/kwxyh2i7iztiscot9g4f.webp`,
    recommended: true,
    topicKeywords: [
      'humor',
      'satire',
      'fluffernutter',
      'madman',
      'joke',
      'funny',
    ],
  },
  {
    id: 'topic-sustainability',
    name: 'Sustainability',
    coverUrl: `${R2}/migrated/ielts-website/blog/fzr40pgzw8c9ztkka9ug.webp`,
    recommended: true,
    topicKeywords: [
      'sustainability',
      'sustainable',
      'biodiversity',
      'climate change',
      'green',
    ],
  },
  {
    id: 'topic-motherhood',
    name: 'Motherhood',
    coverUrl: `${R2}/migrated/ielts-website/blog/zmvqclx28awbq1rogykp.webp`,
    recommended: true,
    topicKeywords: [
      'mother',
      'motherhood',
      'yearned',
      'maternity',
      'pregnancy',
    ],
  },
  {
    id: 'topic-foreign-policy',
    name: 'Foreign Policy',
    coverUrl: `${R2}/migrated/ielts-website/blog/m0stxorovuw8kgp6zptm.webp`,
    recommended: true,
    topicKeywords: [
      'foreign policy',
      'international relations',
      'diplomacy',
      'strait',
      'iran',
      'war deal',
    ],
  },
  {
    id: 'topic-crime',
    name: 'Crime & Safety',
    coverUrl: `${R2}/migrated/ielts-website/blog/ofp29e99s91qjfhohu2c.webp`,
    recommended: true,
    topicKeywords: [
      'crime',
      'madman',
      'security',
      'violence',
      'police',
    ],
  },
  {
    id: 'topic-addiction',
    name: 'Addiction & Drugs',
    coverUrl: `${R2}/migrated/ielts-website/blog/ajrngaedahw6ksrg3ftu.webp`,
    recommended: true,
    topicKeywords: [
      'addiction',
      'drug',
      'get high',
      'substance',
      'opioid',
    ],
  },
  {
    id: 'topic-outbreaks',
    name: 'Virus Outbreaks',
    coverUrl: `${R2}/migrated/ielts-website/blog/pxk4bcgvpjmq52gm8nhp.webp`,
    recommended: true,
    topicKeywords: [
      'ebola',
      'hantavirus',
      'outbreak',
      'virus',
      'epidemic',
    ],
  },
  {
    id: 'topic-sleep-health',
    name: 'Sleep & Cancer Risk',
    coverUrl: `${R2}/migrated/ielts-website/blog/yddtrshhttbzkmi2hfb5.webp`,
    recommended: true,
    topicKeywords: [
      'sleep',
      'cancer',
      'insomnia',
      'poor sleep',
      'rest',
    ],
  },
  {
    id: 'topic-body-image',
    name: 'Body Image',
    coverUrl: `${R2}/migrated/ielts-website/blog/jfzkrxhsfccl1xtooihe.webp`,
    recommended: true,
    topicKeywords: [
      'dysmorphic',
      'body image',
      'looks',
      'appearance',
      'beauty',
    ],
  },
  {
    id: 'topic-carbon',
    name: 'Carbon & Climate Roots',
    coverUrl: `${R2}/migrated/ielts-website/blog/vjafwaxmhptobckt6xxt.webp`,
    recommended: true,
    topicKeywords: [
      'carbon',
      'roots',
      'climate',
      'emissions',
      'net zero',
    ],
  },
  {
    id: 'topic-looksmaxxing',
    name: 'Looksmaxxing & Online Life',
    coverUrl: `${R2}/migrated/ielts-website/blog/wn4jwygueqtqjxsxvngj.webp`,
    recommended: true,
    topicKeywords: [
      'looksmaxxing',
      'online',
      'internet culture',
      'social media',
      'influencer',
    ],
  },
  {
    id: 'topic-mini-retire',
    name: 'Mini-Retirements',
    coverUrl: `${R2}/migrated/ielts-website/blog/hwm7u274ttjkpctds4cc.webp`,
    recommended: true,
    topicKeywords: [
      'mini-retire',
      'retirement',
      'sabbatical',
      'burnout',
      'time off',
    ],
  },
  {
    id: 'topic-time-mgmt',
    name: 'Time Management',
    coverUrl: `${R2}/migrated/ielts-website/blog/ekpf3wae0qehefqagypd.webp`,
    recommended: true,
    topicKeywords: [
      'hours',
      'manage time',
      'time management',
      'productivity',
      'slip away',
    ],
  },
  {
    id: 'topic-closure',
    name: 'Closure & Relationships',
    coverUrl: `${R2}/migrated/ielts-website/blog/riljulmbzhtrqfd6ayge.webp`,
    recommended: true,
    topicKeywords: [
      'closure',
      'hope',
      'breakup',
      'relationship end',
      'goodbye',
    ],
  },
  {
    id: 'topic-aging',
    name: 'Aging Well',
    coverUrl: `${R2}/migrated/ielts-website/blog/tsld4ywxeeje471fybgx.webp`,
    recommended: true,
    topicKeywords: [
      'old',
      'aging',
      'ageing',
      'elderly',
      'longevity',
    ],
  },
  {
    id: 'topic-psychiatry',
    name: 'Psychiatry',
    coverUrl: `${R2}/migrated/ielts-website/blog/gfxjqkztej4hqeaorjzs.webp`,
    recommended: true,
    topicKeywords: [
      'psychiatrist',
      'psychiatry',
      'diagnosis',
      'mental illness',
      'therapy',
    ],
  },
  {
    id: 'topic-env-movement',
    name: 'Environmental Movement',
    coverUrl: `${R2}/migrated/ielts-website/blog/azrrijgpfquyvbtmwegd.webp`,
    recommended: true,
    topicKeywords: [
      'environmental movement',
      'activism',
      'green movement',
      'lost its power',
      'climate activism',
    ],
  },
  {
    id: 'topic-grief',
    name: 'Grief & Loss',
    coverUrl: `${R2}/blog/a834cb35-07b5-4d2b-90ee-8c894fae7880.webp`,
    recommended: true,
    topicKeywords: [
      'grief',
      'loss',
      'mourning',
      'bereavement',
      'sadness',
    ],
  },
  {
    id: 'topic-enrollment',
    name: 'College Enrollment',
    coverUrl: `${R2}/migrated/ielts-website/blog/fpykq1it0f6qs1dtdrnz.webp`,
    recommended: true,
    topicKeywords: [
      'enrollment',
      'college enrollment',
      'death spiral',
      'admissions',
      'campus crisis',
    ],
  },
  {
    id: 'topic-charisma',
    name: 'Charismatic Leaders',
    coverUrl: `${R2}/blog/175f3a9a-0bcb-46bc-a2ea-8ce7fdfe05a7.webp`,
    recommended: true,
    topicKeywords: [
      'charismatic',
      'charisma',
      'leader',
      'leadership cult',
      'obsession',
    ],
  },
  {
    id: 'topic-partners',
    name: 'Finding a Partner',
    coverUrl: `${R2}/migrated/ielts-website/blog/klggcixpcsrfumoil7an.webp`,
    recommended: true,
    topicKeywords: [
      'conquer the world',
      'partner',
      'finding someone',
      'soulmate',
      'dating partner',
    ],
  },
  {
    id: 'topic-tech-giants',
    name: 'Big Tech Power',
    coverUrl: `${R2}/migrated/ielts-website/blog/wbnrmgqb3oj2fqshfham.webp`,
    recommended: true,
    topicKeywords: [
      'apple',
      'runs apple',
      'tech giant',
      'big tech',
      'silicon valley',
    ],
  },
  {
    id: 'topic-treasuries',
    name: 'US Treasuries',
    coverUrl: `${R2}/migrated/ielts-website/blog/s2me7av4pdqjfmxqvidb.webp`,
    recommended: true,
    topicKeywords: [
      'treasuries',
      'treasury',
      'bond',
      'inflation challenges',
      'safe haven',
    ],
  },
  {
    id: 'topic-democrats',
    name: 'Democratic Politics',
    coverUrl: `${R2}/migrated/ielts-website/blog/st9o7zgwi229fcehr815.webp`,
    recommended: true,
    topicKeywords: [
      'democratic',
      'democrat',
      'politicians',
      'left wing',
      'liberal',
    ],
  },
  {
    id: 'topic-ai-bubble',
    name: 'AI Bubble',
    coverUrl: `${R2}/migrated/ielts-website/blog/ilfrag99wz7ieixkbrce.webp`,
    recommended: true,
    topicKeywords: [
      'ai bubble',
      'bubble',
      'hype',
      'ai market',
      'overvalued',
    ],
  },
  {
    id: 'topic-moral-code',
    name: 'America’s Moral Code',
    coverUrl: `${R2}/migrated/ielts-website/blog/gnqvcsfdnqxtow8cuvuf.webp`,
    recommended: true,
    topicKeywords: [
      'moral code',
      'morality',
      'america',
      'values crisis',
      'ethics america',
    ],
  },
  {
    id: 'topic-expectations',
    name: 'Expectations',
    coverUrl: `${R2}/migrated/ielts-website/blog/kwqeaowkngjvouwy8z2s.webp`,
    recommended: true,
    topicKeywords: [
      'expect',
      'expectation',
      'expecting',
      'anticipate',
    ],
  },
  {
    id: 'topic-nature-common',
    name: 'Nature & Humans',
    coverUrl: `${R2}/migrated/ielts-website/blog/flho13nsteyhbwsk1elj.webp`,
    recommended: true,
    topicKeywords: [
      'pigeon',
      'animal behavior',
      'nature',
      'wildlife',
      'species',
    ],
  },
  {
    id: 'topic-ugly-thoughts',
    name: 'Ugly Thoughts',
    coverUrl: `${R2}/migrated/ielts-website/blog/ac6zogze5r2a9nt9rojr.webp`,
    recommended: true,
    topicKeywords: [
      'ugly thoughts',
      'ugly',
      'self-image',
      'inner critic',
      'shame',
    ],
  },
  {
    id: 'topic-smart-crime',
    name: 'Smart Crime',
    coverUrl: `${R2}/migrated/ielts-website/blog/uagvfh3ouivq03xte95u.webp`,
    recommended: true,
    topicKeywords: [
      'curb crime',
      'crime',
      'theft',
      'progressive chic',
      'policing',
    ],
  },
  {
    id: 'topic-gun-violence',
    name: 'Gun Violence',
    coverUrl: `${R2}/migrated/ielts-website/blog/hy9wn2xrhostm8to9u7e.webp`,
    recommended: true,
    topicKeywords: [
      'shooter',
      'gun',
      'firearm',
      'mass shooting',
      'violence',
    ],
  },
  {
    id: 'topic-ev',
    name: 'Electric Vehicles',
    coverUrl: `${R2}/migrated/ielts-website/blog/mnvqftdv3jaw46avpwee.webp`,
    recommended: true,
    topicKeywords: [
      'electric vehicle',
      'ev',
      'tesla',
      'battery',
      'charging',
    ],
  },
]

const SOURCE_ALIASES: Record<string, BilingualSourceId> = {
  'the-atlantic': 'the-atlantic',
  atlantic: 'the-atlantic',
  'the-new-york-times': 'the-new-york-times',
  'new-york-times': 'the-new-york-times',
  nyt: 'the-new-york-times',
  reuters: 'reuters',
  substack: 'substack',
  subtack: 'substack',
  'the-conversation': 'the-conversation',
  conversation: 'the-conversation',
  'the-guardian': 'the-guardian',
  guardian: 'the-guardian',
  'topic-psychology': 'topic-psychology',
  psychology: 'topic-psychology',
  'topic-technology': 'topic-technology',
  technology: 'topic-technology',
  tech: 'topic-technology',
  ai: 'topic-technology',
  'topic-health': 'topic-health',
  health: 'topic-health',
  'topic-politics': 'topic-politics',
  politics: 'topic-politics',
  'topic-lifestyle': 'topic-lifestyle',
  lifestyle: 'topic-lifestyle',
  'topic-environment': 'topic-environment',
  environment: 'topic-environment',
  'topic-economics': 'topic-economics',
  economics: 'topic-economics',
  business: 'topic-economics',
  'topic-education': 'topic-education',
  education: 'topic-education',
  'topic-science': 'topic-science',
  science: 'topic-science',
  philosophy: 'topic-science',
  'topic-culture': 'topic-culture',
  culture: 'topic-culture',
  'topic-work': 'topic-work',
  work: 'topic-work',
  productivity: 'topic-work',
  'topic-self-growth': 'topic-self-growth',
  growth: 'topic-self-growth',
  'self-growth': 'topic-self-growth',
  'topic-history': 'topic-history',
  history: 'topic-history',
  memory: 'topic-history',
  'topic-immigration': 'topic-immigration',
  immigration: 'topic-immigration',
  'topic-climate': 'topic-climate',
  climate: 'topic-climate',
  'topic-cities': 'topic-cities',
  cities: 'topic-cities',
  'topic-security': 'topic-security',
  security: 'topic-security',
  war: 'topic-security',
  'topic-habits': 'topic-habits',
  habits: 'topic-habits',
  sleep: 'topic-habits',
  'topic-love': 'topic-love',
  love: 'topic-love',
  dating: 'topic-love',
  'topic-parenting': 'topic-parenting',
  parenting: 'topic-parenting',
  'topic-policy': 'topic-policy',
  policy: 'topic-policy',
  'topic-privacy': 'topic-privacy',
  privacy: 'topic-privacy',
  'topic-friendship': 'topic-friendship',
  friendship: 'topic-friendship',
  'topic-demographics': 'topic-demographics',
  generations: 'topic-demographics',
  demographics: 'topic-demographics',
  'topic-us-affairs': 'topic-us-affairs',
  'us-affairs': 'topic-us-affairs',
  'topic-sports': 'topic-sports',
  sports: 'topic-sports',
  'topic-money': 'topic-money',
  money: 'topic-money',
  'topic-neuroscience': 'topic-neuroscience',
  neuroscience: 'topic-neuroscience',
  brain: 'topic-neuroscience',
  'topic-thinking': 'topic-thinking',
  thinking: 'topic-thinking',
  'topic-kindness': 'topic-kindness',
  kindness: 'topic-kindness',
  'topic-nature': 'topic-nature',
  nature: 'topic-nature',
  'topic-rebuild': 'topic-rebuild',
  rebuild: 'topic-rebuild',
  'life-change': 'topic-rebuild',
  'topic-media': 'topic-media',
  media: 'topic-media',
  reading: 'topic-media',
  'topic-global': 'topic-global',
  global: 'topic-global',
  'topic-identity': 'topic-identity',
  identity: 'topic-identity',
  'topic-jobs': 'topic-jobs',
  jobs: 'topic-jobs',
  graduates: 'topic-jobs',
  'topic-pets': 'topic-pets',
  pets: 'topic-pets',
  animals: 'topic-pets',
  'topic-rights': 'topic-rights',
  rights: 'topic-rights',
  'human-rights': 'topic-rights',
  'topic-ethics': 'topic-ethics',
  ethics: 'topic-ethics',
  'topic-space': 'topic-space',
  space: 'topic-space',
  'topic-finance': 'topic-finance',
  finance: 'topic-finance',
  'topic-fitness': 'topic-fitness',
  fitness: 'topic-fitness',
  'topic-opinion': 'topic-opinion',
  opinion: 'topic-opinion',
  'topic-disease': 'topic-disease',
  disease: 'topic-disease',
  outbreak: 'topic-disease',
  'topic-critical': 'topic-critical',
  'critical-thinking': 'topic-critical',
  'topic-housing': 'topic-housing',
  housing: 'topic-housing',
  homes: 'topic-housing',
  'topic-trauma': 'topic-trauma',
  trauma: 'topic-trauma',
  'topic-food-history': 'topic-food-history',
  food: 'topic-food-history',
  tradition: 'topic-food-history',
  'topic-energy': 'topic-energy',
  energy: 'topic-energy',
  'topic-ai-mind': 'topic-ai-mind',
  'ai-psychology': 'topic-ai-mind',
  'topic-college': 'topic-college',
  college: 'topic-college',
  'topic-abortion': 'topic-abortion',
  choice: 'topic-abortion',
  'topic-humor': 'topic-humor',
  humor: 'topic-humor',
  'topic-sustainability': 'topic-sustainability',
  sustainability: 'topic-sustainability',
  'topic-motherhood': 'topic-motherhood',
  motherhood: 'topic-motherhood',
  'topic-foreign-policy': 'topic-foreign-policy',
  'foreign-policy': 'topic-foreign-policy',
  'topic-crime': 'topic-crime',
  crime: 'topic-crime',
  'topic-addiction': 'topic-addiction',
  addiction: 'topic-addiction',
  'topic-outbreaks': 'topic-outbreaks',
  outbreaks: 'topic-outbreaks',
  'topic-sleep-health': 'topic-sleep-health',
  'sleep-health': 'topic-sleep-health',
  'topic-body-image': 'topic-body-image',
  'body-image': 'topic-body-image',
  'topic-carbon': 'topic-carbon',
  carbon: 'topic-carbon',
  'topic-looksmaxxing': 'topic-looksmaxxing',
  looksmaxxing: 'topic-looksmaxxing',
  'topic-mini-retire': 'topic-mini-retire',
  'mini-retire': 'topic-mini-retire',
  'topic-time-mgmt': 'topic-time-mgmt',
  'time-management': 'topic-time-mgmt',
  'topic-closure': 'topic-closure',
  closure: 'topic-closure',
  'topic-aging': 'topic-aging',
  aging: 'topic-aging',
  'topic-psychiatry': 'topic-psychiatry',
  psychiatry: 'topic-psychiatry',
  'topic-env-movement': 'topic-env-movement',
  'env-movement': 'topic-env-movement',
  'topic-grief': 'topic-grief',
  grief: 'topic-grief',
  'topic-enrollment': 'topic-enrollment',
  enrollment: 'topic-enrollment',
  'topic-charisma': 'topic-charisma',
  charisma: 'topic-charisma',
  'topic-partners': 'topic-partners',
  partners: 'topic-partners',
  'topic-tech-giants': 'topic-tech-giants',
  'tech-giants': 'topic-tech-giants',
  'topic-treasuries': 'topic-treasuries',
  treasuries: 'topic-treasuries',
  'topic-democrats': 'topic-democrats',
  democrats: 'topic-democrats',
  'topic-ai-bubble': 'topic-ai-bubble',
  'ai-bubble': 'topic-ai-bubble',
  'topic-moral-code': 'topic-moral-code',
  'moral-code': 'topic-moral-code',
  'topic-expectations': 'topic-expectations',
  expectations: 'topic-expectations',
  'topic-nature-common': 'topic-nature-common',
  'nature-humans': 'topic-nature-common',
  'topic-ugly-thoughts': 'topic-ugly-thoughts',
  'ugly-thoughts': 'topic-ugly-thoughts',
  'topic-smart-crime': 'topic-smart-crime',
  'smart-crime': 'topic-smart-crime',
  'topic-gun-violence': 'topic-gun-violence',
  'gun-violence': 'topic-gun-violence',
  'topic-ev': 'topic-ev',
  ev: 'topic-ev',
  'electric-vehicles': 'topic-ev',
}

export function normalizeSourceId(raw: string | null | undefined): BilingualSourceId | null {
  if (!raw) return null
  return SOURCE_ALIASES[raw.trim().toLowerCase()] ?? null
}

export function getSource(id: BilingualSourceId): BilingualSource | undefined {
  return BILINGUAL_SOURCES.find(s => s.id === id)
}

export function getAllArticles(): BilingualArticle[] {
  return ALL
}

function articleMatchesTopic(a: BilingualArticle, keywords: string[]): boolean {
  const hay = `${a.category || ''} ${a.category_vi || ''} ${a.title || ''} ${a.title_vi || ''}`.toLowerCase()
  return keywords.some(k => {
    const key = k.toLowerCase()
    if (key === 'ai') {
      // avoid matching inside words like "said" — match whole token-ish
      return /\bai\b/.test(hay) || hay.includes('artificial intelligence')
    }
    return hay.includes(key)
  })
}

export function getArticlesBySource(
  sourceId: BilingualSourceId,
  sort: 'newest' | 'popular' = 'newest',
): BilingualArticle[] {
  const source = getSource(sourceId)
  let list: BilingualArticle[]
  if (source?.topicKeywords?.length) {
    list = ALL.filter(a => articleMatchesTopic(a, source.topicKeywords!))
  } else {
    list = ALL.filter(a => a.source_id === sourceId)
  }
  if (sort === 'popular') {
    return [...list].sort((a, b) => (b.view_count || 0) - (a.view_count || 0))
  }
  return list
}

export function getArticleById(id: string): BilingualArticle | undefined {
  return ALL.find(a => a.id === id)
}

export function formatViews(n: number): string {
  if (n >= 1000) {
    const k = n / 1000
    return `${k >= 10 ? Math.round(k) : k.toFixed(1).replace(/\.0$/, '')}K`
  }
  return String(n)
}

export function toMeta(a: BilingualArticle) {
  const { content: _c, ...meta } = a
  return meta
}

const IMG_RE = /^\[IMG:(.+)\]$/

export function parseBlockText(raw: string): {
  type: 'img' | 'text'
  value: string
  bold?: boolean
} {
  const m = raw.trim().match(IMG_RE)
  if (m) return { type: 'img', value: m[1]! }
  const bold = raw.includes('**')
  return { type: 'text', value: raw.replace(/\*\*/g, ''), bold }
}

export const BAO_BASE = '/app/reading-corner/bao'
