// AUTO-GENERATED by scripts/build-catalog.mjs — do not edit

import ieltsReadingCam9Test1 from '../data/reading-ielts-cam9-test1.json'
import ieltsReadingCam9Test2 from '../data/reading-ielts-cam9-test2.json'
import ieltsReadingCam9Test3 from '../data/reading-ielts-cam9-test3.json'
import ieltsReadingCam9Test4 from '../data/reading-ielts-cam9-test4.json'
import ieltsReadingCam10Test1 from '../data/reading-ielts-cam10-test1.json'
import ieltsReadingCam10Test2 from '../data/reading-ielts-cam10-test2.json'
import ieltsReadingCam10Test3 from '../data/reading-ielts-cam10-test3.json'
import ieltsReadingCam10Test4 from '../data/reading-ielts-cam10-test4.json'
import ieltsReadingCam11Test1 from '../data/reading-ielts-cam11-test1.json'
import ieltsReadingCam11Test3 from '../data/reading-ielts-cam11-test3.json'
import ieltsReadingCam11Test4 from '../data/reading-ielts-cam11-test4.json'
import ieltsReadingCam12Test1 from '../data/reading-ielts-cam12-test1.json'
import ieltsReadingCam12Test2 from '../data/reading-ielts-cam12-test2.json'
import ieltsReadingCam12Test3 from '../data/reading-ielts-cam12-test3.json'
import ieltsReadingCam12Test4 from '../data/reading-ielts-cam12-test4.json'
import ieltsReadingCam13Test1 from '../data/reading-ielts-cam13-test1.json'
import ieltsReadingCam13Test2 from '../data/reading-ielts-cam13-test2.json'
import ieltsReadingCam13Test3 from '../data/reading-ielts-cam13-test3.json'
import ieltsReadingCam13Test4 from '../data/reading-ielts-cam13-test4.json'
import ieltsReadingCam14Test1 from '../data/reading-ielts-cam14-test1.json'
import ieltsReadingCam14Test2 from '../data/reading-ielts-cam14-test2.json'
import ieltsReadingCam14Test3 from '../data/reading-ielts-cam14-test3.json'
import ieltsReadingCam14Test4 from '../data/reading-ielts-cam14-test4.json'
import ieltsReadingCam15Test1 from '../data/reading-ielts-cam15-test1.json'
import ieltsReadingCam15Test2 from '../data/reading-ielts-cam15-test2.json'
import ieltsReadingCam15Test3 from '../data/reading-ielts-cam15-test3.json'
import ieltsReadingCam15Test4 from '../data/reading-ielts-cam15-test4.json'
import ieltsReadingCam16Test1 from '../data/reading-ielts-cam16-test1.json'
import ieltsReadingCam16Test2 from '../data/reading-ielts-cam16-test2.json'
import ieltsReadingCam16Test3 from '../data/reading-ielts-cam16-test3.json'
import ieltsReadingCam16Test4 from '../data/reading-ielts-cam16-test4.json'
import ieltsReadingCam17Test1 from '../data/reading-ielts-cam17-test1.json'
import ieltsReadingCam17Test2 from '../data/reading-ielts-cam17-test2.json'
import ieltsReadingCam17Test3 from '../data/reading-ielts-cam17-test3.json'
import ieltsReadingCam17Test4 from '../data/reading-ielts-cam17-test4.json'
import ieltsReadingCam18Test1 from '../data/reading-ielts-cam18-test1.json'
import ieltsReadingCam18Test2 from '../data/reading-ielts-cam18-test2.json'
import ieltsReadingCam18Test3 from '../data/reading-ielts-cam18-test3.json'
import ieltsReadingCam18Test4 from '../data/reading-ielts-cam18-test4.json'
import ieltsReadingCam19Test1 from '../data/reading-ielts-cam19-test1.json'
import ieltsReadingCam19Test2 from '../data/reading-ielts-cam19-test2.json'
import ieltsReadingCam19Test3 from '../data/reading-ielts-cam19-test3.json'
import ieltsReadingCam19Test4 from '../data/reading-ielts-cam19-test4.json'
import ieltsReadingCam20Test1 from '../data/reading-ielts-cam20-test1.json'
import ieltsReadingCam20Test2 from '../data/reading-ielts-cam20-test2.json'
import ieltsReadingCam20Test3 from '../data/reading-ielts-cam20-test3.json'
import ieltsReadingCam20Test4 from '../data/reading-ielts-cam20-test4.json'

export const GENERATED_IELTS_READING_EXAMS = [
  ieltsReadingCam9Test1,
  ieltsReadingCam9Test2,
  ieltsReadingCam9Test3,
  ieltsReadingCam9Test4,
  ieltsReadingCam10Test1,
  ieltsReadingCam10Test2,
  ieltsReadingCam10Test3,
  ieltsReadingCam10Test4,
  ieltsReadingCam11Test1,
  ieltsReadingCam11Test3,
  ieltsReadingCam11Test4,
  ieltsReadingCam12Test1,
  ieltsReadingCam12Test2,
  ieltsReadingCam12Test3,
  ieltsReadingCam12Test4,
  ieltsReadingCam13Test1,
  ieltsReadingCam13Test2,
  ieltsReadingCam13Test3,
  ieltsReadingCam13Test4,
  ieltsReadingCam14Test1,
  ieltsReadingCam14Test2,
  ieltsReadingCam14Test3,
  ieltsReadingCam14Test4,
  ieltsReadingCam15Test1,
  ieltsReadingCam15Test2,
  ieltsReadingCam15Test3,
  ieltsReadingCam15Test4,
  ieltsReadingCam16Test1,
  ieltsReadingCam16Test2,
  ieltsReadingCam16Test3,
  ieltsReadingCam16Test4,
  ieltsReadingCam17Test1,
  ieltsReadingCam17Test2,
  ieltsReadingCam17Test3,
  ieltsReadingCam17Test4,
  ieltsReadingCam18Test1,
  ieltsReadingCam18Test2,
  ieltsReadingCam18Test3,
  ieltsReadingCam18Test4,
  ieltsReadingCam19Test1,
  ieltsReadingCam19Test2,
  ieltsReadingCam19Test3,
  ieltsReadingCam19Test4,
  ieltsReadingCam20Test1,
  ieltsReadingCam20Test2,
  ieltsReadingCam20Test3,
  ieltsReadingCam20Test4,
]
