// AUTO-GENERATED by scripts/build-catalog.mjs — do not edit

import ieltsCam9Test1 from '../data/listening-ielts-cam9-test1.json'
import ieltsCam9Test2 from '../data/listening-ielts-cam9-test2.json'
import ieltsCam9Test3 from '../data/listening-ielts-cam9-test3.json'
import ieltsCam9Test4 from '../data/listening-ielts-cam9-test4.json'
import ieltsCam10Test1 from '../data/listening-ielts-cam10-test1.json'
import ieltsCam10Test2 from '../data/listening-ielts-cam10-test2.json'
import ieltsCam10Test3 from '../data/listening-ielts-cam10-test3.json'
import ieltsCam10Test4 from '../data/listening-ielts-cam10-test4.json'
import ieltsCam11Test1 from '../data/listening-ielts-cam11-test1.json'
import ieltsCam11Test2 from '../data/listening-ielts-cam11-test2.json'
import ieltsCam11Test3 from '../data/listening-ielts-cam11-test3.json'
import ieltsCam11Test4 from '../data/listening-ielts-cam11-test4.json'
import ieltsCam12Test1 from '../data/listening-ielts-cam12-test1.json'
import ieltsCam12Test2 from '../data/listening-ielts-cam12-test2.json'
import ieltsCam12Test3 from '../data/listening-ielts-cam12-test3.json'
import ieltsCam12Test4 from '../data/listening-ielts-cam12-test4.json'
import ieltsCam13Test1 from '../data/listening-ielts-cam13-test1.json'
import ieltsCam13Test2 from '../data/listening-ielts-cam13-test2.json'
import ieltsCam13Test3 from '../data/listening-ielts-cam13-test3.json'
import ieltsCam13Test4 from '../data/listening-ielts-cam13-test4.json'
import ieltsCam14Test1 from '../data/listening-ielts-cam14-test1.json'
import ieltsCam14Test2 from '../data/listening-ielts-cam14-test2.json'
import ieltsCam14Test3 from '../data/listening-ielts-cam14-test3.json'
import ieltsCam14Test4 from '../data/listening-ielts-cam14-test4.json'
import ieltsCam15Test1 from '../data/listening-ielts-cam15-test1.json'
import ieltsCam15Test2 from '../data/listening-ielts-cam15-test2.json'
import ieltsCam15Test3 from '../data/listening-ielts-cam15-test3.json'
import ieltsCam15Test4 from '../data/listening-ielts-cam15-test4.json'
import ieltsCam16Test1 from '../data/listening-ielts-cam16-test1.json'
import ieltsCam16Test2 from '../data/listening-ielts-cam16-test2.json'
import ieltsCam16Test3 from '../data/listening-ielts-cam16-test3.json'
import ieltsCam16Test4 from '../data/listening-ielts-cam16-test4.json'
import ieltsCam17Test1 from '../data/listening-ielts-cam17-test1.json'
import ieltsCam17Test2 from '../data/listening-ielts-cam17-test2.json'
import ieltsCam17Test3 from '../data/listening-ielts-cam17-test3.json'
import ieltsCam17Test4 from '../data/listening-ielts-cam17-test4.json'
import ieltsCam18Test1 from '../data/listening-ielts-cam18-test1.json'
import ieltsCam18Test2 from '../data/listening-ielts-cam18-test2.json'
import ieltsCam18Test3 from '../data/listening-ielts-cam18-test3.json'
import ieltsCam18Test4 from '../data/listening-ielts-cam18-test4.json'
import ieltsCam19Test1 from '../data/listening-ielts-cam19-test1.json'
import ieltsCam19Test2 from '../data/listening-ielts-cam19-test2.json'
import ieltsCam19Test3 from '../data/listening-ielts-cam19-test3.json'
import ieltsCam19Test4 from '../data/listening-ielts-cam19-test4.json'
import ieltsCam20Test1 from '../data/listening-ielts-cam20-test1.json'
import ieltsCam20Test2 from '../data/listening-ielts-cam20-test2.json'
import ieltsCam20Test3 from '../data/listening-ielts-cam20-test3.json'
import ieltsCam20Test4 from '../data/listening-ielts-cam20-test4.json'

export const GENERATED_IELTS_LISTENING_EXAMS = [
  ieltsCam9Test1,
  ieltsCam9Test2,
  ieltsCam9Test3,
  ieltsCam9Test4,
  ieltsCam10Test1,
  ieltsCam10Test2,
  ieltsCam10Test3,
  ieltsCam10Test4,
  ieltsCam11Test1,
  ieltsCam11Test2,
  ieltsCam11Test3,
  ieltsCam11Test4,
  ieltsCam12Test1,
  ieltsCam12Test2,
  ieltsCam12Test3,
  ieltsCam12Test4,
  ieltsCam13Test1,
  ieltsCam13Test2,
  ieltsCam13Test3,
  ieltsCam13Test4,
  ieltsCam14Test1,
  ieltsCam14Test2,
  ieltsCam14Test3,
  ieltsCam14Test4,
  ieltsCam15Test1,
  ieltsCam15Test2,
  ieltsCam15Test3,
  ieltsCam15Test4,
  ieltsCam16Test1,
  ieltsCam16Test2,
  ieltsCam16Test3,
  ieltsCam16Test4,
  ieltsCam17Test1,
  ieltsCam17Test2,
  ieltsCam17Test3,
  ieltsCam17Test4,
  ieltsCam18Test1,
  ieltsCam18Test2,
  ieltsCam18Test3,
  ieltsCam18Test4,
  ieltsCam19Test1,
  ieltsCam19Test2,
  ieltsCam19Test3,
  ieltsCam19Test4,
  ieltsCam20Test1,
  ieltsCam20Test2,
  ieltsCam20Test3,
  ieltsCam20Test4,
]
