#DictionaryForMIDs property file
#Sat Sep 30 00:21:06 PDT 2006
indexFileMaxSize=20574
infoText=English-Vietnamese dictionary (110k) setup by VuVanQuynh email\: quynh2003hp@yahoo.com
language1IndexNumberOfSourceEntries=104999
language1DictionaryUpdateClassName=de.kugihan.dictionaryformids.dictgen.DictionaryUpdateEngDef
indexCharEncoding=UTF-8
dictionaryFileSeparationCharacter='\t'
language2NormationClassName=de.kugihan.dictionaryformids.translation.NormationVie
language2DictionaryUpdateClassName=de.kugihan.dictionaryformids.dictgen.DictionaryUpdateEngDef
language1FilePostfix=Eng
dictionaryCharEncoding=UTF-8
numberOfAvailableLanguages=2
language1IsSearchable=true
language2GenerateIndex=false
dictionaryFileMaxSize=47250
language2FilePostfix=Vie
searchListFileMaxSize=3120
language2IsSearchable=false
dictionaryGenerationLanguage1ExpressionSplitString=,
fileEncodingFormat=plain_format1
language1HasSeparateDictionaryFile=true
dictionaryGenerationLanguage1ExpressionSplitString=,
searchListCharEncoding=UTF-8
searchListFileSeparationCharacter='\t'
indexFileSeparationCharacter='\t'
language1DisplayText=English
language2HasSeparateDictionaryFile=true
dictionaryGenerationInputCharEncoding=UTF-8
language2DisplayText=Ti\u1EBFng Vi\u1EC7t
language1GenerateIndex=true
language1NormationClassName=de.kugihan.dictionaryformids.translation.NormationEng2
language1NumberOfContentDeclarations=4
language1Content01DisplayText= loai tu
language1Content01FontStyle=plain
language1Content01FontColour = 0,0,255
language1Content01SelectionMode = none
language1Content02DisplayText= tieng mot
language1Content02FontStyle= plain
language1Content02FontColour = 255,0,0
language1Content02SelectionMode = none
language1Content03DisplayText= vi du
language1Content03FontStyle= plain
language1Content03FontColour = 255,0,0
language1Content03SelectionMode = none
language1Content04DisplayText= tu mo rong
language1Content04FontStyle= underlined
language1Content04FontColour = 255,0,0
language1Content04SelectionMode = none
language2NumberOfContentDeclarations=4
language2Content01DisplayText= loai tu
language2Content01FontStyle=plain
language2Content01FontColour = 0,0,255
language2Content01SelectionMode = none
language2Content02DisplayText= tieng mot
language2Content02FontStyle= plain
language2Content02FontColour = 255,0,0
language2Content02SelectionMode = single
language2Content03DisplayText= vi du
language2Content03FontStyle= plain
language2Content03FontColour = 255,0,0
language2Content03SelectionMode = all
language2Content04DisplayText= tu mo rong
language2Content04FontStyle= underlined
language2Content04FontColour = 255,0,0
language2Content04SelectionMode = single
