/**
 * Build global catalog from Tainguyen/ bundles.
 * - Copies media → apps/web/public/catalog/
 * - Emits processed exam JSON → packages/catalog/data/
 *
 * Run: node scripts/build-catalog.mjs
 */
import { existsSync } from 'node:fs'
import { spawnSync } from 'node:child_process'
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const TAINGUYEN = path.join(ROOT, 'Tainguyen')
const PUBLIC_CATALOG = path.join(ROOT, 'apps/web/public/catalog')
const DATA_OUT = path.join(ROOT, 'packages/catalog/data')

const STATIC_BUNDLES = [
  {
    kind: 'reading',
    slug: 'ket-a2-test1',
    examId: 'catalog-reading-ket-a2-test1',
    sourceDir: 'ket-reading-test1',
    cambridgeLevel: 'a2',
    examTrack: 'cambridge',
  },
  {
    kind: 'reading',
    slug: 'pet-b1-test1',
    examId: 'catalog-reading-pet-b1-test1',
    sourceDir: 'pet-reading-test1',
    cambridgeLevel: 'b1',
    examTrack: 'cambridge',
  },
  {
    kind: 'reading',
    slug: 'fce-b2-test1',
    examId: 'catalog-reading-fce-b2-test1',
    sourceDir: 'fce-reading-test1',
    cambridgeLevel: 'b2',
    examTrack: 'cambridge',
  },
  {
    kind: 'reading',
    slug: 'cae-c1-test1',
    examId: 'catalog-reading-cae-c1-test1',
    sourceDir: 'cae-Reading-test1',
    cambridgeLevel: 'c1',
    examTrack: 'cambridge',
  },
  {
    kind: 'reading',
    slug: 'cpe-c2-test1',
    examId: 'catalog-reading-cpe-c2-test1',
    sourceDir: 'cpe-Reading-test1',
    cambridgeLevel: 'c2',
    examTrack: 'cambridge',
  },
  {
    kind: 'listening',
    slug: 'ket-a2-test1',
    examId: 'catalog-listening-ket-a2-test1',
    sourceDir: 'ket-listening-test1',
    examType: 'ket',
    examMode: 'practice',
  },
  {
    kind: 'listening',
    slug: 'pet-b1-test1',
    examId: 'catalog-listening-pet-b1-test1',
    sourceDir: 'pet-listening-test1',
    examType: 'pet',
    examMode: 'practice',
  },
  {
    kind: 'listening',
    slug: 'fce-b2-test1',
    examId: 'catalog-listening-fce-b2-test1',
    sourceDir: 'fce-Listening-test1',
    examType: 'fce',
    examMode: 'practice',
  },
  {
    kind: 'listening',
    slug: 'cae-c1-test1',
    examId: 'catalog-listening-cae-c1-test1',
    sourceDir: 'cae-Listening-test1',
    examType: 'cae',
    examMode: 'practice',
  },
]

const IELTS_FOLDER_RE = /^Listening IELTS_Test(\d+)_Cam(\d+)$/i

// IELTS Cam9–20 (48 đề) removed from builtin catalog per user request "Xóa sạch 48 đề mẫu".
// User will manually import correct versions from Tainguyen/IELTS/... via Import thủ công.
// To re-enable in future: restore discover + writeGenerated + include in BUNDLES.
async function discoverIeltsListeningBundles() {
  // DISABLED: return []
  // const ieltsRoot = path.join(TAINGUYEN, 'IELTS')
  // ... discovery removed to keep catalog clean of the 48 samples
  return []
}

async function writeGeneratedIeltsImports(ieltsBundles) {
  const outPath = path.join(ROOT, 'packages/catalog/src/generatedIeltsListening.ts')
  const lines = [
    '// AUTO-GENERATED by scripts/build-catalog.mjs — do not edit',
    '',
  ]

  const vars = []
  for (const bundle of ieltsBundles) {
    const varName = `ieltsCam${bundle.cam}Test${bundle.test}`
    lines.push(`import ${varName} from '../data/listening-${bundle.slug}.json'`)
    vars.push(varName)
  }

  lines.push('')
  lines.push('export const GENERATED_IELTS_LISTENING_EXAMS = [')
  for (const varName of vars) {
    lines.push(`  ${varName},`)
  }
  lines.push(']')
  lines.push('')

  await fs.writeFile(outPath, lines.join('\n'), 'utf8')
}

const MEDIA_EXT = new Set(['.jpg', '.jpeg', '.png', '.webp', '.mp3', '.wav', '.ogg'])

function catalogBase(kind, slug) {
  return `/catalog/${kind}/${slug}`
}

function mediaUrl(kind, slug, filename) {
  return `${catalogBase(kind, slug)}/${filename}`
}

function transformReading(payload, bundle) {
  const { examId, slug, cambridgeLevel, examTrack } = bundle
  const base = catalogBase('reading', slug)

  const parts = (payload.parts ?? []).map(partJson => {
    const partId = `${examId}-part-${partJson.partNumber}`
    const passage = (partJson.passage ?? []).map(blockJson => {
      const block = {
        label: blockJson.label,
        text: blockJson.text ?? '',
      }
      if (blockJson.imageFile) {
        block.imageUrl = mediaUrl('reading', slug, blockJson.imageFile)
      }
      return block
    })

    const questionGroups = (partJson.questionGroups ?? []).map((groupJson, groupIndex) => {
      const groupId = `${partId}-g${groupIndex}`
      const questions = (groupJson.questions ?? []).map(qJson => {
        const question = {
          id: `${partId}-q${qJson.number}`,
          number: qJson.number,
          type: qJson.type,
          prompt: qJson.prompt,
          options: qJson.options ?? [],
          answer: qJson.answer,
          explanation: qJson.explanation ?? '',
          answerConfidence: 'key',
        }
        if (typeof qJson.minWords === 'number') question.minWords = qJson.minWords
        return question
      })

      return {
        id: groupId,
        range: groupJson.range,
        instruction: groupJson.instruction,
        note: groupJson.note,
        type: groupJson.type,
        paragraphLetters: groupJson.paragraphLetters,
        features: groupJson.features,
        wordBank: groupJson.wordBank,
        questions,
      }
    })

    return {
      id: partId,
      partNumber: partJson.partNumber,
      rangeLabel: partJson.rangeLabel,
      passageTitle: partJson.passageTitle,
      passageSubtitle: partJson.passageSubtitle,
      passage,
      questionGroups,
    }
  })

  const partCount = parts.length
  const bandHint = (payload.bandHint ?? 'Cambridge Reading')
    + (partCount > 0 ? ` — ${partCount} part${partCount === 1 ? '' : 's'}` : '')

  return {
    id: examId,
    title: payload.title,
    durationMinutes: payload.durationMinutes ?? 60,
    bandHint,
    parts,
    examTrack,
    cambridgeLevel,
    catalogSlug: slug,
    catalogBase: base,
  }
}

function transformListening(payload, bundle, sourceDir) {
  const { examId, slug, examType, examMode } = bundle
  const sharedAudio = new Map()

  const parts = (payload.parts ?? []).map(partJson => {
    const partId = `${examId}-part-${partJson.partNumber}`
    let partAudioUrl

    if (partJson.audioFile) {
      const key = partJson.audioFile.toLowerCase()
      if (!sharedAudio.has(key)) {
        sharedAudio.set(key, mediaUrl('listening', slug, partJson.audioFile))
      }
      partAudioUrl = sharedAudio.get(key)
    }

    const questions = (partJson.questions ?? []).map(qJson => {
      const qId = `${examId}-q-${qJson.number}`
      let audioUrl
      if (qJson.audioFile) {
        const key = qJson.audioFile.toLowerCase()
        if (!sharedAudio.has(key)) {
          sharedAudio.set(key, mediaUrl('listening', slug, qJson.audioFile))
        }
        audioUrl = sharedAudio.get(key)
      }

      let pictureImageUrl
      if (qJson.type === 'picture-mc') {
        const boardCandidates = [
          qJson.imageFile,
          `q${qJson.number}.jpg`,
          `q${qJson.number}.jpeg`,
          `q${qJson.number}.png`,
          `part1-q${qJson.number}.jpg`,
        ].filter(Boolean)
        for (const name of boardCandidates) {
          if (existsSync(path.join(sourceDir, name))) {
            pictureImageUrl = mediaUrl('listening', slug, name)
            break
          }
        }
      }

      const options = (qJson.options ?? []).map(opt => {
        const option = { id: opt.id, label: opt.label }
        if (!pictureImageUrl && opt.imageFile) {
          option.imageUrl = mediaUrl('listening', slug, opt.imageFile)
        }
        return option
      })

      const question = {
        id: qId,
        number: qJson.number,
        type: qJson.type,
        prompt: qJson.prompt,
        options,
        answer: qJson.answer,
        explanation: qJson.explanation ?? '',
        pictureImageUrl,
        audioUrl,
        ttsText: qJson.ttsText,
        wordLimit: qJson.wordLimit,
      }
      if (qJson.context) question.context = qJson.context
      if (qJson.gapLead) question.gapLead = qJson.gapLead
      if (qJson.gapTrail) question.gapTrail = qJson.gapTrail
      if (qJson.noteBefore) question.noteBefore = qJson.noteBefore
      if (qJson.noteAfter) question.noteAfter = qJson.noteAfter
      if (qJson.contextFirst) question.contextFirst = qJson.contextFirst
      if (qJson.sectionRange) question.sectionRange = qJson.sectionRange
      if (qJson.sectionInstruction) question.sectionInstruction = qJson.sectionInstruction
      if (qJson.sectionTitle) question.sectionTitle = qJson.sectionTitle
      if (qJson.mapLabel) question.mapLabel = qJson.mapLabel
      if (qJson.diagramLabel) question.diagramLabel = qJson.diagramLabel
      if (qJson.flowChart) question.flowChart = qJson.flowChart
      if (qJson.flowChartEnd) question.flowChartEnd = qJson.flowChartEnd
      return question
    })

    const part = {
      id: partId,
      partNumber: partJson.partNumber,
      rangeLabel: partJson.rangeLabel,
      instruction: partJson.instruction,
      audioUrl: partAudioUrl,
      ttsText: partJson.ttsText,
      maxPlays: partJson.maxPlays,
      questions,
    }
    if (partJson.passageTitle) part.passageTitle = partJson.passageTitle
    if (partJson.audioIntro) part.audioIntro = partJson.audioIntro
    if (partJson.notePassage) part.notePassage = partJson.notePassage
    if (partJson.notePassageLayout) part.notePassageLayout = partJson.notePassageLayout
    if (partJson.noteTable) part.noteTable = partJson.noteTable
    if (partJson.noteTables) part.noteTables = partJson.noteTables
    if (partJson.notePassageSections) part.notePassageSections = partJson.notePassageSections
    if (partJson.imageFile && existsSync(path.join(sourceDir, partJson.imageFile))) {
      part.partImageUrl = mediaUrl('listening', slug, partJson.imageFile)
    }
    if (partJson.matchingDualTask) part.matchingDualTask = true
    if (partJson.taskOneInstruction) part.taskOneInstruction = partJson.taskOneInstruction
    if (partJson.taskTwoInstruction) part.taskTwoInstruction = partJson.taskTwoInstruction
    return part
  })

  return {
    id: examId,
    title: payload.title,
    durationMinutes: payload.durationMinutes ?? 35,
    bandHint: payload.bandHint ?? 'Cambridge Listening',
    examType: payload.examType ?? examType,
    examMode: payload.examMode ?? examMode,
    parts,
    catalogSlug: slug,
    catalogBase: catalogBase('listening', slug),
  }
}

/** Tainguyen bundles may ship as .zip only on CI — extract before read. */
async function ensureSourceDir(sourceDir, sourceName) {
  const examJsonPath = path.join(sourceDir, 'exam.json')
  if (existsSync(examJsonPath)) return

  const zipPath = path.join(TAINGUYEN, `${sourceName}.zip`)
  if (!existsSync(zipPath)) {
    throw new Error(`Missing source: ${examJsonPath} (no ${zipPath})`)
  }

  await fs.mkdir(sourceDir, { recursive: true })
  if (process.platform === 'win32') {
    const result = spawnSync(
      'powershell',
      ['-NoProfile', '-Command', `Expand-Archive -LiteralPath '${zipPath}' -DestinationPath '${sourceDir}' -Force`],
      { stdio: 'inherit' },
    )
    if (result.status !== 0) throw new Error(`Expand-Archive failed for ${zipPath}`)
  } else {
    const result = spawnSync('unzip', ['-o', zipPath, '-d', sourceDir], { stdio: 'inherit' })
    if (result.status !== 0) throw new Error(`unzip failed for ${zipPath}`)
  }

  if (!existsSync(examJsonPath)) {
    throw new Error(`After extracting ${zipPath}, still missing ${examJsonPath}`)
  }
}

async function copyMediaFiles(sourceDir, destDir) {
  await fs.mkdir(destDir, { recursive: true })
  const entries = await fs.readdir(sourceDir, { withFileTypes: true })
  let copied = 0
  for (const entry of entries) {
    if (!entry.isFile()) continue
    const ext = path.extname(entry.name).toLowerCase()
    if (!MEDIA_EXT.has(ext)) continue
    await fs.copyFile(path.join(sourceDir, entry.name), path.join(destDir, entry.name))
    copied += 1
  }
  return copied
}

async function main() {
  await fs.mkdir(DATA_OUT, { recursive: true })
  await fs.mkdir(PUBLIC_CATALOG, { recursive: true })

  const ieltsBundles = await discoverIeltsListeningBundles()
  const BUNDLES = [...STATIC_BUNDLES, ...ieltsBundles]
  // writeGeneratedIeltsImports skipped (ielts disabled)
  // await writeGeneratedIeltsImports(ieltsBundles)

  const manifest = {
    version: 2,
    builtAt: new Date().toISOString(),
    reading: [],
    listening: [],
  }

  for (const bundle of BUNDLES) {
    const sourceDir = path.join(TAINGUYEN, bundle.sourceDir)
    await ensureSourceDir(sourceDir, bundle.sourceDir)
    const examJsonPath = path.join(sourceDir, 'exam.json')
    const destDir = path.join(PUBLIC_CATALOG, bundle.kind, bundle.slug)

    const raw = JSON.parse(await fs.readFile(examJsonPath, 'utf8'))
    const mediaCount = await copyMediaFiles(sourceDir, destDir)

    let processed
    let outName
    if (bundle.kind === 'reading') {
      processed = transformReading(raw, bundle)
      outName = `reading-${bundle.slug}.json`
      manifest.reading.push({ id: bundle.examId, slug: bundle.slug, title: processed.title })
    } else {
      processed = transformListening(raw, bundle, sourceDir)
      outName = `listening-${bundle.slug}.json`
      manifest.listening.push({ id: bundle.examId, slug: bundle.slug, title: processed.title })
    }

    await fs.writeFile(
      path.join(DATA_OUT, outName),
      JSON.stringify(processed, null, 2),
      'utf8',
    )

    console.log(`✓ ${bundle.kind}/${bundle.slug} — ${mediaCount} media, → ${outName}`)
  }

  await fs.writeFile(
    path.join(DATA_OUT, 'manifest.json'),
    JSON.stringify(manifest, null, 2),
    'utf8',
  )

  console.log(`\nIELTS listening: ${ieltsBundles.length} đề (DISABLED - 48 Cam9-20 samples removed per "Xóa sạch 48 đề mẫu")`)
  console.log('\nCatalog build complete.')
  console.log(`  Public: ${PUBLIC_CATALOG}`)
  console.log(`  Data:   ${DATA_OUT}`)
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})