export const CAMBRIDGE_WRITING_COPY = {
  hubTitle: 'Luyện viết Cambridge A2–C2',
  hubDescription:
    'Chọn cấp độ trước — mỗi cấp độ có các dạng bài riêng như email, story và essay. Dễ tìm kiếm khi thư viện có nhiều đề.',
  openLibrary: 'Mở thư viện',
  modelAnswerCatalog: 'Thư viện bài mẫu',
  collapse: 'Thu gọn',
  expand: 'Mở',
  allLevels: 'Tất cả',
  testsLabel: 'đề',
  tasksLabel: 'bài viết',
  levelSearchPlaceholder: 'Tìm theo tên đề hoặc dạng bài...',
  levelLoading: 'Đang tải thư viện Writing...',
  levelNoSearchResults: 'Không tìm thấy đề phù hợp.',
  levelNoTests: 'Chưa có đề Writing nào cho cấp độ này.',
  levelUpdating: 'Nội dung đang được cập nhật.',
  levelInvalidRecordsAdmin: 'Có bản ghi Writing không hợp lệ.',
  levelUpdatingAdminHint: 'Nội dung Writing đang được cập nhật.',
  createTest: 'Tạo đề mới',
  editTest: 'Chỉnh sửa đề Writing',
  editDraft: 'Chỉnh sửa',
  saveDraft: 'Lưu bản nháp',
  savingDraft: 'Đang lưu...',
  draft: 'Bản nháp',
  localDraft: 'Bản nháp cục bộ',
  publishedSync: 'Bản đồng bộ đã xuất bản',
  seed: 'Đề mẫu hệ thống',
  cardPreview: 'Xem trước thẻ đề',
  openTest: 'Mở đề',
  testLoading: 'Đang tải đề...',
  testNotFoundTitle: 'Không tìm thấy đề Writing.',
  testNotFoundDescription: 'Đề này có thể là bản nháp chỉ dành cho admin hoặc không còn tồn tại.',
  testBackToLibrarySuffix: 'thư viện',
  testStructureHint: 'Giữ đúng cấu trúc Part/Task của đề thật.',
  taskOpen: 'Mở bài viết',
  taskChooseOne: 'Chọn một',
  taskCompulsory: 'Bắt buộc',
  taskLoading: 'Đang tải bài viết...',
  adminGuideButton: 'Hướng dẫn tạo đề',
  adminGuideTitle: 'Hướng dẫn tạo đề Writing',
  adminGuideSteps: [
    'Chọn đúng level',
    'Nhập thông tin đề',
    'Thêm task',
    'Kiểm tra preview',
    'Lưu bản nháp và mở thử task',
  ],
  adminGuideWarning:
    'Bản nháp hiện chỉ được lưu trên trình duyệt này. Nội dung chưa được xuất bản cho học viên.',
} as const

